### ISSUE TITLE
Mipmapping on texture groups is buggy

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6801] opened 2024-07-20 10:33 UTC
### Description
Mipmaps generated on texturegroups with `mip_markedonly` appears to have weird artefacts.

Turning them on globally with `mip_on` seems to be fine.

![image](https://github.com/user-attachments/assets/948d874e-0b9d-440c-bab5-96f178d8e182)

![image](https://github.com/user-attachments/assets/216449a7-03d4-4e68-8250-da3414af2cd3)

Its supposed to look like this:

![image](https://github.com/user-attachments/assets/f9bd2d60-2622-4b4e-907f-2953092b84a0)

### Steps To Reproduce
1. Run the sample project
2. Cycle through mip states with the space bar

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[31277a48-a40d-40e7-bede-7769b4818bef](https://api.gamemaker.io/api/github/downloads/31277a48-a40d-40e7-bede-7769b4818bef)

**Comment by JonnoRobson** [comment] 2024-07-30 15:28
Closing this as it appears to be a duplicate of the issue https://github.com/YoYoGames/GameMaker-Bugs/issues/6800 and the other issue has more detailed info and reproduction steps.

**Closed by JonnoRobson** 2024-07-30 15:28 UTC
Labels: runner-bug, project
