### ISSUE TITLE
Regression -  part_system_drawit ignore depth provided by matrix_build_lookat

### ISSUE THREAD

**Issue by Alkapivo** [YoYoGames/GameMaker-Bugs#7968] opened 2024-10-10 22:31 UTC
### Description

It is no longer possible to render particles on different depth by using `matrix_build_lookat` function. Last time it was working on runtime **v2024.6.1.208**. In current runtime particles are always rendered on depth of instance layer. The problem occurs while rendering directly to `application_surface` or to custom surface.

In **Sample Package** there are two videos, one from runtime **v2024.6.1.208** (`ParticleDepthBug-good.mp4`) which shows the correct behavior and one from runtime **v2024.8.1.218** (`ParticleDepthBug-bad.mp4`) which shows the wrong behavior.

**Sample package**: https://api.gamemaker.io/api/github/downloads/e3911985-5d65-474e-b172-b651d388b7dd
**Sample project**: [ParticleDepthBug.zip](https://github.com/user-attachments/files/17334902/ParticleDepthBug.zip)
**Sample project (with surface)**: [ParticleDepthSurfaceBug.zip](https://github.com/user-attachments/files/17334910/ParticleDepthSurfaceBug.zip)

### Expected Change

Particles rendering should work like in v2024.6.1.208 - e.g. depth can be changed with matrix_build_lookat

### Steps To Reproduce

1. Start GameMaker with runtime **v2024.6.1.208**.
2. Build & run the project.
3. Observe that particles are being rendered on different depth and Particle Z oscillates between 0.0 and 300.0.
4. Start GameMaker with runtime **v2024.8.218** or higher
5. Build & run the project
6. Observe that particles are always on the same depth (the same depth as the depth of the instance layer) while Particle Z oscillates between 0.0 and 300.0.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by pkraif** [comment] 2024-11-15 08:50
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/7561, which was fixed in https://github.com/YoYoGames/GMS2-Runner-Main/pull/217. Closing

**Closed by pkraif** 2024-11-15 08:50 UTC
Labels: runner-bug
