### ISSUE TITLE
MacOS Accessibility setting fails to work in GM IDE

### ISSUE THREAD

**Issue by inhalt120g** [YoYoGames/GameMaker-Bugs#8253] opened 2024-11-01 12:14 UTC
### Description

I have my MacOS set up so that it reads various things when I point the mouse over them for reasons of accessibility. For example, when there's a prompt asking me whether I want to overwrite an already existing file and I place the cursor over the "Replace" button, the MacOS will announce "Replace file" using the system voice.

This works well in all apps I have installed, except in Gamemaker and one other program, where it works only for menus but nothing else. For example, if I want to create a new sprite and place my pointer over the "create new" button in the Assets panel, nothing happens even if I keep my mouse there for a few minutes (it's supposed to happen after a few seconds).

### Expected Change

I'd like to hear the announcement of whatever is being pointed at.

### Steps To Reproduce

0. Make sure you turned on the accessibility settings under "Open System Settings > Accessibility > Spoken Content" and turn on "Speak Announcements" (or whatever it's called in English, it's the second option from the bottom).
1.  Start GameMaker
3. Start a dummy project
4. Click on a menu, for example "File" and leave the cursor there. The announcer will say "File" (or the equivalent of whatever language the GameMaker is set to use).
5. Now place your mouse cursor over the "+" button in the Asset panel. The announcer fails to activate.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sequoia

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-11-01 12:18
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3727

**Comment by YYDan** [comment] 2024-11-01 12:19
This one is a very large change and so it's been on the backlog for a while, sorry.

**Closed by YYDan** 2024-11-01 12:18 UTC
Labels: ide-bug
