### ISSUE TITLE
 The underwater effect does not work on switch

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#2458] opened 2023-12-12 10:42 UTC
### Description

I would like to repost this serious problem since my previous post on this subject was closed without providing a solution (https://github.com/YoYoGames/GameMaker-Bugs/issues/2339).
The latest update of GMS 2 does not correct the problem (which I have reported numerous times to the developers without response from them)

Reproduction protocol: Start the Windy Woods project on switch. Stay next to a water source without moving for several minutes. You will notice that the water moves less and less quickly, until it no longer moves at all. reloading the room does not correct the problem.
This is a problem that seems serious enough to prevent my game from being published on Switch.

This problem does not occur on PC, only on switch

### Steps To Reproduce

1. Start the Windy Woods project on switch
2.  Stay next to a water source without moving for several minute
3. You will notice that the water moves less and less quickly, until it no longer moves at all. reloading the room does not correct the problem.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Switch

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2023-12-13 09:35
Duplicate of #2181 
As above, you can fix yourself just now if need be, or it'll be fixed in the February release.

**Closed by stuckie** 2023-12-13 09:35 UTC
Labels: runner-bug
