### ISSUE TITLE
matrix funcs that operate on existing matricies

### ISSUE THREAD

**Issue by coyo-t** [YoYoGames/GameMaker-Bugs#7317] opened 2024-08-16 21:33 UTC
### Is your feature request related to a problem?

dont want more array object creations

### Describe the solution you'd like

parallels or modifications to the existing matrix funcs that take a destination rather than returning a new array

```gml
// create
var viewm = matrix_build_identity()
var projm = matrix_build_projection_perspective(...)
var projviewm = matrix_build_identity()

// draw
matrix_build(-x,-y,-z, pitch,yaw,0, 1,1,1, viewm)

matrix_multiply(projm, viewm, projview)
```

should also be able to take Matrix Constants instead of matricies themselves (since creating a new copy of the arrays with `matrix_get` would defeat the purpose
```gml
matrix_identity(matrix_world)

matrix_build(x,y,z, pitch,yaw,0, 1,1,1, matrix_view)
matrix_multiply(matrix_projection, matrix_view, viewprojm)
```

### Describe alternatives you've considered

writing them myself in gml (and have done but is far slower than if they were natively a part of the engine)

**Comment by YYDan** [comment] 2024-08-19 08:45
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/4205

**Closed by YYDan** 2024-08-19 08:45 UTC
Labels: feature request
