### ISSUE TITLE
LTS: Last login always showing as "Currently Offline" even when freshly logging in 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7275] opened 2024-08-14 05:23 UTC
### Description

The LTS homepage is always showing "Currently Offline" as the most recent login, even when I log out and then log in again. It will update the date, but still say offline. I first encountered this a week or so ago, and waited a bit to see if it was some sort of server issue that would fix itself, but it's still the same.
![image](https://github.com/user-attachments/assets/ef6a77cb-41c7-45d4-9a66-c723feaa6614)

It is still letting me export, but that might just be the offline grace period, not sure.

### Steps To Reproduce

Open LTS, log in if you're not already. It will say currently offline. Log out and log in again, the date will update but it will still say currently offline.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-08-14 08:58
Yeah, we saw this one ourselves and so this has been fixed already ahead of the next LTS release

**Comment by YYDan** [comment] 2024-08-14 08:58
Duplicate of https://github.com/YoYoGames/YoYoStudio/issues/10449

**Closed by YYDan** 2024-08-14 08:58 UTC
Labels: ide-bug
