### ISSUE TITLE
[Manual] There is NOT documentation about dbg_* functions

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#2657] opened 2024-01-06 02:36 UTC
### Description

Yeah i know this functions are still on the beta branch, but many beta functions had manual entries.

**Comment by L-Clouds** [comment] 2024-01-07 01:05
Please clarify what you are not seeing and where you are not seeing it.  For reference, here is what I see (screenshot attached)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/6913402/0cd51ea3-34c4-4706-aa3b-7701a1782c0e)

**Comment by stuckie** [comment] 2024-01-08 10:29
Closing as duplicate of #2660

**Closed by stuckie** 2024-01-08 10:29 UTC
Labels: docs-bug
