### ISSUE TITLE
Feather: CRASH when adding new functions in parent constructor

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2091] opened 2023-11-02 13:08 UTC
### Description
In latest beta (Beta IDE v2023.1100.0.425 Beta Runtime v2023.1100.0.439), when trying to add new function inside constructor which is extended by another constructor, IDE crashes.

It happens when writing new function, and adding `)` or `}` characters, when there's nothing between them and opening bracket.

### Steps To Reproduce
1. Open attached project (alternatively - same code is in #2090 )
2. Try to write a new function inside `qty_selector`:
```gml
test = function()
```
or
```gml
test = function(_arg) {}
```

as soon as you write `)` in first case or `}` in second case, game would crash. Sometimes they need to be prefixed with `static`.

[49f97ad4-380f-41fa-9839-c9d5de2a48a5](https://api.gamemaker.io/api/github/downloads/49f97ad4-380f-41fa-9839-c9d5de2a48a5)

**Comment by zreedy** [comment] 2023-11-07 17:32
Fixed. Recently another ticket regarding static and constructor function inheritance was fixed. This fix did not account for recursive constructor function declarations. In this ticket's example the assignment of `test =` was being interpreted as an assignment of the following function inside of the body of the first one resulting in a recursive declaration.
A new error message GM1039 warning of recursive constructor function declarations has been added. This is different from the other error of using the base function and recursion occurring.

**Comment by alicemoretti** [comment] 2023-11-08 16:19
Issue still appears on Beta IDE v2023.1100.0.435 Beta Runtime v2023.1100.0.448 . It happens on closing the backets for the new function. 

I've attached the new ui.log for reference. 

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/13299000/ui.log)

**Comment by gnysek** [comment] 2023-11-13 15:28
Seems to work on  IDE v2023.1100.0.437  Runtime v2023.1100.0.450 .

**Comment by zreedy** [comment] 2023-11-13 16:17
@alicemoretti Reproduced the issue with the steps you provided. The issue is related to the same cyclic dependency but the origin in different. This one is in rendering the diagnostic squiggles.

**Comment by DragoniteSpam** [comment] 2023-11-13 16:35
is "diagnostic squiggles" the technical term

i really hope it is

**Comment by zreedy** [comment] 2023-11-13 16:36
Yes, it is the documented term.

**Comment by zreedy** [comment] 2023-11-13 20:00
Fixed once more, passed desk testing with a few additional tests. Please disregard previous comments about issue being rooted in Diagnostic Squiggle rendering as this was a red herring.

_For QA_
There are multiple ways to introduce a cyclic dependency with constructor functions. Previous fixes for this were tested against the repro steps in the original ticket. Further reports have revealed additional avenues of introducing a cyclic dependency which are as follows:

Condition 1
```gml
function qty_selector(_min = 1, _max = 9999) constructor {
	test = function () 
}
function small_qty_selector(_min = 1, _max = 99) : qty_selector(_min, _max) constructor {
	a = function wow() : small_qty_selector(1, 2) constructor { }
}
```

Condition 2
```gml
function qty_selector(_min = 1, _max = 9999) constructor {
	test = function () 
}
function small_qty_selector(_min = 1, _max = 99) : qty_selector(_min, _max) constructor {
	a = function wow() : small_qty_selector(1, 2) constructor { }
}
// } // terminating brace may be added to clear a new GM1100 condition
```

Two underlying issues were identified and have potentially far reaching implications, in condition order:
1. `function () ... ` without an initiating `{`, but with a terminating `}` was being incorrectly parsed as BlockExpression with all expressions being parsed as part of that block. This is incorrect. Now the parser returns an empty block and marks a GM1100 "Expected '{' but found '}''. This change fixes block nesting occurring where it would otherwise be impossible to write such syntax. This means that there might be edge cases (due to an impossible AST being passed to the Compiler) that are now fixed; this also means that there might be regressions (unlikely) in error reporting around these cases.
2. Previous fix was to track the inheritance stack check during Discovery when diving base ctor funcs. This, unfortunately, does not work for Rediscovery since Rediscovery (when triggered by Discovery) does not share the inheritance stack (and cannot because we cannot promise it's valid between Discovery instances). A (hopefully only slightly) slower approach has been implemented to walk ancestry to determine if we can dive inheritance. _It is possible there are other ways to break this check, but none have been discovered in desk testing_

**Comment by alicemoretti** [comment] 2023-11-16 15:56
On  IDE v2023.1100.0.441  Runtime v2023.1100.0.453, the original issue is fixed. 
Adding Condition 1 and/or 2 to a new script or object also works as expected. 

However, adding either Condition 1 or Condition 2 to the original project (the one in the attached zip file) makes the IDE crash. I'm not sure what's happening there. 

Reopening the bug. Thank you.

**Comment by gnysek** [comment] 2023-11-17 08:03
For me it just crashed on such code:

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/98d8e3fd-3327-4b48-a01e-5b676e048be2)

**Comment by zreedy** [comment] 2023-11-17 18:52
Fixed with the additional repro steps provided by @alicemoretti. My Condition 1 and 2 were meant to replace the contents of the script in question in the original ticket post. However, when you paste them in addition to the contents of the original ticket's script the check in Discovery gets caught in a recursive loop due to the "can dive" check confusing the functions that are parented (there are now 2 "qty_selector" functions). The "can dive" check now checks function _name_ not _context reference_.

The crash outlined in @gnysek's `static` are different and are detailed in https://github.com/YoYoGames/GameMaker-Bugs/issues/2224

**Closed by zreedy** 2023-11-17 18:52 UTC
Labels: ide-bug, project

**Comment by gnysek** [comment] 2023-11-22 09:55
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/d7ec0298-c483-48d9-b9f4-69024872e95d)

IDE freezes for me in such case, when I wanted to press backpace...

**Comment by cameron-home** [comment] 2023-12-04 14:28
Verified fixed for every different repro step listed above in IDE v2023.11.0.120  Runtime v2023.11.0.157.
