### ISSUE TITLE
Performance: G-Sync can cause flickering when using GameMaker

### ISSUE THREAD

**Issue by RhyminGarfunkle** [YoYoGames/GameMaker-Bugs#6515] opened 2024-07-03 20:35 UTC
### Description
Upon launching the IDE, the entire screen (even parts of the screen that aren't part of the GameMaker IDE, like the Windows start bar) begin rapidly flickering any time any portion of the IDE window visually changes. I believe this is VRR, or Variable Refresh Rate, flicker, which can happen on G-Sync or Freesync monitors when the frame rate rapidly changes, because disabling G-Sync causes the issue to disappear entirely.

The flicker starts any time anything on the screen changes. This includes events like scrolling a code window, having new text appear on the GameMaker start screen, or even just moving the mouse around. The flicker takes the form of rapidly oscillating the screen brightness at what I believe is the monitor refresh rate, and lasts for half a second or so.

This flicker does not appear when using most other applications. The only other time it happens is during loading screens for some 3D games, or during particularly graphically intense scenes in those games. Other windowed applications, like web browsers or 3D CAD programs, do not cause this flicker to occur.

The flicker does not occur if GameMaker is not the focused window. For example, if I have GameMaker maximized and another non-maximized window in focus over the GameMaker window, I can move the mouse over the GameMaker window and scroll the workspace up and down using the middle mouse wheel with no screen flicker. If I click on the GameMaker window to bring it into focus and do the same thing, the flicker will happen as I scroll around.

I have a second monitor with a fixed 60hz refresh rate, and the flicker does not affect that monitor. Flicker does not appear on either monitor when using GM on the 60hz monitor. It DOES appear when the GM window is stretched across both monitors, but only on the g-sync compatible monitor - the 60hz monitor remains unaffected.

There are guides on the internet for reducing VRR flicker, but they do not make the issue go away, they only lower the intensity of the flicker. The only fix is to fully disable G-Sync from the Nvidia control panel.

According to the control panel, G-Sync should only be used on full-screen applications, but for some reason it appears to be used with GameMaker as well. Setting GameMaker to used a fixed refresh rate in the Nvidia control panel does not fix the issue, G-Sync must be disabled globally to fix the issue.

### Steps To Reproduce
Run GameMaker on a system with an Nvidia graphics card capable of G-Sync and a G-Sync compatible monitor (my monitor uses AMD Freesync, which Nvidia considers compatible with G-Sync). My monitor is an AOC AG241QG, and my graphics card is an Nvidia GeForce RTX 4060 TI. Ensure that G-Sync is on in the Nvidia control panel.

You should immediately see the flicker as text like "use processing" appears on the start screen, and continue to see flicker as you do normal activities like move the mouse around the screen. It's more apparent in a dim room or at night, but can be observed in a brightly sunlit room.

Turning G-Sync off will cause the flicker to stop, but will also disable G-Sync for all applications.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[dc40863f-370c-4e92-b034-96330b74df1f](https://api.gamemaker.io/api/github/downloads/dc40863f-370c-4e92-b034-96330b74df1f)

**Comment by YYDan** [comment] 2024-07-04 16:23
2024.6.1 will add a new Preference for turning Vsync back on inside GM, which should hopefully stop the issues.

**Comment by RhyminGarfunkle** [comment] 2024-07-09 20:37
In 2024.6.1, on first opening the IDE the flicker issue went away, but each time I would change focus from the GM IDE to something else, or put focus back on the IDE, my entire monitor went dark for a couple seconds like I was changing the display settings. Turning off vsync in the general settings stopped this, but brought back the flicker.

When I tried to re-enable vsync in the IDE, the screen didn't go dark, but the flicker didn't go away either. It appears that the check box works to turn vsync _off_, but not back _on_. I've tried cycling the box and restarting the IDE several times, and have reverted all by GPU settings to defaults.

**Comment by stuckie** [comment] 2024-07-09 23:17
That's interesting as all it's doing is saving a boolean out as #6533 shows, and reading it in on startup.
You'll be able to find this file at %programdata%\GameMakerStudio2\dpi_override.json
Assuming you don't have a dpi override setting, deleting that file will set it back to a clean slate.

**Comment by RhyminGarfunkle** [comment] 2024-07-09 23:33
The json file matches the IDE setting of vsync enabled:

`[{"Key":"vsync_enabled","Value":true},{"Key":"is_enabled","Value":true},{"Key":"value","Value":96}]`

but I still see the flickering no matter what  Again, I didn't see it when I initially opened 2024.6.1 (just the issue with the screen going dark every time focus changed) but now it won't go away no matter what the vsync setting is.

**Comment by RhyminGarfunkle** [comment] 2024-07-09 23:39
Disabling freesync from the Nvidia control panel still makes the flicker issue go away, regardless of the GM vsync setting.

**Comment by JimiThing85** [comment] 2024-07-10 20:18
The screen flickering thing also happens to me, running in Windows 11.  I also get "stuttering" when G-Sync is enabled, huge temporary FPS drops for a second or two before it recovers, only to happen again a few seconds later.  Additionally, I can't seem to turn off V-sync at all in the IDE since the last patch:  the minute I close the preferences window, V-sync toggles back to displaying as enabled.

**Comment by stuckie** [comment] 2024-07-11 10:32
You should get a message to restart the IDE when you toggle it and click Apply, as we have to set it on startup.

**Comment by RhyminGarfunkle** [comment] 2024-07-11 10:40
I do get the message, and restart the IDE as it says is needed. The box checks or unchecks, and as I mentioned the settings in dpi_override.json reflect what I've selected, but changing the setting doesn't appear to actually enable or disable vsync (or if it does, then vsync has nothing to do with the flickering issue, which wouldn't make sense for multiple reasons)

I've tried restarting both from the popup message, and from ignoring the message and manually restarting.

**Comment by stuckie** [comment] 2024-07-11 11:39
Ah, that was mean as a reply directly above... but yes, that's weird, as the preference is literally just turning on and off the line we changed for June.
Having it set on should make the IDE behave like 2024.04/April again, where as off should make it behave as 2024.06.0... it's not doing anything else but changing how we present frames to the graphics card.

I am wondering if we have tripped over a driver issue, which is why forcing it in your NVidia control panel is the only thing that's making a difference. Frustrating...

**Comment by JimiThing85** [comment] 2024-07-11 18:50
> You should get a message to restart the IDE when you toggle it and click Apply, as we have to set it on startup.

Yeah, I don't get the popup at all when toggling v-sync in preferences.  Clicking apply doesn't trigger any popup for me.  Running latest version of Gamemaker 2 IDE, v2024.6.1.160.  If it helps, I've got a 3080 GPU, running on driver version 556.12

**Comment by stuckie** [comment] 2024-07-19 14:51
The first August/2024.800 beta has been released, and this includes pending updates to the rendering and windowing libraries we use.. hopefully this has had an effect in improving things.

As for the VSync preference not popping up a restart prompt, I'm not sure how that isn't working.
You should be able to toggle it on/off, then on pressing Apply you should get this
![image](https://github.com/user-attachments/assets/9010bff5-aa70-4a34-a8cd-36887d045056)


The alternative is modifying the dpi_override.json file manually, but that isn't something you should need to do.

**Comment by RhyminGarfunkle** [comment] 2024-07-20 00:03
I still see the flickering issue on the new beta. As before, it only goes away when I disable gsync globally.

When I first opened the beta and tried to toggle the vsync settings, I also didn't get the confirmation dialog after hitting apply, which I did on the stable release. I had to go into the JSON file and enable DPI override (at 100 percent, so it didn't really change anything) to start seeing the confirmation box. But even after I started getting the confirmation box, toggling vsync from inside GM didn't change anything.

**Comment by stuckie** [comment] 2024-08-06 10:40
Ah hah.. I've reproduced one of the issues here.
If there is no dpi_override.json present, then yes, toggling the VSync does nothing in the IDE, nor do you get the above warning.
So I'll get this fixed.

However, VSync is still on by default, as it was in 2024.4.. so I wonder if the driver has saved a profile for GameMaker which is getting in the way.
On the NVIDIA Control Panel I have, I can go to Manage 3D Settings -> Program Settings where I get a screen like this:
![Image](https://github.com/user-attachments/assets/c68f6b39-275a-4d22-9bad-ca7deaecac7d)


You might be able to force VSync on/off here, or even restore the defaults for the driver, as I'm starting to clutch at straws a bit, as to what else could have changed in-between!

**Comment by RhyminGarfunkle** [comment] 2024-08-08 00:23
The program-specific vsync options from the NVIDIA control panel - on, off, and fast - don't have any effect on the flickering in the GameMaker IDE. The only program-specific option that seems to make a difference is Monitor Technology - the default, "G-SYNC Compatible", causes flicker, while "Fixed Refresh" does not. This tracks with the flickering going away with disabling G-SYNC globally.

The issue with that is, with only GM set to Fixed Refresh, is frequent full-monitor blackouts that last several seconds, the sort of blackout you get when you change the screen resolution or some other monitor function. They happen when I switch focus to a different program, focus back on GameMaker, or even take certain actions inside GameMaker (it seems sort of random, I can't figure out what specific actions cause it). It's much more convenient to just disable G-SYNC globally when I'll be using GameMaker for an extended period, then re-enable it when I'll be playing a game or something.

(Of course most convenient of all would be just not needing to worry about this anymore, as was the case with previous versions of GM, so I appreciate your continued work on this!)

**Comment by RhyminGarfunkle** [comment] 2024-08-08 00:30
Could it have something to do with GameMaker behaving like a full-screen program even though it's windowed? According to the NVIDIA control panel, G-SYNC should only be enabled for full-screen applications, so I'd expect toggling it on and off not to have any effect on the windowed GameMaker, and yet it does.

**Comment by stuckie** [comment] 2024-08-19 11:35
Ok.. here's something silly to try that might help us pin this down a bit - though please back things up before doing so.
Install the 2024.4 version of the IDE ( or whichever version worked )
Copy the SDL2.dll and FNA3D.dll files into the current Beta.

So, assuming 2024.4 is the installed monthly ( or again, whichever version does not cause the flickering ) this should be copying:
C:\Program Files\GameMaker Studio 2\FNA3D.dll -> C:\Program Files\GameMaker Studio 2-Beta\FNA3D.dll
C:\Program Files\GameMaker Studio 2\SDL2.dll -> C:\Program Files\GameMaker Studio 2-Beta\SDL2.dll

And see if that helps. I've at least checked that 2024.4.0.137's SDL2/FNA3D set works against a current Beta, but it's very much a "here be dragons" thing.
That at least pins it down to an update within those, which should have just been general stability updates, but perhaps a fix for detecting G-SYNC properly has went in, and we're not handling it at the application end.
If it does work, that should keep you going for a little while, until we can pin down exactly what's needing to be fixed.

**Comment by stuckie** [comment] 2024-09-24 15:30
The current 2024.1100 beta should hopefully have this fixed. Please let us know if this is the case, if you are able to test this.

**Comment by RhyminGarfunkle** [comment] 2024-09-24 18:05
Yep, everything appears to be working as it should in beta 2024.1100. Thanks, can't wait for the changes to make it to the main release!

**Comment by stuckie** [comment] 2024-09-25 08:16
Lovely, thanks for confirming! And no, there's no need now!

**Comment by stuckie** [comment] 2024-10-10 16:29
Going to close this now since we've not heard of any other issues.
However, should anyone else has an issue with 2024.1100 betas onwards, please submit a new bug report and we'll have another look.

Thanks!

**Closed by stuckie** 2024-10-10 16:29 UTC
Labels: ide-bug

**Comment by Emc1923** [comment] 2024-10-14 17:14
Closing as per comments. Thanks!
