### ISSUE TITLE
Command Line Builds: Igor doesn't build projects in 2024.6.1.208 runtimes

### ISSUE THREAD

**Issue by SofaTreat** [YoYoGames/GameMaker-Bugs#7248] opened 2024-08-13 11:35 UTC
### Description

I updated to v2024.6.2.162 runtime v2024.6.1.208 and now Igor no longer builds. 

this is my run.ps1 file

Igor.exe /uf="C:\Users\DoomMachine\AppData\Roaming\GameMakerStudio2\***my user name***" /rp="C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2024.6.1.208" /project="W:\forgotten_game.yyp" /cache="C:\dump\gamemaker\forgotten" /temp="C:\dump\gamemaker\forgotten" -- Windows Run

and this is what Igor spits out. 

PowerShell 7.4.4
PS W:\>  ./run.ps1
Options: C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2024.6.1.208\bin\platform_setting_defaults.json
Options: C:\Users\DoomMachine\AppData\Roaming\GameMakerStudio2\***my user name***\local_settings.json
Setting up the Asset compiler
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=***'. Could not find or load a specific file. (0x80131621)     
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=***'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=***'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name)
   at Igor.Program.InitialiseAssetCompiler()
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)      
   at Igor.Program.Main(String[] args)
Igor complete.
PS W:\> 

### Steps To Reproduce

1. Start Powershell
2. run the run.ps1 file from the w: drive. (I subst a project to its own w: drive to make everything easier.)
3. Igor fails to build.
4. I can build the game from the gamemaker IDE just fine. This is just and Igor thing.

link to the package.zip:

the package file was too big to upload and I don't feel comfortable having a public link to it

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-08-13 12:48
"link to the package.zip:

the package file was too big to upload and I don't feel comfortable having a public link to it"

As is written on the bug-reporter itself and on all our various literature pages for reporting bugs, if you use the IDE to report bugs then ALL files are private.

**Comment by stuckie** [comment] 2024-08-14 08:37
As Dan said above, your included files through the bug reporter will be private.. we will need these to verify where the issue is.

I'll close this ticket just now so that you can create a new one with the required files.

**Closed by stuckie** 2024-08-14 08:37 UTC
Labels: build-bug
