### ISSUE TITLE
[IDE] During startup on MacOS, dropdown menu items are `String not found`

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5591] opened 2024-04-21 03:33 UTC
### Description

While the IDE is booting (this is a _very_ minor bug as you can tell), the top bar menu items are all "string not found":
<img width="382" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/ffa91241-449c-47f0-9be2-4f2b78daa7ff">

### Steps To Reproduce

1. Start the IDE under MacOS.
2. Open a top bar.
3. _Observe most minor bug imaginable._
4. When the IDE is ready, the items will correctly populate.

This is easiest to catch if the IDE needs to download a runtime as that takes a while keeping it in this state for that duration.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

**Comment by YYDan** [comment] 2024-04-22 08:31
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1561

**Closed by YYDan** 2024-04-22 08:31 UTC
Labels: ide-bug
