### ISSUE TITLE
Still crash with 2024.4 version

### ISSUE THREAD

**Issue by BL1TTZ0** [YoYoGames/GameMaker-Bugs#5750] opened 2024-05-04 02:49 UTC
### Description

I'm still experiencing the error with the new version 2024.4.

I can't start old, current, or blank projects on the Windows platform.

I can run them in GX.Games with F5 but not with the debugger.

I've already tried reinstalling GameMaker, deleting the IDE and reinstalling it again, reverting to an older version, not using GameMaker from Steam and installing it separately. Nothing works.

Creating an executable runs the game fine, but it doesn't work when running it in GameMaker.

### Expected Change

Can excecute my games on Windows with and without debbuger as normal

### Steps To Reproduce

1. Start GameMaker
2. Run the game
3. Crash

[Contact_File.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15206417/Contact_File.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment] 2024-05-07 10:21
I've tested the enclosed project and it runs for me fine. It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.

**Closed by jackerley** 2024-05-07 10:21 UTC
Labels: build-bug, project

**Comment by BL1TTZ0** [comment] 2024-05-16 23:30
I found the problem, leaving this here as it might be useful to you all.

I tried everything recommended and nothing worked, to the point where I had to format my computer to keep working. That solved the problem.

While I was working and putting everything back as it was, I changed the game's audio output from Windows, and out of nowhere, the error reappeared. Neither F5 nor the debugger worked, and it crashed every second.

Since it was so straightforward, I thought: It can't be just this... And indeed, it is just that.

Points to clarify:
- This never happened with previous versions.
- I use the "ElGato" driver to manage my audio outputs, it might have a conflict.
- The audio output was changed with the game running and changed from the Windows 10 sound manager; upon rebooting, it crashes.

**Comment by toby-yoyo** [comment] 2024-05-17 09:42
@BL1TTZ0 What is the exact name of the Elgato software you are using?

**Comment by BL1TTZ0** [comment] 2024-05-17 15:40
Software: Elgato Wave Link
Comes with the Elgato Wave: 3 microphone

**Comment by toby-yoyo** [comment] 2024-05-24 16:21
Unfortunately we're not able to use the software without the hardware so there isn't a lot we can do to reproduce the issue ourselves. If you were able to provide us with a crash dump (see C:\ProgramData\GameMakerStudio2\Dumps) then we may be able to work with that.

**Comment by cconroy** [comment] 2025-03-28 13:40
I also experience this bug with the Elgato Stream Deck XL. The Stream Deck doesn't need to manage audio like the mic AFAIK, but the wave link driver is still installed by the Stream Deck software.
