### ISSUE TITLE
array slow adding elementa

### ISSUE THREAD

**Issue by anabah122** [YoYoGames/GameMaker-Bugs#5483] opened 2024-04-13 22:25 UTC
### Is your feature request related to a problem?

 arrays now work slowly if you insert
many elements into them sequentially.
this happens because at the engine level, the buffer does not double when it is full

### Describe the solution you'd like

to make the array initially agree on its size when overflowing and then cut off all unfilled elements, now I can implement this in gml :

arr = array_create(100000)

for i=0; i<1000; i++
arr[i]=irandom(999)

array_resize(arr,i)

or 

arr=[]

for i=0; i<1000; i++
{
if i>=array_length(arr)-1 then array_resize(arr, array_length(arr)*2
arr[i]=irandom(999)
}
there are also cases when I can't find out the exact size of the final array

I don't understand why the array works this way , it's not justified because any way to declare it except array_create will be consistent , and therefore very slow. I propose to introduce an increase in the size of the array buffer by half when overflowing at the engine level

### Describe alternatives you've considered

-

### Additional context

you can easily compare the speed with this code:

start = current_time; arr=[]
for i in 1000000
arr=irandom(999)
print ( current_time- start )

start = current_time; arr=[]

for i=0; i<100000; i++ {
if i>=array_length(arr)-1 then array_resize(arr, array_length(arr)*2
arr[i]=irandom(999)
}
array_resize( arr, i)
print ( current_time- start )

**Comment by DragoniteSpam** [comment] 2024-04-14 01:11
see: 3022

**Comment by stuckie** [comment] 2024-04-15 09:30
Duplicate of #3022

**Closed by stuckie** 2024-04-15 09:30 UTC
Labels: feature request
