### ISSUE TITLE
Code won't work

### ISSUE THREAD

**Issue by Pandiyaya** [YoYoGames/GameMaker-Bugs#8363] opened 2024-11-10 18:51 UTC
### Description
Whenever I write code it runs but does nothing, I would like to know what is doing this please as I am following an official tutorial but the instructions aren't leading anywhere

### Steps To Reproduce
Run the project

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

### Attached Files
* tinygame 2.0.yyp

[9dddd1da-7639-4d85-902c-6c6f36e49d4f](https://api.gamemaker.io/api/github/downloads/9dddd1da-7639-4d85-902c-6c6f36e49d4f)

**Comment by stuckie** [comment] 2024-11-11 10:06
This is not a bug with GameMaker itself, but one in your project, so I will close this issue now. For coding support, please visit the [GameMaker Community](https://forum.gamemaker.io/index.php) forum and create a thread there, asking for advice.

**Closed by stuckie** 2024-11-11 10:06 UTC
Labels: build-bug, project
