### ISSUE TITLE
Code Editor 2: Using Ctrl+Z to undo pasting of code which includes semicolons into the middle of other text leads to unexpected results

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5544] opened 2024-04-17 21:05 UTC
### Description

Using 'Ctrl+Z' in CE2 to undo the pasting of a code block including semicolons leads to strange results.

If the pasted segment is only a single line then it results in visual glitches while undoing with 'Ctrl+Z'. The remaining code seems to shift to the right for a brief second before setteling in its correct position.
In the following GIF all I do is paste the code into the line and then press 'Ctrl+Z' to undo it.

![ctrl_z_glitch_01](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/0e0d2adf-db03-4bcc-be6a-2adfd8721393)

The effect gets worse when you undo the pasting of a multi-line segment. Then the code doesn't go back into its original structure but the line where you inserted the block gets split into two lines after the undo.
Again, in the following GIF all I do is paste the code into the line and then press 'Ctrl+Z' to undo it.

![ctrl_z_glitch_02](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/34efdc18-8b17-4514-a994-50ed5eab3114)

### Steps To Reproduce

1. See example GIFs,

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment] 2024-06-27 21:20
Unable to reproduced. I suspect that this issue is essentially a duplicate of other color coding issues that have been fixed now.

**Closed** 2024-06-27 21:20 UTC
Labels: ide-bug
