### ISSUE TITLE
Right-Click Sprite(s) in Asset Browser -> Create Object(s) from Sprite(s)

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#5179] opened 2024-04-02 08:00 UTC
### Is your feature request related to a problem?

A very common workflow is creating objects and then assigning a sprite to them. It could be improved by providing a right-click menu item for this very core procedure.

### Describe the solution you'd like

1. Select one or multiple sprites in the asset browser
2. Right click - menu pops open
3. Create Object(s) from Sprite(s)

Using Feather defined naming scheme (or anything else) it would create the objects and assign the sprites they are made from.

### Describe alternatives you've considered

.

**Comment by backYard321** [comment] 2024-04-02 17:32
big fan of this idea! not sure if naming conventions could be used to generate a name for this object as well.

**Comment by YYDan** [comment] 2024-08-20 14:34
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3714

**Closed by YYDan** 2024-08-20 14:34 UTC
Labels: feature request
