### ISSUE TITLE
Trying to use the Exception struct inside a Catch silently crashes

### ISSUE THREAD

**Issue by cenowador** [YoYoGames/GameMaker-Bugs#6814] opened 2024-07-21 12:02 UTC
### Description
When using a try/catch block, if an exception occur and you try to use the generated struct inside the catch scope in any way, the game simply closes without warning or message

### Steps To Reproduce
1. create a try/catch
2. force an exception
3. try to log any property of the exception struct
4. game closes

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[d7537167-7fdf-4ed4-8d36-bc38411491a1](https://api.gamemaker.io/api/github/downloads/d7537167-7fdf-4ed4-8d36-bc38411491a1)

**Comment by YYDan** [comment] 2024-07-22 09:14
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6190

**Closed by YYDan** 2024-07-22 09:14 UTC
Labels: runner-bug, project
