### ISSUE TITLE
Code editor 2: tabs do not copy correctly when copy pasting

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5234] opened 2024-04-02 17:36 UTC
### Description
If you copy paste some code that has tabbed if statements, the tabs are lost in the pasted code past the first if statement.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/a88ef377-8b0a-4f9f-8ffa-6e63a1552244

### Steps To Reproduce
```
// copy paste this chunk!
if outsideThing {
    if thing { 
        
    }
    if otherThing {
        
    }
    if otherOtherThing {
        
    }
}

```
after pasting:
```
if outsideThing {
    if thing {
        
    }
if otherThing {
    
}
if otherOtherThing {
    
}
}
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[6b65ea7c-0088-4d54-9f5f-94b2a9ea84ae](https://api.gamemaker.io/api/github/downloads/6b65ea7c-0088-4d54-9f5f-94b2a9ea84ae)

**Comment by DragoniteSpam** [comment] 2024-04-16 23:54
Interestingly, I almost always have a problem with tabs going the *opposite* way when I copy and paste stuff.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/a0df61a2-10b9-4c2a-89d3-52004c00fc20)

**Comment by zreedy** [comment] 2024-11-21 19:34
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6708

**Closed by zreedy** 2024-11-21 19:34 UTC
Labels: ide-bug, project
