### ISSUE TITLE
Code Editor 2: No Code Completion prompted when adding a moment function in a sequence

### ISSUE THREAD

**Issue by mmMarzban** [YoYoGames/GameMaker-Bugs#6103] opened 2024-06-03 21:20 UTC
### Description

In latest Beta (24.600.562) when you try to add a moment on a sequence frame, it doesn't recognize any function that you enter. Whereas, in the last monthly it worked pretty fine, but apparently this beta has broken this important feature. In fact previously when you began to write the name of the function, by typing the first letter, GameMaker used to suggest and auto-complete the function name. But this in not the case in the last beta and caused me to switch my project back to the monthly stable.

### Steps To Reproduce

1. Start GameMaker
2. Define a function with the name for example: myFunc
3. Create a sequence (with for example 60 frames)
4. put the head on a random frame and try to add a moment and assign the above function to it.
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment] 2024-06-04 16:18
Hi, this looked to be working for me in Beta 562 - 
![2024-06-04 16_47_49-6103-beta562-seqMoment - GameMaker-Beta](https://github.com/YoYoGames/GameMaker-Bugs/assets/8818217/56ec4923-8171-401c-b636-fdf3997551a7)
-is it perhaps possible you have Code Editor 2 enabled in the preferences? This functionality does not appear to be implemented at present for Code Editor 2. If you are not using Code Editor 2, I will likely need a ui.log and test project to diagnose.

**Comment by mmMarzban** [comment] 2024-06-04 17:34
> Hi, and thank you for your report. This looked to be working for me in Beta 562 - ![2024-06-04 16_47_49-6103-beta562-seqMoment - GameMaker-Beta](https://private-user-images.githubusercontent.com/8818217/336529247-56ec4923-8171-401c-b636-fdf3997551a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjI3MTAsIm5iZiI6MTcxNzUyMjQxMCwicGF0aCI6Ii84ODE4MjE3LzMzNjUyOTI0Ny01NmVjNDkyMy04MTcxLTQwMWMtYjYzNi1mZGYzOTk3NTUxYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTczMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNlZjI2ZmUzNzkzMjM0M2E3OTE2ODQ3ZjFjMjQ1NDZlNGE3NGE0MDJlYzA3M2E5MmEyNTYzMTVkYzNhNTdhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Rswtoo4P_8m57geI1R52jXHlUx9SepsE6YS6xdX-igg) -is it perhaps possible you have Code Editor 2 enabled in the preferences? This functionality does not appear to be implemented at present for Code Editor 2. If you are not using Code Editor 2, I will likely need a ui.log and test project to diagnose.

Yes, in fact I am using CE2. So that's the problem?

**Comment by mmMarzban** [comment] 2024-06-04 17:44
I disabled the CE2 and restarted GM and it now works fine. Thank you. Can I hope that in the next beta, I would be able to use moment functions with the CE2 as well?

**Comment by zreedy** [comment] 2024-06-18 14:00
With regards to the title change, you can still create functions it's merely that the code completion window doesn't prompt. All critical services are in tact.

**Comment by mmMarzban** [comment] 2024-06-20 12:26
> With regards to the title change, you can still create functions it's merely that the code completion window doesn't prompt. All critical services are in tact.
You "can" create functions, but you can't assign it to a moment in sequence. Because as soon as you write the function's name and hit Enter, the name gets red and an exclamation mark shows up. So no function is added to the moment.

**Comment by mmMarzban** [comment] 2024-06-20 12:27
> With regards to the title change, you can still create functions it's merely that the code completion window doesn't prompt. All critical services are in tact.

**You "can" create functions, but you can't assign it to a moment in sequence. Because as soon as you write the function's name and hit Enter, the name gets red and an exclamation mark shows up. So no function is added to the moment.**

**Comment by zreedy** [comment] 2024-07-05 21:43
Closing as duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6479
The linked issue also explores other manifestations of this issue.

**Closed by zreedy** 2024-07-05 21:43 UTC
Labels: ide-bug
