### ISSUE TITLE
Accessing self from inside the instance create event returns an instance ID instead of the self struct

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#6777] opened 2024-07-19 08:57 UTC
### Description

Code snippet example:

```
/// @description Insert description here
// You can write your code in this editor

// function bound to self
func = function() {
	show_debug_message("From inside A!");
}

// the self here is an Id.Instance
var _self = method_get_self(func);

// the self here will become the struct of the instance
with (_self) {
	_self = self;
}

// This should be possible because _self IS a valid struct type 
var _weak_ref = weak_ref_create(_self);
```

This used to be possible and is now not possible with 800 beta.

[access_self_from_inside_create_event.zip](https://github.com/user-attachments/files/16309763/access_self_from_inside_create_event.zip)

### Expected Change

Fix the regression bug

### Steps To Reproduce

1. Start GameMaker
2. Run the demo project 
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment] 2024-07-19 10:13
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6765 Fixed in 2024.8

**Closed by rwkay** 2024-07-19 10:13 UTC
Labels: runner-bug
