### ISSUE TITLE
Building Projects: Compiler does not flag self/other/noone/all as getters or as dynamic variables

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#7731] opened 2024-09-22 01:18 UTC
### Description

`self`, `other`, `noone`, and `all` still uses the -1 through -4 id format, which gets optimized by the compiler when attempting to use them, they are not flagged as getter functions, nor as dynamic variables.

### Steps To Reproduce

```gml
//prints -1
show_debug_message(string(self))
//prints a struct
var _self = self
show_debug_message(string(_self))
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment] 2024-09-25 00:58
This is not a bug and is due to the way the current compiler was written - the real fix for this is GMRT (which has a rewritten compiler) - this is not something that will change in the short term.

**Closed by rwkay** 2024-09-25 00:58 UTC
Labels: ide-bug
