### ISSUE TITLE
Feather doesn't understand the types of Variable Definitions defined as expressions

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5528] opened 2024-04-17 04:43 UTC
### Description
Whenever you define something in a Variable Definition as an "expression" (ie any ol code that runs in PreCreate) Feather just assumes it's "undefined."

### Steps To Reproduce
look in obj_object_one Create event

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[ade869bb-c5ff-4293-bfcb-67dfec758dbd](https://api.gamemaker.io/api/github/downloads/ade869bb-c5ff-4293-bfcb-67dfec758dbd)

**Comment by DragoniteSpam** [comment] 2024-04-17 05:00
Okay this is probably the same bug as #2162

**Comment by stuckie** [comment] 2024-04-17 08:54
Duplicate of #2162
Closing as above.

**Closed by stuckie** 2024-04-17 08:54 UTC
Labels: ide-bug, project
