### ISSUE TITLE
Code Editor 2: Tabs are removed when pasting code

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6243] opened 2024-06-13 11:03 UTC
### Description
In CE2, when doing Ctr+V, all tab characters in current line are removed.

### Steps To Reproduce
1. Write some code, put `Tab` before it *
2. Paste something

_*when inside function, two tabs might be needed, as 1 tab is auto-indent_

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[6f4f83b9-fc06-49e6-97ae-6c84130b80d6](https://api.gamemaker.io/api/github/downloads/6f4f83b9-fc06-49e6-97ae-6c84130b80d6)

**Comment by zreedy** [comment] 2024-08-30 21:14
Fixed. The behavior of "Auto Indent clipboard contents" has been modified so that it no longer attempts to pretty print the pasted contents using the tab stop calculation heuristics. New behavior instead calculates the appropriate tab stop for the line that the paste occurs on and then formats the leading whitespace in the pasted text given a delta between the pasted text's first line and the correct tab stop. This results in the formatting of the pasted text being retained, but with the leading whitespace adjusted to the appropriate tab stop.

**Comment by cameron-home** [comment] 2024-09-19 14:42
Verified fixed in IDE v2024.1100.0.623  Runtime v2024.1100.0.649

**Comment by cameron-home** [comment] 2024-09-19 15:45
I'll try these repro steps now where I cut the code that was already there and paste it in. I was testing it by pasting in other code on the line where the original code was.

**Comment by cameron-home** [comment] 2024-09-19 15:47
I cannot repro the above in IDE v2024.1100.0.623  Runtime v2024.1100.0.649. What version are you using @gnysek ?

**Comment by gnysek** [comment] 2024-09-19 15:51
IDE v2024.1100.0.623  Runtime v2024.1100.0.649
 
 I would wait for official release. Also, it might be one of those bugs that happens depending to PC locale.

**Comment by cameron-home** [comment] 2024-09-19 16:04
Upon further investigation, we can only reproduce when we double tab within a function, and when there are two or more lines of code being cut and pasted. If we only tab once (like with the autoindent), we cannot reproduce. If we cut and paste with only one line of code, we cannot reproduce.

I will reopen for further investigation.

**Comment by gnysek** [comment] 2024-09-20 08:02
Yes, this happens for more than one line of code.

Also, it is very important for text to contain `"\t"` not spaces, as I have feeling that "tab" character is replaced with one space after pasting, and that's main issue. Pasting text which is tabbed with spaces works much better.

Also, issues with pasting are different depending on CE2 setting of preferred tabs character.

**Comment by zreedy** [comment] 2024-09-26 14:28
Yes the tabs are replaced with spaces, that is configurable via your preferences.

**Comment by gnysek** [comment] 2024-09-26 14:35
Issue is, that it paste space bo matter what. And replaces tabs to ONE space. Or removes them completely. Depending on situation.

**Comment by zreedy** [comment] 2024-09-26 14:37
@cameron-home I tested the behavior against the conditions you specified and it appears to be the expected behavior to me. It's adjusting the tab stops to the correct tap stop (1 tab stop), even if the pasted code had 2 leading tab stops. The relative indentation is preserved

![GameMaker_7auR8FiP7e](https://github.com/user-attachments/assets/c41dbd8a-57d0-4a48-9254-a485a899d87c)

This is correct behavior.

**Comment by zreedy** [comment] 2024-09-26 14:39
@gnysek I do not observe that behavior...
![GameMaker_roub9RjbVO](https://github.com/user-attachments/assets/d80acb6c-30f3-44a8-8271-ecd2a6977aa0)

**Comment by gnysek** [comment] 2024-09-26 14:47
I will submit exact steps in few hours on latest beta IDE then as I'm out of home now. Except you're on some internal IDE and it's fixed there...

**Comment by gnysek** [comment] 2024-09-26 21:38
@zreedy 
ok, little late, but my tests.
Text used for testing:
```
// this is my example test
	// first - one tab
	  // tab + 2 spaces
        // 8 spaces
  	// 2 spaces + tab
			// 3 tabs
            // 12 spaces
  	  // 2 spaces + tab + 2 spaces
  		  // 2 spaces, 2 tabs, 2 spaces
// final line
```

After my testing, I've noticed, that setting "Auto indent clipboard contents" it's one which causes contents to change. 
In case of `Tab Type = Space`, all Tabs are converted to "Tab size" settings (so in my case tab = 4 spaces), spaces are kept as spaces, and that have sense.
In case of `Tab Type = Space`, all Tabs remains tabs, but spaces are floored down (so in my case 4 spaces = 1 tab, but 1,2,3 spaces = nothing).

I understand that this is expected behaviour (even if it requires some deeper thinking to find out why), so I'm skipping that "tab rounding issues", but that means one bug remains:

### **Paste text, when `Tab Type` == `Space`, `Auto Indent clipboard` = ON, and there's indented in line:**

On first line, 4 spaces are changed to 1 space. I feel that instead of "put one tab equivalent" (1 tab or 4 spaces in my case) it does "put one character of tab type" (1 tab or 1 space).

![obraz](https://github.com/user-attachments/assets/40d72ea0-e0c4-4e50-b589-fdaf6ce2a2e3)
![obraz](https://github.com/user-attachments/assets/2d3d8653-0cf0-4a8e-b48d-5cb25a2b1dd0)

Why I'm thinking that it puts 1 character of "Tab type", instead of "tab size" of characters?
Here's another example - when there are "two tabs" (so, 4 spaces), pressing enter gives 2 spaces (so 2x Tab Type character, instead of 2x Tab size):
![obraz](https://github.com/user-attachments/assets/2a92d1ba-9b80-4130-8b78-42a526255151)
![obraz](https://github.com/user-attachments/assets/bda192d4-45ba-48e2-8add-193224ed3b20)

**Comment by gnysek** [comment] 2024-09-26 21:47
Also, if code was indented, cut, and pasted, it's lost no matter which setting is applied, as long as "Auto Indent clipboard contents" i selected, for both Tab and Space as Tab type:

![GIF 26 09 2024 23-46-58](https://github.com/user-attachments/assets/37f0fefd-57a7-4685-8fc4-2d6478b34ff2)

**Comment by zreedy** [comment] 2024-10-24 19:50
This is not a bug, this is expected behavior. When pasting, if you have the option set the code will be formatted so the whitespace will be updated. The kind of whitespace replaced will be dependent on your Tab Type setting.

**Closed by zreedy** 2024-10-24 19:50 UTC
Labels: ide-bug
