### ISSUE TITLE
Auto-Tile Brushes can't be duplicated

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#2069] opened 2023-10-31 10:04 UTC
### Description
Currently auto-tile setups can't be duplicated which makes it very tedious if you want to create a bunch of variations of the brushes.

[e418b874-26f0-4d11-bbea-a8814503b4af](https://api.gamemaker.io/api/github/downloads/e418b874-26f0-4d11-bbea-a8814503b4af)

**Comment by YYDan** [comment] 2023-11-06 10:48
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1817

**Closed by YYDan** 2023-11-06 10:48 UTC
Labels: ide-bug
