### ISSUE TITLE
CE2: Pressing CTR+M in a object in the Match 3 Template corrupt every fold region

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6240] opened 2024-06-13 03:05 UTC
### Description
as title, watch video too.

### Steps To Reproduce
1) Match 3 Template
2) Go to obj_matching_piece
3) Press CTR+M
4) D:

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[d5ec39b1-0667-4b89-a28a-b2ef9413b9c3](https://api.gamemaker.io/api/github/downloads/d5ec39b1-0667-4b89-a28a-b2ef9413b9c3)

**Comment by stuckie** [comment] 2024-07-26 14:42
Duplicate of #5549

**Closed by stuckie** 2024-07-26 14:43 UTC
Labels: ide-bug, project
