### ISSUE TITLE
int64 And (or perhaps shift left/shift right) are incorrectly truncating to 32 bits

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#8120] opened 2024-10-24 14:03 UTC
```
enum LargeEnum {
	Zero = 0,
	One = 1,
	Two = 1 << 1,
	Three = 1 << 2,
	Four = 1 << 3,
	Five = 1 << 4,
	Six = 1 << 5,
	Seven = 1 << 6,
	Eight = 1 << 7,
	Nine = 1 << 8,
	Ten = 1 << 9,
	Eleven = 1 << 10,
	Twelve = 1 << 11,
	Thirteen = 1 << 12,
	Fourteen = 1 << 13,
	Fifteen = 1 << 14,
	Sixteen = 1 << 15,
	Seventeen = 1 << 16,
	Eighteen = 1 << 17,
	Nineteen = 1 << 18,
	Twenty = 1 << 19,
	TwentyOne = 1 << 20,
	TwentyTwo = 1 << 21,
	TwentyThree = 1 << 22,
	TwentyFour = 1 << 23,
	TwentyFive = 1 << 24,
	TwentySix = 1 << 25,
	TwentySeven = 1 << 26,
	TwentyEight = 1 << 27,
	TwentyNine = 1 << 28,
	Thirty = 1 << 29,
	ThirtyOne = 1 << 30,
	ThirtyTwo = 1 << 31,
	
	FULL = LargeEnum.One
		| LargeEnum.Two
		| LargeEnum.Three
		| LargeEnum.Four
		| LargeEnum.Five
		| LargeEnum.Six
		| LargeEnum.Seven
		| LargeEnum.Eight
		| LargeEnum.Nine
		| LargeEnum.Ten
		| LargeEnum.Eleven
		| LargeEnum.Twelve
		| LargeEnum.Thirteen
		| LargeEnum.Fourteen
		| LargeEnum.Fifteen
		| LargeEnum.Sixteen
		| LargeEnum.Seventeen
		| LargeEnum.Eighteen
		| LargeEnum.Nineteen
		| LargeEnum.Twenty
		| LargeEnum.TwentyOne
		| LargeEnum.TwentyTwo
		| LargeEnum.TwentyThree
		| LargeEnum.TwentyFour
		| LargeEnum.TwentyFive
		| LargeEnum.TwentySix
		| LargeEnum.TwentySeven
		| LargeEnum.TwentyEight
		| LargeEnum.TwentyNine
		| LargeEnum.Thirty
		| LargeEnum.ThirtyOne
		| LargeEnum.ThirtyTwo
}

show_debug_message(typeof(LargeEnum.ThirtyOne));
show_debug_message(typeof(LargeEnum.ThirtyTwo));
show_debug_message(typeof(LargeEnum.FULL));


if (LargeEnum.FULL & LargeEnum.ThirtyOne == LargeEnum.ThirtyOne) {
	show_debug_message("that worked");
} else {
	show_debug_message("full did not contain thirty one");
}

if (LargeEnum.FULL & LargeEnum.ThirtyTwo == LargeEnum.ThirtyTwo) {
	show_debug_message("that worked");
} else {
	show_debug_message("full did not contain thirty two");
}
```

This prints out:

```
int64
int64
int64
that worked
full did not contain thirty two
```

This tells me that the bit math is truncating to 32 bits incorrectly.
(yes, we do have an enum entry with this many members in Fields of Mistria)

**Comment by rwkay** [comment] 2024-10-28 21:00
Unable to replicate on HEAD of `develop` branch - please check on latest Beta...

**Comment by rwkay** [comment] 2024-11-22 15:48
Looks like issue is on non-Windows machine - reopening

**Comment by rwkay** [comment] 2024-11-25 16:18
Fixed in 2024.11 - looks like some odd handling in the C# side when handling int64s and doubles.

**Closed by rwkay** 2024-11-25 16:18 UTC
Labels: runner-bug

**Comment by YYDan** [comment] 2024-12-11 17:54
Made an actual sample [truncationTest.zip](https://github.com/user-attachments/files/18100088/truncationTest.zip)

And confirmed this works fine in Nov 11 - 

![Image](https://github.com/user-attachments/assets/4d54941c-980e-4f4c-9f5a-3854afaf4393)

Worked fine in Aug also, but as our issue template was (somehow) not used for some reason I have no idea which version it did _not_ work in - and current Nov IDEs cannot use older Nov runtimes, so it's tricky working out when it was ever broken.

Please do use our standard issue templates whenever reporting anything in future, rather than omitting valuable information.

**Comment by YYDan** [comment] 2024-12-11 18:07
Note that HTML5 does show a difference between Aug and Nov - however, not the results originally documented above.

Aug:
![Image](https://github.com/user-attachments/assets/30594c02-8494-4c0d-94b4-0c25d78929b9)

Nov:
![Image](https://github.com/user-attachments/assets/384dcc7b-f5e1-4042-b4d8-a638ffa18d08)
