### ISSUE TITLE
Crash when opening sprite in a project that imported sprite from package

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#5375] opened 2024-04-07 15:47 UTC
### Description
Hey there,

bad news, I see this directly related to #4955 which I reported as bug and which got changed to "Feature Request" on your end.

This is not a feature request, this is a bug. The resource structure of the receiving project gets destroyed.
I hope you can get useful information from the crash dump!

Thanks for reading,
cheers
Gris

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[18824255-aed6-48fc-aaac-3c2ebf2226cd](https://api.gamemaker.io/api/github/downloads/18824255-aed6-48fc-aaac-3c2ebf2226cd)

**Comment by stuckie** [comment] 2024-04-10 11:07
Closing as duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5333

**Closed by stuckie** 2024-04-10 11:07 UTC
Labels: crash, dump
