### ISSUE TITLE
[Project Load] Attempting to load a project from LTS results in "Record polymorphism requires a header field"

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7909] opened 2024-10-05 12:40 UTC
### Description
Seems that attempting to load any project made in LTS, results in this error. 
<img width="377" alt="GameMaker-Beta_2024-10-05_22-42-08" src="https://github.com/user-attachments/assets/54ab0e6c-1583-4cb1-9bea-cc07ba5739bc">
Upon further inspecting, it seems like that the Project Tool wasn't even being used at all. I was able to further confirm this by manually converting it myself, and then loading up the project. This works perfectly.
<img width="405" alt="GameMaker-Beta_2024-10-05_22-16-51" src="https://github.com/user-attachments/assets/c680c0ec-237c-4e7a-a32a-6115e6f6b6d3">

This issue was originally noticed with Input, but affects just about any project currently in LTS. The project format does not change at all when attempting to load.

### Steps To Reproduce
1. Load any GameMaker LTS project (You may use the LTS Sample Project I've included) .
2. See Error message.

// Making it load
3. Goto Tools -> Project Tool. Add the LTS project as a source, set the conversion type to DEFAULT and convert it.
4. Load up the converted project.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files
* LTS Sample Project.zip

[8be708d8-cc65-4da4-86aa-f9e74a98697a](https://api.gamemaker.io/api/github/downloads/8be708d8-cc65-4da4-86aa-f9e74a98697a)

**Comment by gnysek** [comment] 2024-10-05 15:56
That's same error message that in #7771 .

**Comment by stuckie** [comment] 2024-10-07 08:51
Duplicate of #7771

**Closed by stuckie** 2024-10-07 08:51 UTC
Labels: ide-bug
