### ISSUE TITLE
In-Game [YYC]: Undefined named parameters are being set to 1503 in YYC

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1520] opened 2023-08-16 13:25 UTC
GM-8109

When running a project in YYC, when setting a named parameter to undefined, it returns 1503 instead. 

This is an example: 

```
function foo(z) {
ASSERT_NEQ(z, 1503);
}
```
called like so:
```
foo();
```
crashes at that assert (ASSERT_NEQ means "assert not equal", and will crash the game if the values equal each other).
{code}

*Steps to reproduce:*
- See comments on how to access the project
- Run the project in YYC 
- Observe the issue

**Comment by rwkay** [comment] 2023-09-21 19:10
duplicate of https://github.com/YoYoGames/GameMaker/issues/2854

**Closed by rwkay** 2023-09-21 19:10 UTC
Labels: ide-bug, import

**Comment by YYDan** [comment] 2023-09-22 08:09
Confirmed dupe.
