### ISSUE TITLE
GMS2 preferences occasionally get stuck for a long time

### ISSUE THREAD

**Issue by arrosev** [YoYoGames/GameMaker-Bugs#7344] opened 2024-08-19 14:38 UTC
### Is your feature request related to a problem?

When I click the File -> Preferences -> Text Editors -> Code Editor, the IDE will freeze for 2 seconds before displaying the “Code Editor” screen. And then the most important problem is that when I pull the “Code Editor” screen down to the bottom, then click the “Cancel” button and the IDE will freeze for a very long time, about 3-4 seconds.

### Describe the solution you'd like

I hope it's so that when I change the IDE settings in Preferences, it doesn't freeze the whole IDE

**Comment by YYDan** [comment] 2024-08-19 14:44
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1935

**Closed by YYDan** 2024-08-19 14:44 UTC
Labels: feature request
