### ISSUE TITLE
Silent crash in YYC but not VM

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6767] opened 2024-07-18 18:24 UTC
### Description
The project runs fine in VM but crashes with non-zero status (-1073741819) in YYC. 

This might be caused by playing an audio whose audio group is not loaded yet. However, in VM, the error can be caught, while in YYC, the runner just crashes.

### Steps To Reproduce
1. Run the project for Windows YYC under the `gamepipe_test_debug` config. See that after the character is attacked by enemies, the game crashes with the non-zero status (-1073741819).
2. Run the project for Windows VM and see it does not crash. Search in the Output logs for "Error: Audio group for snd_wompit_attack (2) is not loaded" and 
"Index did not map to an existing audio asset or sound instance", see that they are present.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
iOS, Windows

[97e46ea9-1e5d-4428-8b2d-11b1c0183ea6](https://api.gamemaker.io/api/github/downloads/97e46ea9-1e5d-4428-8b2d-11b1c0183ea6)

**Comment by rwkay** [comment] 2024-07-19 09:06
Duplicate of #6759

**Closed by rwkay** 2024-07-19 09:06 UTC
Labels: runner-bug, project

**Comment by mgeddesGM** [comment] 2024-07-24 11:31
verified as duplicate by previous comment
