### ISSUE TITLE
Manual Content: instance_nearest() page code sample needs updating after refs feature added in 2023.8

### ISSUE THREAD

**Issue by SebastienGllmt** [YoYoGames/GameMaker-Bugs#4622] opened 2024-02-05 05:44 UTC
### Description

The [docs for `instance_nearest`](https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FInstances%2Finstance_nearest.htm) currently contains the following snippet

```gml
var inst, xx;
xx = x;
x -= 10000;
inst = instance_nearest(xx, y, object_index);
if inst != id
{
    draw_line(x, y, inst.x, inst.y);
}
x += 10000;
```

However, this no longer works because `instance_nearest` now returns a ref, but `id` is still of type `real` (note: I'm building for HTML5 so maybe this is related to https://github.com/YoYoGames/GameMaker-Bugs/issues/1746 )

Instead, the proper code to fix this is to use `inst.id == id`

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FInstances%2Finstance_nearest.htm

**Comment by YYDan** [comment] 2024-02-06 14:15
Can see this has been assigned as if a runner bug also - will need clarification on what is _actually_ changing here if this turns out to be more than a docs issue.

**Comment by SebastienGllmt** [comment] 2024-02-06 18:57
After changing the code to `inst.id == id`, the example works for me in HTML5. Since #1746 is closed, I assume it's not a runner bug and this is the intended behavior (and it's just the docs that are outdated)

**Comment by pkraif** [comment] 2024-02-13 13:59
I'm closing the issue as I'm not able to reproduce it in the 2024.02 development branch. This issue is not specific to function `instance_nearest`, but to handling instance IDs/refs in HTML5 as a whole, so it was probably fixed as part of another issue.

**Closed by pkraif** 2024-02-13 13:59 UTC
Labels: runner-bug, docs-bug

**Comment by YYDan** [comment] 2024-03-01 15:57
Confirmed that no manual change is required also, as the issue apparently did not reproduce when using the content in the manual,
