### ISSUE TITLE
Image Editor: Color palette broken in 2024.11 beta

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7918] opened 2024-10-06 10:57 UTC
### Description
In the image editor, the color palette for selecting colors appears to be totally busted. It only shows a single row of transparent squares, and none of them can be clicked.

![image](https://github.com/user-attachments/assets/71a78748-f8dd-4984-9079-8b707e270cb9)

### Steps To Reproduce
Open the image editor and look at the "Colours" panel

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[abec1aee-47b7-4478-ae0e-8188763231cd](https://api.gamemaker.io/api/github/downloads/abec1aee-47b7-4478-ae0e-8188763231cd)

**Comment by stuckie** [comment] 2024-10-07 09:03
Duplicate of #7774

**Closed by stuckie** 2024-10-07 09:03 UTC
Labels: ide-bug
