### ISSUE TITLE
show_debug_message color argument

### ISSUE THREAD

**Issue by Vethergen** [YoYoGames/GameMaker-Bugs#6690] opened 2024-07-15 22:15 UTC
### Is your feature request related to a problem?

The `show_debug_message()` text in the output window is all the same color and quickly gets messy as a project grows.

### Describe the solution you'd like

A color argument for `show_debug_message("Warning...",c_red")` like so would be a game changer to quickly differentiate at a glance... Warnings, flow control, "Game saved!" kind of stuff.

### Additional context

![XaDcTd4](https://github.com/user-attachments/assets/6f22eaa5-b474-468b-8676-3fe763f0f1b9)

**Comment by Foxtrio** [comment] 2024-07-15 22:34
Big yes!

**Comment by ParodyKnaveBob** [comment] 2024-07-15 23:27
This **might** need to be a new function -- `show_debug_message_colour()`? `show_debug_message_format()`? -- due to `show_debug_message()` already having optional arguments for displaying values, but being able to format in **some** way **could** be nice, yes. Otherwise, it's always differentiating by caps or spaces or punctuation (like `=============` etc.) or what-have-you.

**Comment by Vethergen** [comment] 2024-07-16 00:50
The multiple values thing might as well just be replaced since you can just toss anything you want into an array, which is what I've always done for some reason anyway 😅 `show_debug_message([val,val,val],color);`

**Comment by Alphish** [comment] 2024-07-16 08:42
Another alternative would be a function like `show_debug_set_colo(u)r(background,foreground)` or similar, which would change the output colours from that moment forward. Then we don't need to mess with `show_debug_message` function (as changing how its optional arguments work would inevitably break some potential current code) nor figure out the best argument order for a function that merges setting colours and printing messages functionality.

(and from there, it's easy enough to do something like `function show_error(_error) { show_debug_set_color(c_red, c_black); show_debug_message(_error); show_debug_set_color(c_black, c_silver); }` or similar function.

**Comment by GameDevTosh** [comment] 2024-07-16 10:57
If some sort of color isn't possible, even just allowing a highlight like old dos programs would be nice.

**Comment by rwkay** [comment] 2024-07-16 19:16
This is a duplicate of other bugs https://github.com/YoYoGames/GameMaker-Bugs/issues/3428 and #4844  and #4849

**Comment by YYDan** [comment] 2024-07-29 10:13
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3428

**Closed by YYDan** 2024-07-29 10:13 UTC
Labels: feature request
