### ISSUE TITLE
In-Game: [Windows] Gamepad input becomes unreliable after minimising the game or when external software like OBS is also running

### ISSUE THREAD

**Issue by BerserkBoyGames** [YoYoGames/GameMaker-Bugs#4569] opened 2024-01-30 17:22 UTC
### Description

Players are noticing control inputs are going haywire when they minimise the game for a while (this only happens on the pc config) Or if they open someting like OBS

This happens when they're using a controller (and the d-pad + buttons seem to start responding incorrectly)

if you're using a controller, it can't determine whether it's a keyboard / controller and all the tutorial assets begin to rapidly switch.and you can no longer move properly as the movement begins to stutter nd the player can't walk properly.

Replicaiton notes are difficult as they're not always consistent but
(opening OBS) or some sort of software also triggers this but, again.. it's not consistent.

This has happened throughout QA and early reviewers are seeing it now. We've had our first reviewer on the Steam deck reach out after leaving the game minimised by triggering standby on the steam deck and rebooting the steam deck

"* Think I've encountered a bug - don't know if you're aware of it - and I don't know if this is just the Steam Deck version causing this.

I've had two instances where I'm playing and the buttons become unresponsive. It doesn't seem to matter which button - jump, attack, even the start button. They suddenly only work one out of every 4 or 5 presses."

it's as if the controls start fighting with eachother.

The secondary programmer is assured* its a GM bug but i'm 100% sure it's not as i've never seen thios before in any other GM game.

video link: of tutorial assets conflicting between PC and XBOX controlls + movement acting funny with D Pad

Build: Demo build as starting the demo takes you to the stage where this issue happens so you can try replicate it easily.
(all of the code base is the same)

Appreciate the time and help provided!

(My Discord is : zu ) btw

links for internal team 
* movie - https://drive.google.com/file/d/1NIKrRlKhBIvSdZywpB8G17-ZMB8DCsuP/view?usp=sharing
* project - https://drive.google.com/file/d/1Pd1mbz2Wbfwzbhy7-n_W9gpltl4AdL0k/view?usp=sharing

### Expected Change

Find out if there's a clash happening between controller inputs (switch is fine) issue is with controller + Keyboard

### Steps To Reproduce

1. Start GameMaker
2. load into a new file / start game 
3.   once done try open obs, when the game is minimised .. or try with it open (tough to replicate) -// plug in controller during cutscene.  // leave minimised for a while and reload //  --  run around with the dpad on controller 
4. you should be stuttering movement
5. See the issue

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment] 2024-01-31 17:38
Hi @BerserkBoyGames,

I've tried a few times to reproduce your issue using the "FutureGamesShow" configuration in your demo project and not managed to reproduce it, either by launching OBS before/while the game is running or leaving it minimised for 5+ minutes after switching away with alt+tab.

I can get a similar effect (although more severe) by holding down a key (e.g. shift) while moving with the D-Pad, and from watching your video, I believe the check at line 25 of InputObj's step event (`INPUT_DEVICE_CURRENT == Devices.Pad && keyboard_check(vk_anykey)`) may be getting hit (since it shows the prompt switching between keyboard/pad buttons), suggesting the game is periodically detecting a keyboard key being pressed in this state.

Please let me know if you know of anything else I can try to reproduce this issue.

**Comment by BerserkBoyGames** [comment] 2024-02-01 11:16
Hey there!

Thank you for replicating that, seems like some sort of conflict between controllers is happening then!

We’ve put in a fix after replicating your notes! Hopefully that fixes it

Thank you very much
Zu

On 31 Jan 2024, at 17:38, Daniel Collins ***@***.***> wrote:

﻿

Hi @BerserkBoyGames<https://github.com/BerserkBoyGames>,

I've tried a few times to reproduce your issue using the "FutureGamesShow" configuration in your demo project and not managed to reproduce it, either by launching OBS before/while the game is running or leaving it minimised for 5+ minutes after switching away with alt+tab.

I can get a similar effect (although more severe) by holding down a key (e.g. shift) while moving with the D-Pad, and from watching your video, I believe the check at line 25 of InputObj's step event (INPUT_DEVICE_CURRENT == Devices.Pad && keyboard_check(vk_anykey)) may be getting hit (since it shows the prompt switching between keyboard/pad buttons), suggesting the game is periodically detecting a keyboard key being pressed in this state.

Please let me know if you know of anything else I can try to reproduce this issue.

**Comment by yoyo-danielc** [comment] 2024-06-05 16:28
Closing as unable to reproduce.

**Closed by yoyo-danielc** 2024-06-05 16:28 UTC
Labels: runner-bug
