### ISSUE TITLE
`zip_unzip` and `zip_unzip_async` don't extract to the chosen directory

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#6304] opened 2024-06-17 02:30 UTC
### Description

This exists on Monthly and LTS.

```gml
var _file_count = zip_unzip("testFile.zip", working_directory)
log(_file_count) // outputs :: 2
log(working_directory) // outpues :: C:\Users\Red\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\doot_doot_7A0BEB64_VM\
```
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/5cee459f-0252-4ca8-96cf-db3e4d8631ba)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/35880000-60b1-4ec7-a214-c1e9c4cec32c)
Here is the test zip i've been working with:
[testFile.zip](https://github.com/user-attachments/files/15860825/testFile.zip)

I have tried many prefixes for the directory, as well as sandbox on and off, yet none of them seem to effect it.

### Expected Change

should extract

### Steps To Reproduce

supplied above, just include a zip file with some files in it.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly), 2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by tinkerer-red** [comment] 2024-06-17 02:31
They might be extracting, but if so there is zero way to find out where that would be. Though if the zip target is valid the async event is never fired off when using `zip_unzip_async` So I suspect it doesn't even reach that far.

**Comment by YYDan** [comment] 2024-06-17 16:18
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1700

**Closed by YYDan** 2024-06-17 16:18 UTC
Labels: ide-bug

**Comment by YYDan** [comment] 2024-06-17 16:22
Also, if you were not using 0-byte empty files inside the .zip it's very easy to work out where they got extracted:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/876e4d13-4814-4f46-a40c-b53763394015)

**Comment by YYDan** [comment] 2024-06-17 16:55
Whoops! Realised I had made a typo in the project at that time and so I was showing the wrong result for the async test - it's actually more broken than I had thought, as the "status" is incorrect also, not just the "id".

https://github.com/YoYoGames/GameMaker-Bugs/issues/6311 anyway.

**Comment by tinkerer-red** [comment] 2024-06-17 17:41
Amazing! As mentioned in the open issue, a update to the docs would be greatly appreciated to inform people not to expect 0byte files.
