### ISSUE TITLE
Sound Editor: Audio loop points support in the IDE

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4042] opened 2023-06-06 14:55 UTC
Ticket #198965
Feature Type: feat_change_ide
Description: Each sound could have an option that makes them loop in-game with start and end loop points. The sound editor could have two sliders, you'd be able to drag them around or set a specific value for them in seconds. In-game, the sound would loop back to the set starting point the moment it reaches the ending point.
Benefit: It would be a smoother way to loop songs after their intro plays without having to rely on asynchronous events or checking what position a sound is on every step.
Link:

**Comment by YYDan** [comment] 2024-07-23 08:44
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2811

**Closed by YYDan** 2024-07-23 08:44 UTC
Labels: feature request, import
