### ISSUE TITLE
ImGui debug windows - allow to scroll using gamepad / mouse wheel

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2855] opened 2023-10-31 10:25 UTC
### Is your feature request related to a problem?

When testing game on Steam Deck (Asus Rog, Lenovo Legion Go, probably consoles exports too), after calling `show_debug_overlay()` we're able to open log, which opens console window.

![obraz](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/524094/21e06017-c617-4f85-990b-d97c09c822b0)

However, it's really hard to scroll such log on devices without mouse as scrollbar is rather small because of high DPI. While it would probably not help much on mobiles (until developer would connect gamepad), I would really appreciate if console log window could be scrolled with analog stick of gamepad console (as mentioned devices have them built-in).

Preferably it should be right analog stick (as left usually is responsible for gui movement and player movement, while right is less used), but any solution is welcome.

Allowing to scroll using mouse wheel would be also very welcome.

### Describe the solution you'd like

ImGui console scrolling on gamepad analog stick, and mouse wheel.

**Comment by YYDan** [comment] 2024-07-23 07:52
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6823

"Duplicate", but taking your own advice on the other issue ;)

**Closed by YYDan** 2024-07-23 07:52 UTC
Labels: feature request
