### ISSUE TITLE
Code editor 2: Jumping to declaration will stop working if project is reloaded without restarting gamemaker

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5366] opened 2024-04-06 17:49 UTC
### Description
Jumping to declarations will stop working after the project is reloaded:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/947f5003-3e0b-4f79-b2f9-5a68b2524204

### Steps To Reproduce
Open the project, then open it again without closing gamemaker. Try to jump to a declaration.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[01f19f56-7f84-468e-a685-ff5d257c254d](https://api.gamemaker.io/api/github/downloads/01f19f56-7f84-468e-a685-ff5d257c254d)

**Comment by zreedy** [comment] 2024-06-19 22:01
Unable to reproduce, I suspect this ticket is now fixed as a knock on to the fix for internal issue 9665.

**Closed** 2024-06-19 22:01 UTC
Labels: ide-bug
