### ISSUE TITLE
Room editor, inspector F2 doesn't work

### ISSUE THREAD

**Issue by batblaster** [YoYoGames/GameMaker-Bugs#4491] opened 2024-01-25 01:36 UTC
### Description
Hi,
as the title said if you need to rename a layer in the room editor under the inspector also if the info on right mouse suggest to use F2 button it doesn't work, if you press F2 un a layer, whatever it is, the rename is for the inspector and not for the layer.

[05084e47-054f-41f6-a701-47bbbfcd0f3b](https://api.gamemaker.io/api/github/downloads/05084e47-054f-41f6-a701-47bbbfcd0f3b)

**Comment by YYDan** [comment] 2024-01-25 13:48
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2665

**Closed by YYDan** 2024-01-25 13:48 UTC
Labels: ide-bug
