### ISSUE TITLE
Room Editor: Duplicating or copy-pasting instances and then undoing leaves a phantom selection of the instances that no longer exist

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8086] opened 2024-10-22 21:24 UTC
### Description
Copy pasting instances and then undoing it does not clear the selection, and you can manipulate this selection of no longer existing instances. Making changes to this selection goes onto the undo stack, which can cause some confusing results if this was done on accident.

https://github.com/user-attachments/assets/bdd84b83-965f-4c98-ace5-84b4633d4dd0

### Steps To Reproduce
1. Place some objects in a room.
2. Duplicate or copy-paste them.
3. Undo.
4. The selection of the now deleted instances will still be visible and possible to edit.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[5c114153-e494-466f-9092-977b2719b9fe](https://api.gamemaker.io/api/github/downloads/5c114153-e494-466f-9092-977b2719b9fe)

**Comment by YYDan** [comment] 2024-10-23 08:18
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/7443

**Closed by YYDan** 2024-10-23 08:18 UTC
Labels: ide-bug, project
