### ISSUE TITLE
Right-Click reverts to previous (non-pasted) brush on select tool/paste in Image Editor.

### ISSUE THREAD

**Issue by Yaazarai** [YoYoGames/GameMaker-Bugs#4625] opened 2024-02-05 07:52 UTC
### Is your feature request related to a problem?

When you copy-paste it overrides your current brush and makes unlimited brushes forcing you to manually delete subsequent pastes. Very irritating when you want to work with a specific brush/setting for it to be overridden by pasting something over from another sprite or layer.

### Describe the solution you'd like

Right-Click reverts you to the previous non-pasted brush tool. Having both left/right mouse buttons move a selection is unnecessary, this should be a useful replacement (maybe even toggleable in the settings).

**Comment by yyalansavage** [comment] 2024-02-19 09:56
Hi, I understand why this problem is annoying, I'm not sure about the right-click-revert, right click on the canvas/drawing area does already perform a different function for some tools (eg paintbrush tool draws with alternate colour), so seems like this may conflict; but perhaps I have misunderstood what you are meaning here.
There is already a "B" key "Toggle Selection Brush" shortcut to toggle between last standard and selection brush, although atm it does not preserve the size setting of the standard brush. I've made a couple of changes locally to i)not create a duplicate of the existing copied brush when you paste, and ii) restore the brush size setting when using "B" to toggle selection/standard brush. Does this sound like it would solve the problem for you?

**Comment by Yaazarai** [comment] 2024-02-19 15:22
Yes that solves the problem. Thanks!

**Comment by yyalansavage** [comment] 2024-02-19 16:29
Ok, great! Changes implemented as described; unfortunately, this is too late to make it into the next release, so won't be available until the next one.

**Closed by yyalansavage** 2024-02-19 16:29 UTC
Labels: ide-bug

**Comment by caitlinrmcintyre** [comment] 2024-03-20 15:27
Verified fix in IDE v2024.400.0.521  Runtime v2024.400.0.540, thanks.
