### ISSUE TITLE
Code Editor 2: [Mac IDE] The Diagnostics tab will always appear empty/won't display any messages

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5418] opened 2024-04-09 11:18 UTC
### Description

As described - no matter if feather is enabled or not, the diagnostics tab won't display any messages.

[ui.log](https://github.com/YoYoGames/YoYoStudio/files/14917855/ui.log)

### Steps To Reproduce

1. Start GameMaker on a Mac
2. Open a project with some code and feather messages making sure you enable CE2
3. Observe the empty diagnostics tab
4. Disable CE2
5. Observe that the messages will reappear on the feather's messages tab

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

IDE v2024.400.0.534  Runtime v2024.400.0.553

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by thennothinghappened** [comment] 2024-04-10 23:49
This on my end at least seems to be a manifestation of feather just having strange issues on macos under CE2. I've seen this also in the form of tooltips being slightly messed up:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/f66855a2-c810-4b6c-8156-03f81dd89a6a)
Note the missing function signature, and argument names.

Plus a lot of feather's intellisense is just straight up missing - it doesn't warn about invalid syntax or argument issues, etc, but I've also seen that in CE2 on windows to an extent.

I'm running Ventura

**Comment by zreedy** [comment] 2024-07-05 21:25
This should have been fixed by other now closed tickets related to LSP not functioning on Mac OS X and Linux.

**Comment by Emc1923** [comment] 2024-08-26 09:59
Issue has reappeared as of  IDE v2024.800.0.614  Runtime v2024.800.0.637, reopening for now.

**Comment by zreedy** [comment] 2024-08-29 19:31
Fixed the regression. Additionally fixed an issue where typing inside of a function declared inside of an event would result in the Diagnostics previously displayed to disappear.

**Closed** 2024-09-02 14:23 UTC
Labels: ide-bug

**Comment by Emc1923** [comment] 2024-09-20 08:47
Verified in  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
