### ISSUE TITLE
The IDE no longer loads the config you were using in a previous session.

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#4780] opened 2024-02-21 18:19 UTC
### Description

When you open the Game Maker IDE, it will now always be set to the 'Default' config, even if you were working in a different config in a prior session.

No sample project attached, since the replication steps don't require any special code or project. Any project will demonstrate this bug.

### Expected Change

The IDE should once again restore whichever config you were using in the previous session.

### Steps To Reproduce

1. Start GameMaker
2. Set your config to something other than 'Default'.
3. Close GameMaker.
4. Reopen GameMaker.
5. Observe that your config is now back to 'Default'.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-02-22 10:02
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1736

**Closed by YYDan** 2024-02-22 10:02 UTC
Labels: ide-bug
