### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by ChilliadEmerald** [YoYoGames/GameMaker-Bugs#4737] opened 2024-02-15 14:37 UTC
### Is your feature request related to a problem?

I'm too much of an amateur as of now to have run into a problem with this, but I've seen this feature in multiple other languages and it looks extremely useful for high level programming.

### Describe the solution you'd like

Add a way to do multithreading in base GML code.

### Describe alternatives you've considered

I've seen a C++ (or maybe it was C#) plugin for GMS2 that allowed the user to code in C++ and have that code work for GMS2. Because C++ has multithreading built in, that option becomes available using this plugin.

**Comment by attic-stuff** [comment] 2024-02-15 14:49
duplicate of #4063 and #3024 and #2758

**Comment by stuckie** [comment] 2024-02-16 09:37
Closing as above

**Closed by stuckie** 2024-02-16 09:37 UTC
Labels: feature request
