### ISSUE TITLE
Code Editor 2: Autocomplete and syntax-highlighting failures with large projects

### ISSUE THREAD

**Issue by nuevocharrua** [YoYoGames/GameMaker-Bugs#5347] opened 2024-04-05 15:28 UTC
### Description

I have identified a critical issue specifically with Code Editor 2 on macOS, where both the autocomplete functionality and syntax highlighting cease to operate after the editor has been in use for some time. This problem is exacerbated in the context of large projects, where from the outset, neither autocomplete nor syntax highlighting is functional.

[test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14887058/test.zip)
<img width="998" alt="Captura de pantalla 2024-04-05 a la(s) 12 17 27 p  m" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/24524075/d2be171b-bcbd-41ae-a283-178ffef2a419">
<img width="693" alt="Captura de pantalla 2024-04-05 a la(s) 12 27 24 p  m" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/24524075/d0f1207a-1215-4b40-9af2-b9a024111a02">

Due to the extensive size of the projects in question, I am unable to attach them to this report. I hope this description is sufficient to isolate and address the issue.

### Steps To Reproduce

1. Start GameMaker Beta.
2. Open a large-scale project within GameMaker. (Note: The issue becomes immediately apparent with projects of significant size, indicating that the project's dimensions are a crucial factor.)
3. Switch to using Code Editor 2 as the active code editor in the settings. (This step is essential to replicate the issue, as it specifically involves the new code editor.)
4. Observe the issue: Autocomplete functionality and syntax highlighting in Code Editor 2 cease to work after some time for smaller projects, and are immediately non-functional for larger projects upon opening.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by KormexGit** [comment] 2024-04-05 17:32
It's the same on windows, I've also experienced the coloring not filling out correctly on my large project, but have not been able to come up with consistent reproduction steps

**Comment by nuevocharrua** [comment] 2024-04-05 20:57
> It's the same on windows, I've also experienced the coloring not filling out correctly on my large project, but have not been able to come up with consistent reproduction steps

I appreciate your input and can confirm similar behavior across different project sizes. In smaller projects, the issue seems to occur somewhat randomly, making it hard to pin down a consistent reproduction pattern. However, as project size increases to a medium or large scale, the frequency of these issues, including syntax highlighting and autocomplete failures, also increases noticeably.

In very large projects, ones with hundreds of objects, thousands of sprites and sounds, and hundreds of rooms, the functionality rarely works as intended from the outset. It seems like the scale of the project significantly impacts the editor's performance, with larger projects consistently presenting more severe problems.

**Comment by stuckie** [comment] 2024-04-08 09:13
You can use something like Google Drive to upload it to, and then we can request access for it.
Or, you can also use the IDE bug reporter to include the project, but you will need to create a new ticket for this.

**Comment by stuckie** [comment] 2024-04-08 09:38
Actually, just noticed the test.zip link directly above the first picture, which I assume reproduces this.

**Comment by MahradH** [comment] 2024-04-11 08:29
same problem here on Ubuntu 22.0.4 LTS. I agree that it doesn't work for large projects. but about small projects, It seems quite random. it works sometimes but not all the time. I am attaching my small project in Google drive.
[link to small project](https://drive.google.com/file/d/1HZVuSvldI0_H8H_vABsjcHw5GlPtOEqy/view?usp=sharing)

**Comment by zreedy** [comment] 2024-04-11 13:48
For this ticket, it would be useful to have the verbose log, if available.
Go to your GM installation folder and find `/TextEditor2/Servers/GML.lspConfig` and replace the contents with:
```json
{
	"fileTypes": [
		"gml"
	],
	"type": "Process",
	"path": "GameMakerLanguageServer",
	"args": "",
	"logLevel": "Trace"
}
```

You should now see a lot of debug logging in the Output window of the IDE. Please attach that with your report. Additionally, the ui.log would be extremely important here.

**Comment by MahradH** [comment] 2024-04-11 14:39
There is no log in output window when ce2 is not working. this means when ce2 is working I can see logs, but when its not working there is no log. but I will send ui.log.

**Comment by MahradH** [comment] 2024-04-11 15:01
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/126811340/f9536a1d-0398-4528-b147-ef6ba7775910)
[outputLogs.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/14947883/outputLogs.txt)

I tried opening a small project to get log working and after that I opened my main project. so now I will send logs too.

**Comment by Lukanibal** [comment] 2024-05-25 04:47
![noFunctionHighlighting](https://github.com/YoYoGames/GameMaker-Bugs/assets/6170632/cf00022e-44ff-476e-b73e-18ef369fff26)
I just wanted to say I am having the same issue still in the Ubuntu IDE in the latest beta (2024.600.0.560)
The game runs fine, all the code works, but the no highlighting and no intellisense is a real hassle.

**Comment by zreedy** [comment] 2024-06-06 18:43
I suspect there's a partial fix for this ticket as it relates to CE2 behavior on Mac OS X and Linux with this ticket https://github.com/YoYoGames/GameMaker-Bugs/issues/5948

Further work is being done to allow for partial Language Services to be served prior to a project being completely loaded which unavoidably might take a bit of time with larger projects.

**Comment by zreedy** [comment] 2024-06-13 15:06
This ticket should now be completely fixed.
The primary issue seems to be that LSP designates some commands are parallizable and others are serializable (though the specific commands seem to be up to the implementer's discretion). For OmniSharp's part, if a long running serial command is in the queue all parallel and serial commands are halted until the blocking request is complete. It's likely that one of these commands was previously blocking indefinitely (timeout is 5 minutes, but that's a long time for 1 command and there might be others in queue which will also time out). 

While this appears to be the primary cause there were many performance issues on both the Client and Server that would have contributed.
As such, the following fixes and changes have been made relating to this issue:
- Server: Split the concept of "YYP Project" and "Feather Project" so that certain drivers can be active while Feather parses the project
- Server: Added ability to serve Hover Info, Semantic Tokens, and Code Completion on a loaded YYP Project, without a Feather Project loaded improving apparent Client-side performance
- Server: All requests asyncly resolve document/resource lookups now, and block against YYP load state which should mean that no request will ever block if a Feather Project Wide Reparse is initiated (config change, asset renamed, quick fix applied, room instance added, etc.)
- Client/Server: Fixed a severe performance issue with document/resource resolvent: 186,000ms -> 164ms for ??? requests
- Client/Server: Improvements to YYP deserialization ~8s -> 5s for large project
- Client: Dispatches "Add Workspace" request to Server when "Project Load Begun" rather than _after_ the project has finished loading on the Client. This means that both the Client and Server can load the project from disk at the same time. This reduces the amount of time it takes for full Language Services to be available (~8s faster for large project)
- Client: Diagnostics are collected, sorted and displayed using an improved heuristic to avoid unnecessary sorting which blocks the UI thread (8,645ms -> 90ms, 9007req -> 91req for large project)

**Comment by zreedy** [comment] 2024-06-13 21:26
Further changes to logging on the GML Server have also been made now. When `GML.lspConfig`'s `LogLevel` value is set to `Trace` all LSP logging will be logged to Console stderr, and to the `ui.log` for the appropriate environment. The `ui.log` is shared across all IDE sessions and GML Server sessions. The invoking Client's PID will be echoed by the Server in its announcement log lines regardless of `LogLevel`.

```
[17:24:32:020(2ca0)] **************************************  06/13/2024  **************************************
[17:24:32:044(2ca0)] Logger.Initialise
[17:24:32:044(2ca0)] [GMLServer] GameMakerLanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[17:24:32:045(2ca0)] [GMLServer] Command line arguments:
GameMakerLanguageServer.dll
--log-level=None
[17:24:32:045(2ca0)] [GMLServer] ProcessId:20832
[17:24:32:045(2ca0)] [GMLServer] Client ProcessId:19096
[17:24:33:691(7412)] Language Server - Initialized - GameMakerLanguageServer
```

**Comment by zreedy** [comment] 2024-06-14 20:46
Final change related to this ticket: Once a the Language Server has reported that a long running Work Progress is complete (such as when performing a Feather Project-wide Parse) the Client will now refresh all open Documents. So any previously discarded requests are ensured to be served.

**Closed** 2024-06-18 14:29 UTC
Labels: ide-bug

**Comment by Emc1923** [comment] 2024-07-16 09:55
Verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
