### ISSUE TITLE
No way to set audio loop points in IDE

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6826] opened 2024-07-22 21:02 UTC
### Description

Built-in audio loops were added to GM over a year ago, but there's still no way to set them aside from through code (or loading them from a file, through code).

![image](https://github.com/user-attachments/assets/0075b8d5-d5d9-4147-bd60-3ce817316609)

For whatever strange reason, Unreal and Unity don't seem to have a convenient way to do this either, which is equally if not more baffling because non-coder people ask for this all the time.

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by toby-yoyo** [comment] 2024-07-22 21:06
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2811 and https://github.com/YoYoGames/GameMaker-Bugs/issues/4042.

**Comment by stuckie** [comment] 2024-07-23 08:40
Closing as above

**Closed by stuckie** 2024-07-23 08:40 UTC
Labels: ide-bug
