### ISSUE TITLE
In-Game: [iOS] device_mouse_x_to_gui() values are offset when running on an iPhone 13 Mini specifically · Issue #2389 · YoYoGames/GameMaker-Bugs (github.com)  There is also a problem with device_mouse_y_to_gui() when in portrait mode  Occurs on iPhone 12,13 mini   This is a fatal bug  When will it be fixed?

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GameMaker-Bugs#2598] opened 2023-12-26 20:22 UTC
### Description

[In-Game: [iOS] device_mouse_x_to_gui() values are offset when running on an iPhone 13 Mini specifically · Issue #2389 · YoYoGames/GameMaker-Bugs (github.com)](https://github.com/YoYoGames/GameMaker-Bugs/issues/2389)

There is also a problem with device_mouse_y_to_gui() when in portrait mode

Occurs on iPhone 12,13 mini

This is a fatal bug

When will it be fixed?

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment] 2023-12-27 10:29
Duplicate of [https://github.com/YoYoGames/GameMaker-Bugs/issues/2389](https://github.com/YoYoGames/GameMaker-Bugs/issues/2389)

Please stop reporting more reports for this - you know we have the original report already, so us closing all your extra reports will not help us fix the problem more quickly.

**Closed by YYDan** 2023-12-27 10:29 UTC
Labels: runner-bug
