### ISSUE TITLE
Can't build on Linux when Steamworks script copy dependencies

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4962] opened 2024-03-09 22:57 UTC
### Description
Building from Windows IDE on Linux fails, tested on two different machines.
Since last launching successfuly in IDE, I updated GM from 2023.11 to 2024.2 and I updated the Steamworks Extension
```
"Copying Linux (64 bit) dependencies"


    Directory: C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC


Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----        09/03/2024     16:54                _temp                                                                




C://GMS//extensions//Steamworks\post_build_step.bat DONE (0)
mkdir -p /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\Ref.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/Ref.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYGML.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYGML.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYRValue.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYRValue.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYSlot.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYSlot.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYStd.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYStd.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\libyoyo_yyc-x64.a /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/libyoyo_yyc-x64.a
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\makefile /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/makefile
pscp C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163\linux\execute.sh /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/execute.sh
chmod +x /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/execute.sh
mkdir -p /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/Game/
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\Game\ /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/Game/
rsync -c -r /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux /home/tom/GameMakerStudio2/yyc
unshare -mUprf sh -c 'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin && cd /tmp/ && make -C /tmp/ -j `nproc --all`"' -- /home/tom/GameMakerStudio2/yyc/Chronique_des_Silencieux /opt/steam-runtime
make: Entering directory '/tmp'
mkdir -p out
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasAppSurf.gml.o Game/gml_GlobalScript___CanvasAppSurf.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasCleanupQueue.gml.o Game/gml_GlobalScript___CanvasCleanupQueue.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasError.gml.o Game/gml_GlobalScript___CanvasError.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasGC.gml.o Game/gml_GlobalScript___CanvasGC.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasSurfFormat.gml.o Game/gml_GlobalScript___CanvasSurfFormat.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasSystem.gml.o Game/gml_GlobalScript___CanvasSystem.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasTrace.gml.o Game/gml_GlobalScript___CanvasTrace.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CleanConfig.gml.o Game/gml_GlobalScript___CleanConfig.gml.cpp -DYYLLVM
make: Leaving directory '/tmp'
System.Exception: command 'unshare -mUprf sh -c 'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin && cd /tmp/ && make -C /tmp/ -j `nproc --all`"' -- /home/tom/GameMakerStudio2/yyc/Chronique_des_Silencieux /opt/steam-runtime' failed with exit status 2
   at Igor.LinuxBuilder.plink_async(String command, Boolean fail_on_error)
   at Igor.LinuxBuilder.LinuxSendAndBuildMakefile(String _dir)
   at Igor.LinuxBuilder.Package()
```

### Steps To Reproduce
1. Launch a build from Windows IDE to an ubuntu machine on local network

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[2f94e80c-9600-44df-a33b-1e39607e1770](https://api.gamemaker.io/api/github/downloads/2f94e80c-9600-44df-a33b-1e39607e1770)

**Comment by patchuby** [comment] 2024-03-10 18:06
Did a few more tests on my end
- Reverting to 2023.11 solves the issue
- Still in 2023.11, building in YYC from the CLI doesn't work : Igor says remote client took too long to respond but it's likely confused because on VM I don't get this issue (and I got it on 4 different times doing with YYC)

**Comment by DiasFranciscoA** [comment] 2024-03-11 11:22
@patchuby, could you please specify the version of the extension you're currently using? We haven't encountered any issues with the extension while targeting an Ubuntu machine and are unable to replicate the problem you described.

Additionally, you mentioned an included project file, but we didn't find any attachments with your issue. Could you please upload the project file in question?

**Comment by patchuby** [comment] 2024-03-11 15:17
@DiasFranciscoA I redid the whole setup you linked to on my laptop that was already setup for it and was previously successful in compiling, just to be sure. 
I also tested on a raspberry pi with a fresh ubuntu install (though I understand raspberry pi is not fully supported), I managed to go further into the script the first time I ran it, and then the second time it stopped at roughly the same place, like running the script itself changed something.

There must be an issue with the 2024.2 IDE, I submitted the project once with #4691 and thought I had already included it, now I'm 100% sure I included it with this one, checking the box in the bug report. 

I can't resubmit on 2024.2 because I have reverted to 2023.11 to resume work, after some trouble with git lfs who didn't like the project format changes. I can send the 2023.11 version of the project via a link in a DM on Discord or something else, until the bug reporting is fixed.

**Comment by patchuby** [comment] 2024-03-11 17:22
@DiasFranciscoA I've submitted succesfully my project using the 2023.11 IDE in #4979, you can use that after converting it to 2024.2

**Comment by DiasFranciscoA** [comment] 2024-03-12 09:30
Morning @patchuby, you mention that the problem is "Copying Linux (64 bit) dependencies" any reason? are you able to compile when not using Steamworks? 

Cus the steamworks dependencies seem to be working just fine: 
```
C://GMS//extensions//Steamworks\post_build_step.bat DONE (0)
```

This means the `post_build_step.bat` of the extension is running successfully (returning code 0) so the files are being copied correctly and there are no errors. I noticed there are some configurations there and I tried 2 or 3 of them, please let us know the entire steps you follow to reproduce this. We are currently unable to do so.

**Comment by DiasFranciscoA** [comment] 2024-03-12 15:05
Hello @patchuby, we require more details to understand the exact nature of the failure.

Are you compiling on a Windows machine with a target platform of Linux? Could you specify whether the problem arises while using the Command Line Interface (CLI) or within the Integrated Development Environment (IDE)? Additionally, which runtime environment are you utilizing — VM or YYC? We're also curious to know if the issue persists when Steamworks is disabled, as none of the error messages you mentioned appear in the logs we reviewed.

**Comment by patchuby** [comment] 2024-03-12 15:36
@DiasFranciscoA Can we set up a call ? There are several overlapping issues (https://github.com/YoYoGames/GMEXT-Steamworks/issues/61, https://github.com/YoYoGames/GameMaker-Bugs/issues/4917), I've already submitted all the info you asked several times (including this issue), it might be better if I summarize it in a call so we can go over config problems on my end and rule out "me" problems vs "gm" problems much more quickly.
I'm available on discord (patchuby_) or another platform.

**Comment by DiasFranciscoA** [comment] 2024-03-14 23:38
After further investigation and discussion with the user on Discord, we've determined the root causes of the build issue reported. The primary factors were:

1. Unsupported Build Platform: The user attempted the build process on a Raspberry Pi, which, as per our current platform support documentation, is not a supported platform for building and compiling this project.
2. Lack of Clean Build Process: The user transitioned from the November 2023 (Nov23) build to the February 2024 (Feb24) version without performing a clean build. Due to significant project format changes between these versions, residual cached data from the previous build became invalid, leading to the reported issue.

## **Solution**: 

The user was advised to perform a clean build of the project. Subsequently, the build was successfully executed from a Windows IDE targeting Linux (Ubuntu), confirming that the issue was resolved by removing outdated cached data and using a supported build environment.

## **Recommendation**: 

We recommend all users to ensure they are working on supported platforms and to perform clean builds when switching between project versions especially when significant changes are implemented (ie.: Nov23 -> Feb24). This practice helps avoid similar issues stemming from incompatible or outdated cached data.

## **Action**: 

This ticket will be marked as resolved. We appreciate the community's collaboration in diagnosing and addressing build issues, and we encourage users to consult the documentation for supported platforms and build guidelines.

**Closed by DiasFranciscoA** 2024-03-14 23:38 UTC
Labels: build-bug, project

**Comment by Emc1923** [comment] 2024-03-28 17:03
Closing as per comments, thanks!
