### ISSUE TITLE
Object Editor/Code Editor 2/Inspector: Parent's new events don't automatically appear for a Child if it is already opened

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5608] opened 2024-04-22 22:40 UTC
### Description
If you add a new event to a parent object, the event won't appear on the child object until the project is reloaded or the child object is closed and reopened.

This applies to the workspace:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/bd4c0500-6228-4978-afe1-dfa885a748cc

And the new code editor:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9386718b-c826-45a1-b1fb-f14513c636df

And the inspector:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/c767bb2f-9b78-49e5-a0a4-22831516d01c

### Steps To Reproduce
Create two objects. Make one the child of the other. While both have their windows open, add a new event to the parent. This new event will not appear in the child object until the child object's window is closed and reopened, or the project is reloaded.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[74828e1d-0a4b-416d-ad72-2e9e4ea2da86](https://api.gamemaker.io/api/github/downloads/74828e1d-0a4b-416d-ad72-2e9e4ea2da86)

**Comment by YYDan** [comment] 2024-04-23 08:34
Technically a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/4841 but you have the fancy videos and the mention about the Inspector also, so we'll keep yours and get rid of the original ;)

**Comment by zreedy** [comment] 2024-09-04 21:41
Fixed

**Closed** 2024-09-17 09:49 UTC
Labels: ide-bug, project

**Comment by caitlinrmcintyre** [comment] 2024-09-19 13:45
Verified fix in  IDE v2024.1100.0.623  Runtime v2024.1100.0.649, thanks.
