### ISSUE TITLE
Add the ability to put streamed-from-disk audio in a subfolder

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6735] opened 2024-07-18 01:36 UTC
### Is your feature request related to a problem?

When you set an audio file's type to "compressed - streamed," it gets encoded as an ogg and dropped in your game's root folder.

![image](https://github.com/user-attachments/assets/c163466b-661b-49b2-a60c-866531b06d6c)

This seems to bother some people more than others.

### Describe the solution you'd like

There are a few things that could be done about this.

- Allow Compressed - Streamed audio files to be assigned to an audio group, and give audio groups a folder name where streamed files are stored so that users could load their music from `/bgm` or something (this would probably be my preferred solution)
- Put a "streamed audio folder" setting somewhere in Game Options that does the above but for all streamed files

### Describe alternatives you've considered

- `audio_create_stream` lets you load audio from a file and basically treat it like audio loaded by the IDE, but why should people have to use code to achieve something like this?
- Edit the data wad by hand to point the runner to audio files in another folder - yes, this does work, and I might or might not have done this before

https://github.com/user-attachments/assets/a579ae6b-0ada-4eb1-a549-edab6481ba5a

**Comment by toby-yoyo** [comment] 2024-07-18 08:54
Relates to https://github.com/YoYoGames/GameMaker-Bugs/issues/2732 and https://github.com/YoYoGames/GameMaker-Bugs/issues/3585.

**Comment by YYDan** [comment] 2024-08-08 08:23
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2732

**Closed by YYDan** 2024-08-08 08:23 UTC
Labels: feature request
