### ISSUE TITLE
Event List does not update properly when changing the parent of the parent

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#7163] opened 2024-08-08 08:04 UTC
### Description
Just a small visual bug I noticed when messing with a chain of inheritance.

I had an object obj_destructible_wall which had the parent obj_trigger. obj_trigger was without a parent and had no events to it.

I added obj_entity as a parent to obj_trigger.

The event list of obj_destrucbile_wall did not reflect the change until I closed and reopened it.

### Steps To Reproduce
1. Open last child of a chain of inheritance, more than one layers deep
2. Open the parent object that was previously without a parent
3. Add a parent to it
4. The Event list of the last child does not update visually.
5. If you close and reopen the object, the Event list is rendered correctly

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[b8cb8fca-f38c-4307-bc93-5a1483c758a0](https://api.gamemaker.io/api/github/downloads/b8cb8fca-f38c-4307-bc93-5a1483c758a0)

**Comment by YYDan** [comment] 2024-08-08 08:28
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5608

**Closed by YYDan** 2024-08-08 08:28 UTC
Labels: ide-bug
