### ISSUE TITLE
Preferences: Disable Feather rule GM2017 (Inconsistent Naming) by default

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#7809] opened 2024-09-27 18:47 UTC
### Is your feature request related to a problem?

I understand the motivation for using Feather GM2017 to help enforce naming conventions, but the default convention is far from universally accepted and is not flexible enough to suit many production needs. Increasingly I see the flood of GM2017 Feather notices as unhelpful at all levels, needlessly frightening novices on one end and annoying professionals on the other end. Virtually all users with production-level Feather experience has it turned off, and others even turn Feather off entirely just because of GM2017 alerts. Not even the tutorials on [the official tutorials page](https://gamemaker.io/en/tutorials) are fully compliant with it. That should be indicative of how unloved it is.

### Describe the solution you'd like

Going forward, I would like to make GM2017 disabled by default.

**Comment by stuckie** [comment] 2024-09-30 09:39
Duplicate of #3084

**Closed by stuckie** 2024-09-30 09:39 UTC
Labels: feature request
