### ISSUE TITLE
Inspector - Trying to drag a asset to a "asset list" in a instance inspector panel will not work with a new clicked asset

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5846] opened 2024-05-14 02:29 UTC
### Description
When you try to drag and drop a asset into a asset list, it will work as expected ONLY if that asset is already clicked if not it will change the inspector panel.

### Steps To Reproduce
1) Watch Video
2) Make a instance with a asset list instance variable
3) Try to drag and drop an asset into it.

try it on the rCH1GhostCity2 room with the inst_7C71529B instance in the room

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[5e01899d-f881-4c62-9bcd-2b1e407e0ae4](https://api.gamemaker.io/api/github/downloads/5e01899d-f881-4c62-9bcd-2b1e407e0ae4)

**Comment by YYDan** [comment] 2024-05-14 08:49
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5490

**Closed by YYDan** 2024-05-14 08:49 UTC
Labels: ide-bug, project
