### ISSUE TITLE
Duplicate objects created in asset browser when saving while using GMEdit.

### ISSUE THREAD

**Issue by nmranney** [YoYoGames/GameMaker-Bugs#4930] opened 2024-03-07 04:58 UTC
### Description

Howdy, I'm not sure if this is a GM bug or a GMEdit bug, but here are the details.

After the newest update, any time I save an object in GMEdit, a duplicate version of that object is added to the asset browser in GM. This appears to be a visual bug only, as the game continues to build and run fine. Duplicate assets are NOT created in GMEdit. This only seems to happen with objects. Saving scripts doesn't have an issue. Closing GM and opening it back up will clear out the duplicates. 

If I create a new project in GM on the newest version, and I only work within GM, I have no issues. If I open that project in GMEdit, and try to make changes, the changes aren't immediately reflected on the GM side like they usually are. I have to close GM and open it back up. However, because I made changes to the project through GMEdit, it triggers the Project Tool and I get the message in the screenshot. After that everything starts duplicating.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/10203698/7cb9258e-3b4d-4158-84e8-4c26b0d9237e)
[CYOP.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14518942/CYOP.zip)

### Expected Change

Duplicates aren't created when saving in GMEdit. 

### Steps To Reproduce

1. Start GameMaker
2. Create an object
3. Start GMEdit
4. Open an object in GMEdit, edit the code, and save it. You can do anything including add white space or a comment. 
5. See that the changes aren't immediately reflected on the GM side. 
6. Close GM, re-open the project, and get the Project Tool message. 
7. Now make changes and save in GMEdit.
8. See the duplicate asset in GM

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2024-03-13 16:43
Closing as duplicate of #4906 as it's the same root cause

**Closed by stuckie** 2024-03-13 16:43 UTC
Labels: ide-bug
