### ISSUE TITLE
Extend the Broadcast Message System to allow sending and receiving messages between instances

### ISSUE THREAD

**Issue by Funcestor** [YoYoGames/GameMaker-Bugs#7486] opened 2024-08-31 11:50 UTC
### Is your feature request related to a problem?

Related to: #6153 and #3975 

We already have the Broadcast Message Event, but it is only reserved for Sprites and Sequences.
Are there any plans to extend the Broadcast Message System to send and receive messages between objects/instances via a function?
Or outright implementing a different built-in system unrelated to Broadcast Messages?

### Describe the solution you'd like

It think at the current state, the best solution would be to extend the Broadcast Message System:

- Add a new string for the "event_type" key in the "event_data" ds_map (seomthing like "instance event")
- Add a gml function to send broadcast messages (maybe also with some optional data?). 
Something like: `broadcast_message_send(message_string, optional_data)`

**Example:**

**obj_player** | Collision Event with obj_pressure_plate:

`
broadcast_message_send("open door", other.switch_id);
`

**obj_door** | Broadcast Message Event:

```
if event_data[? "event_type"] == "instance event"
{
    if event_data[? "message"] == "open door"
    {
        if event_data[? "data"] == switch_id
        {
            open_door();
        }
    }
}
```

### Describe alternatives you've considered

As an Alternative, I think the easiest Solution to implement this would be to add a function similar to event_perform_async, but for the Broadcast Message Event.

After dabbling though the manual, I encountered the function [event_perform_async](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Objects/Object_Events/event_perform_async.htm) which performs an async event, **while also letting you add custom ds_map entries to the async_load map to be read in the Async Event**.

I tested this a bit, and it _could_ work as a makeshift event messaging system. 

It would be great if this could also be implemented with the event_data map that is used for Broadcast Messages by adding a function. Something like `event_perform_broadcast(ds_map)`

Example for a custom `broadcast_message_send` function using the requested function `event_perform_broadcast(ds_map)`:

```
function broadcast_message_send(message, data)
{
    var map = ds_map_create();

    map[? "event_type"] = "instance event";
    map[? "message"] = message;
    map[? "element_id"] = id;
    map[? "data"] = data;

    event_perform_broadcast(map); 
}
```

**Comment by YYDan** [comment] 2024-09-02 08:28
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6153

**Comment by YYDan** [comment] 2024-09-02 08:29
I have now tidied up the other really old report also, so that we keep all conversation for this feature request in the one issue. Thanks.

**Closed by YYDan** 2024-09-02 08:28 UTC
Labels: feature request
