### ISSUE TITLE
Pressing F2 renames the Inspector tab instead of the selected layer

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#7029] opened 2024-07-31 13:58 UTC
### Description
When selecting a layer and pressing F2, the cursor jumps to the Inspector panel name and gets it ready to be renamed instead of the selected layer

### Steps To Reproduce
1. Select a layer
2. Press F2
3. The panel name gets readied to be renamed, skipping over the layer

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[13b584d0-b2d3-4ec5-8891-6b077f1117a0](https://api.gamemaker.io/api/github/downloads/13b584d0-b2d3-4ec5-8891-6b077f1117a0)

**Comment by YYDan** [comment] 2024-07-31 14:01
Regression of https://github.com/YoYoGames/GameMaker-Bugs/issues/2665 ?

**Comment by YYDan** [comment] 2024-07-31 14:03
No... The Room Editor still works for me, as does the Image Editor.

@nullbunny Which editor are you renaming layers in? (That bit's quite important in the steps ;) )

**Comment by nullbunny** [comment] 2024-07-31 14:16
It was happening in the Room Editor. I had a tilemap open and pressed over to the layer list, pressed F2. I just restarted the editor and now it is behaving as expected. It must have been a fluke or I am too tired and shouldn't be working. Sorry! ;)

**Comment by stuckie** [comment] 2024-08-01 08:38
Closing as above.

If it happens again, let us know with a reproduction if possible.

**Closed by stuckie** 2024-08-01 08:38 UTC
Labels: ide-bug
