### ISSUE TITLE
Startup failure 

### ISSUE THREAD

**Issue by Cadaver2465** [YoYoGames/GameMaker-Bugs#5705] opened 2024-05-01 15:25 UTC
### Description

Few seconds after GM started, nothing happens. Steam profile status changes for a few seconds. I can actually see the process in the task manager, that gets about 50-60mb and crashes. My PC suits the requirements. Its just doesnt start and i dont know how to actually make the Contact Us Package without going into the app.

### Steps To Reproduce

1. Start GameMaker
2. Absolutely fails
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment] 2024-05-02 08:38
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.

**Closed by jackerley** 2024-05-02 08:38 UTC
Labels: ide-bug

**Comment by YYDan** [comment] 2024-05-02 09:04
If you do continue to have this issue after carefully reviewing the guide above, as the problem is almost certainly antivirus or possibly system drivers, then you can find GameMaker's ui.log file in Windows Explorer by opening the the folder %programdata%\GameMakerStudio2\ (which usually means C:\ProgramData\GameMakerStudio2\)

Please ensure you send us that file if you do need to send another report, as without that there's no specific advice we can give. Thanks.
