### ISSUE TITLE
string_join returns an incorrect result when using variable as argument

### ISSUE THREAD

**Issue by UTF00** [YoYoGames/GameMaker-Bugs#6498] opened 2024-07-03 11:24 UTC
### Description

 When using
```gml

//No problem when the arguments are constant
show_message(string_join("-","start","str1","end"));
//expectation: "start-str1-end"
//output: "start-"str1"-end"


//Constant will lost if a variable before it
var a="str1";
show_message(string_join("-","start",a,"end"));
//expectation: "start-str1-end"
//output: "start-str1"


//The last variable eats up all the remaining constants
var a="str1";
show_message(string_join("-","start",a,"end"));
//expectation: "start-str1-end"
//output: "start-str1"

var a="str1";
var b="str2";
show_message(string_join("-","start",a,b,"end"));
//expectation: "start-str1-str2-end"
//output: "start-str1-str2"


//And if the last argument is a variable, there's no problem with that
var a="str1";
var b="str2";
show_message(string_join("-","start",a,b,"end",a));
//expectation: "start-str1-str2-end-str1"
//output: "start-str1-syr2-end-str1"
```

### Steps To Reproduce

1. Start GameMaker
2. Type the code above
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-07-03 11:25
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6480

**Closed by YYDan** 2024-07-03 11:25 UTC
Labels: runner-bug

**Comment by YYDan** [comment] 2024-07-03 11:26
Sorry, you were probably well under way writing this one up as I was making my changes, but the other report there identified string_join() was affected also, and so I just a few mins ago edited its title and pinned it as a known issue ;)

Thanks anyway!
