### ISSUE TITLE
unstable af

### ISSUE THREAD

**Issue by adriano-t** [YoYoGames/GameMaker-Bugs#8296] opened 2024-11-04 17:59 UTC
### Description
unstable af

### Steps To Reproduce
random

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[98419756-7998-4aa2-8029-9985508df9d5](https://api.gamemaker.io/api/github/downloads/98419756-7998-4aa2-8029-9985508df9d5)

**Comment by stuckie** [comment] 2024-11-05 15:37
Duplicate of #7648

**Closed by stuckie** 2024-11-05 15:37 UTC
Labels: crash, dump, low quality
