### ISSUE TITLE
In-Game Audio: [OperaGX] Drop-outs in looped audio when game is running below target framerate

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#205] opened 2023-07-28 12:36 UTC
GM-2154

*As stated by the user:*

_I ran The Swords Of Ditto and Hyper Light Drifter through the OperaGX target. The games boot and run, but their framerate is noticeably lower than desktop platforms, sometimes straying below 30FPS. This is perhaps to be expected, but the biggest problem is that the audio thread seems to not be keeping up causing many distracting and acoustically unpleasant drop-outs. These drop-outs go away when the game is running above 60FPS._

**Comment by toby-yoyo** [comment] 2024-11-11 16:30
This has already been fixed as much as is currently possible by [GM-5377](https://bugs.opera.com/browse/GM-5377) in Sep '22.

The core issue here is that audio on GX.games is rendered on the main thread, and so frame drops can also lead to missed audio deadlines.

Part of the solution implemented for GM-5377 was that the mix buffer size would grow in response to missed deadlines until they had stopped. This meant that while drop-outs would not be completely avoided, they would stop very quickly after initially occurring.

Attached is an example project that drops frames by busy-waiting: [gmb-205-x.zip](https://github.com/user-attachments/files/17705589/gmb-205-x.zip)
When running the project, you will hear that there are some drop-outs right at the beginning, but they should very quickly stop as the runner reacts to them. From then on, audio should play smoothly.

Once we are able to thread on the WASM runner (this may come with GMRT), audio mix scheduling on GX.games should begin to work as it does on other targets (ignoring HTML5).

As this was already fixed by GM-5377, I'm closing this as a duplicate of that.

**Closed by toby-yoyo** 2024-11-11 16:30 UTC
Labels: runner-bug, import
