### ISSUE TITLE
Ticket: #179668 - Windows .ZIP build: Store streamed audio files in different location

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3585] opened 2023-06-06 15:16 UTC
Ticket: [Ticket #179668]

*Description:* I'm not sure if this affects other desktop builds, but when building an executable for Windows all the "Compressed - Streamed" audio files are stored in the same location as the .exe file. This makes the build folder really messy and the .exe file hard to locate. If possible, I'd like the option to choose where streamed audio files are placed when creating a .zip build. Or, simply default to storing the files in an "audio" sub-folder or something. I've included a link to a forum post I created discussing this topic.

*Benefit:* The .zip build folder would look nicer without all the sound files cluttering it up.

*Link:* [https://forum.yoyogames.com/index.php?threads/store-streamed-audio-files-in-different-location-for-zip-build.82966/#post-494792]

**Comment by YYDan** [comment] 2024-08-08 08:23
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2732

**Closed by YYDan** 2024-08-08 08:23 UTC
Labels: feature request, import
