### ISSUE TITLE
struct_get_by_index or struct_get_values & accesor

### ISSUE THREAD

**Issue by legocris** [YoYoGames/GameMaker-Bugs#8578] opened 2024-12-01 13:07 UTC
### Is your feature request related to a problem?

I would like to access with ease to struct members by index. Just that.

An example where I need this:
When getting values from an internet database, sometimes I get nested structs like this:
```
struct = {first: {second : 10}}
//So to get the value I have to do this
var _names = struct_get_names(struct);
var _nested = struct[ $ _names[0] ];
value = _nested[ $ struct_get_names( nested )[0] ];
```

### Describe the solution you'd like

To add one or both of the next functions.
struct_get_by_index(struct, index) => Gets "index" element of the struct (ordered by default way) .
struct_get_values(struct) => Similar to struct_get_names except it rater returns the values on the array.

It would be much cool if you add a way to access to those values by index on an accessor but I don't know the implications of having a single data structure with multiple accessor types.

### Describe alternatives you've considered

I currently do this if it can give you an idea how could an accessor of the kind be used

```
//Adds __names & __values fields to structs
function struct_indexer(_struct){
	static _recursive = function(__value, __recursive){
		if ( is_struct(__value) ){
			with{ __recursive }
				struct_foreach( __value, function(__n, __v){__recursive(__v, __recursive)});
			
			var __names = struct_get_names(__value);
			var __values;
			with {__value} 
				__values = array_map(__names, function(__v){ return __value[$ __v] } );
			struct_set( __value, "__values", __values);
			struct_set( __value, "__names", __names );
		}
		else if ( is_array(__value) ) 
			with{ __recursive }
				array_foreach( __value, function(__v){__recursive(__v, __recursive)});
	}
	
	_recursive(_struct, _recursive);
}

struct = {first: {second : 10, second2 :[1,4,5]}};

show_debug_message( struct.__values[0].__values[1][1] ); //4
```

**Comment by attic-stuff** [comment] 2024-12-01 13:13
indexing for structs is not possible as they are, by design, unordered hashmaps. if you grab a struct off a database on tuesday then whatever is conceptually first in the struct may not be the same if you snatch it again on thursday. if you need order then you should be using an array. a function to grab an array of values would be cool, but determining which struct field each value goes wouldn't be fun because of the unorderedness of structs. really does sound like you just want an array heh

**Comment by stuckie** [comment] 2024-12-02 09:56
Closing as above.
Internally, this is a hash structure, so the indices will not be stable.
An array is likely what you want.

**Closed by stuckie** 2024-12-02 09:56 UTC
Labels: feature request

**Comment by attic-stuff** [comment] 2024-12-02 23:52
> Is that really the case?

that is the case, yeppers. like stuckie said, the order is not stable. just because you are seeing a predictave/determined order on your machine does not mean you always would or that your players would at all. its literally happenstance heh
