### ISSUE TITLE
CE2: Clicking in the declaration panel of a variable will higlight comment text.

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6884] opened 2024-07-25 23:46 UTC
### Description
I dont think this should happen. if its a feature close.

### Steps To Reproduce
1) Match 3 template
2) obj_matching_piece line 1 declarations.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files:
GameMaker-Beta_qjvtKkT0v0.mp4, GameMaker-Beta_hRPEafis6V.png

[161cebec-9a3c-4374-96c5-e61845e64487](https://api.gamemaker.io/api/github/downloads/161cebec-9a3c-4374-96c5-e61845e64487)

**Comment by zreedy** [comment] 2024-11-21 16:17
The video is showing the variable being highlighted correctly. The additional highlights are due to the "highlight matching selection text" feature. Closing as this is working as intended.

**Closed by zreedy** 2024-11-21 16:17 UTC
Labels: ide-bug
