### ISSUE TITLE
YYC export crashes but not VM

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6762] opened 2024-07-18 15:44 UTC
### Description
The project can run fine in VM but crashes in YYC.

### Steps To Reproduce
1. Run the project under the `dev` config for Windows VM, see it does not crash
2. Run for Windows YYC, see the in-game exception:

```
Caught exception:
############################################################################################
ERROR in action number 1
of Create Event for object o_init:
argument is not a method, unable to call############################################################################################
gml_Script_register@Cakeframe@CakeframeConstructor (line 1746)gml_Script_cf_parse (line 13)gml_Script_cf_add_cell (line 393)gml_Script_cf_add_cells (line 380)gml_Script_register@Cakeframe@CakeframeConstructor (line 1768)gml_Script_cf_parse (line 13)gml_Script_cf_add_cell (line 393)gml_Script_cf_add_cells (line 380)gml_Script_register@Cakeframe@CakeframeConstructor (line 1768)gml_Script_cf_parse (line 13)gml_Script_cf_attach (line 363)gml_Script_register@Cakeframe@CakeframeConstructor (line 1759)gml_Script_cf_parse (line 13)gml_Script_init_touch_controls (line 192)gml_Object_o_init_Create_0 (line 356)
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Android, iOS, Windows

[404c312e-fd3e-4f59-9ef2-15199e5d67a8](https://api.gamemaker.io/api/github/downloads/404c312e-fd3e-4f59-9ef2-15199e5d67a8)

**Comment by rwkay** [comment] 2024-07-19 09:04
This is a duplicate of #6759 this one is fixed with the same fix

**Closed by rwkay** 2024-07-19 09:04 UTC
Labels: runner-bug, project
