### ISSUE TITLE
[1.4.9999] "Missing tools detected" error

### ISSUE THREAD

**Issue by FollowTheFun** [YoYoGames/GameMaker-Bugs#7585] opened 2024-09-09 20:38 UTC
### Description

Sorry for posting about a 1.4.9999 issue here but it won't even launch due to some server error. 

When trying to install game maker 1.4.9999 on a new computer, it won't launch, and says that tools are missing. If you try to install them, it downloads and extracts something but after launching, and trying to create a new project, you'll be presented with this error again. 

There are 2 recent topics about this
https://forum.gamemaker.io/index.php?threads/game-maker-studio-1-4-not-installing-missing-tools-detected.115286/
https://forum.gamemaker.io/index.php?threads/gamemaker-studio-1-4-error.115136/

and I am also experiencing this issue. I have a working copy of 1.4.9999 on my computer, this test install was created on a VM.

If you need a copy of my functional installed game maker files to resolve this, please let me know.

There also appear to be working downloads to the module files, but perhaps the tools its missing are not the same thing?
[deec894e-fac6-498e-bcaa-cd37147870c0.zip](https://github.com/user-attachments/files/16936360/deec894e-fac6-498e-bcaa-cd37147870c0.zip)

### Expected Change

Ability to use 1.4's IDE again without an error

### Steps To Reproduce

1. Install GameMaker 1.4.9999 on windows 11 (or probably any windows)
2. Enter license code, restart, install extra tools it prompts for
3. IDE will restart and look like it's working, but:
4. Error will occur when creating a new project
5. You can press 'yes install' but it just gets stuck in a loop.

![image](https://github.com/user-attachments/assets/9380edaf-2775-420a-93af-4c53a65a99a0)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by FollowTheFun** [comment] 2024-09-24 22:16
- You can fix this error by creating a Windows8 folder in AppData\Roaming\GameMaker-Studio\Configs\Default\
- You can also stop it trying to update itself by renaming 5pice.exe (in AppData\Roaming\GameMaker-Studio\) to GameMaker-Studio.exe (rename the existing GameMaker-Studio.exe there to something else). 

But it looks like the licensing server is granting a license for "WindowsTest" instead of "Windows", which makes it so you can't compile, only run games. 

This seems like it's quite arbitrary to fix on the server end.

**Comment by LiEnby** [comment] 2024-09-24 22:21
yeah, the main cause of the issue is that the license generated by the server does not contains these addons : 
![image](https://github.com/user-attachments/assets/067cc55c-1216-4ea6-8377-4fbb2207473f)

"Windows8" - which seems to be required for the IDE to work properly .. is missing, 
and more notably- the regular "Windows" module is also missing (only "WindowsTest" which i think is supposed to be an internal thing)

**Comment by YYDan** [comment] 2024-10-18 08:33
Should just have been a blip on the licensing server and fixed back at the time, but (as mentioned above) 1.4 is not covered by this bug database anyway, so closing now. Thanks.

**Closed by YYDan** 2024-10-18 08:33 UTC
Labels: ide-bug

**Comment by FollowTheFun** [comment] 2024-10-19 00:05
> Should just have been a blip on the licensing server and fixed back at the time
As in, a month ago when this started occurring? Or when 1.4 originally was sunset, because similar issues to this have been fixed up to this point. This is first issue left broken. Game maker 8 is still working fine, which is an even older product. 

> 1.4 is not covered by this bug database anyway, so closing now. Thanks.
Yes sorry about that, but there's no other place to contact about this, and if you reach out to the help desk they just tell you to go away 😢 I've reached out to Russell about this but no response. Can you recommend the best place to contact to have this issue fixed?

Alternatively, if there is no possibility of this issue being fixed, do we have the greenlight to use third party tools to get it to work?

**Comment by iampremo** [comment] 2024-11-12 12:26
This issue has now been resolved - https://forum.gamemaker.io/index.php?threads/fixed-gamemaker-studio-1-4-update-licence-issues.116442/
