### ISSUE TITLE
Code Editor 2: Fold/Unfold doesn't work properly for #region.

### ISSUE THREAD

**Issue by Panthervention** [YoYoGames/GameMaker-Bugs#8863] opened 2024-12-25 15:45 UTC
### Description
Basically folding doesn't work for #region and #endregion... like at all! And it also hide the opportunity to fold/unfold its sub-regions.

### Steps To Reproduce
Either Ctrl+M or just click the [-] or [+].

### Which version of GameMaker are you reporting this issue for?
IDE v2024.11.0.179 Runtime v2024.11.0.226

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

[88df06f3-2869-4d56-bef8-fdfd976fd19b](https://api.gamemaker.io/api/github/downloads/88df06f3-2869-4d56-bef8-fdfd976fd19b)

**Comment by AvioxArcade** [comment] 2024-12-26 21:34
having a similar issue, but to provide more details -- it looks like it ultimately doesn't fold anything that has a closing bracket more than 1 line past the current view. 

Where possible, scrolling down or dragging the view large enough to see the closing bracket then trying again will successfully close the region.

**Comment by Emc1923** [comment] 2024-12-27 07:33
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5549

**Closed** 2024-12-27 07:40 UTC
Labels: ide-bug
