### ISSUE TITLE
In-Game: [Spine] skeleton_bone_state_set() does not work with image_angle

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#27] opened 2023-07-28 12:27 UTC
GM-8031

Following GM-7614

Skeleton_bone_state_get() also needs to be changed to allow it to work after setting the rotation with image_angle. 

*Steps to reproduce:*
- Import the project attached
- Run the project
- Observe the issue

**Comment by rwkay** [comment] 2023-11-15 10:25
This is a duplicate of GM-7777 and that has already been fixed in 2023.8

**Closed by rwkay** 2023-11-15 10:25 UTC
Labels: runner-bug, import
