### ISSUE TITLE
Code Editor 2: Declaration variables are not listed in an Object event that uses event_inherited()

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5953] opened 2024-05-24 21:31 UTC
### Description
as title or watch video.
if you use event_inherited in the create code it will not show the variable declarations.

### Steps To Reproduce
1) Open Platform Template
2) See obj_enemy create event.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[7f675570-5d68-4c96-9048-54c356d0ba1c](https://api.gamemaker.io/api/github/downloads/7f675570-5d68-4c96-9048-54c356d0ba1c)

**Comment by stuckie** [comment] 2024-07-26 15:22
Possibly related to #5550

**Comment by zreedy** [comment] 2024-08-23 20:31
Fixed

**Comment by scott-dunbar** [comment] 2024-09-19 15:04
This fix is incomplete or possibly due to the issue related not completely testable in  IDE v2024.1100.0.623  Runtime v2024.1100.0.649

The same repro steps as given above results in a single declaration shown and not all declarations. The linked issue above should be addressed at the same time as this issue 

![image](https://github.com/user-attachments/assets/7e289705-050b-45e9-a806-35a94ecd51a2)

![image](https://github.com/user-attachments/assets/2627d823-2298-4cd8-aaf2-63b5abdad23b)

**Comment by scott-dunbar** [comment] 2024-09-20 14:58
Note - this appears to only really be occuring when having the Navigation Pane in the side orientations. top and bottom orientations are functioning correctly

![Image](https://github.com/user-attachments/assets/d5eae2ad-3b15-4776-802a-252610de3520)

**Comment by zreedy** [comment] 2024-09-25 16:38
Regression is fixed.

**Closed** 2024-11-01 16:13 UTC
Labels: ide-bug, project

**Comment by Emc1923** [comment] 2024-11-04 08:16
Verified fixed as of  IDE v2024.1100.0.666  Runtime v2024.1100.0.692.
