### ISSUE TITLE
Code Editor (Visual): Autocomplete window does not appear when typing code if Feather is enabled

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1526] opened 2023-08-16 13:26 UTC
GM-8071

When typing in the 'execute code' visual action the code autocompletion window does not appear at all, as shown in the attached video.

 [^new_project_template - GameMaker 2023-07-31 11-03-00 (2).mp4] 

*Steps*

- Launch the IDE
- Open any project
- Type some code into an object event or script
- Convert the code to GML visual
- Start typing the name of a function or variable
- Observe that the autocomplete does not appear

Repro: 100%

**Comment by YYDan** [comment] 2024-08-19 13:41
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/977

**Closed as not planned by YYDan** 2024-08-19 13:41 UTC
Labels: ide-bug, import
