### ISSUE TITLE
Don't keep creating ~/GameMakerProjects folder when Paths are set to custom folders.

### ISSUE THREAD

**Issue by bryanrieger** [YoYoGames/GameMaker-Bugs#7678] opened 2024-09-17 13:00 UTC
### Is your feature request related to a problem?

When I set the IDE General Settings -> Paths to folders such as /Users/{user}/Games (Projects) and /Users/bryanrieger/Library/Application Support/GameMakerStudio2/Templates (Templates) the IDE insists on recreating the empty (and unused) ~/GameMakerProjects folder in my user dir every time I launch GameMaker.

### Describe the solution you'd like

Stop creating the ~/GameMakerProjects folder if the 'My Projects' and 'Template Projects' directories are set to custom paths.

### Describe alternatives you've considered

Deleting the ~/GameMakerProjects folder doesn't work as it's recreated every time I launch GameMaker. Currently I use `chflags hidden /Users/bryanrieger/GameMakerProjects` (I'm on macOS) to hide it, but it's just annoying.

**Comment by YYDan** [comment] 2024-09-17 15:16
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/4620

**Closed by YYDan** 2024-09-17 15:16 UTC
Labels: feature request
