### ISSUE TITLE
`call_later` first run always undershoot by approx 300millis if object was created from room

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#6636] opened 2024-07-12 15:43 UTC
### Description

The problem is exactly what is discribed... when an object is created from a room the first call to call_later always undershoots by approx 300millis.

![image](https://github.com/user-attachments/assets/a0bd7a7e-015e-4b3b-b2c9-75ffb607890f)

I included 2 rooms one where there is no bug (obj_ini instantiates the obj_run) and another where there is a bug (obj_run is placed directly in the room).

[call_later_first_run_undershoot.zip](https://github.com/user-attachments/files/16196333/call_later_first_run_undershoot.zip)

### Expected Change

The delta time should always be pretty much the same

### Steps To Reproduce

1. Start GameMaker
2. Run the game and check the console log the first value printed has 300millis difference from the others.
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment] 2024-07-15 16:32
The two scenarios are not the same and so cannot be measured in the same way.

Just for reference, here is the code in the example project used to measure this:
```
a = get_timer();
call_later(3, time_source_units_seconds, function() {
	a = get_timer() - a;
	show_debug_message(a);
	a = get_timer();
}, true);
```

### Object in room at game start

The important point here is that this object will exist before any frame is processed. The first callback of the time source set up at this time is invoked relative to the internal timers being initialised. The internal timers are set up more or less at the beginning of engine initialisation, so there is a fair amount of work done between that moment and the moment the first line of GML is executed.

By the time `get_timer` in the object's create event is executed, some time will have already passed as the engine was setting up to run the game. So the time source's internal reference and the one taken in the object's create event are not the same point in time. This makes it seem like the first callback is being invoked at the wrong time.

To account for this, the reference point in the object should be zero to match the time source's reference point in this particular scenario:
```
a = 0;
call_later(3, time_source_units_seconds, function() {
	a = get_timer() - a;
	show_debug_message(a);
	a = get_timer();
}, true);
```

This will yield the expected result.

### Object created by another object

The reason this scenario behaved as expected was because the reference point of the time source was the same as the one taken in the object. When the 'child' object is created, a game frame will have already been started and so the built in time sources will have ticked. This means that the time source will be referencing the time taken at the start of the first frame, which is correctly approximated in the initial code by calling `get_timer`.

**Comment by toby-yoyo** [comment] 2024-07-16 08:43
Closing as not a bug.

**Closed by toby-yoyo** 2024-07-16 08:43 UTC
Labels: runner-bug
