### ISSUE TITLE
Updater: [Win IDE] GM can crash on startup after updating from 2024.1100 Beta 686 to 700

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8559] opened 2024-11-29 05:51 UTC
### Description
After updating to 2024.11.0.700 from 2024.11.0.686 using the auto-updater, it did appear to successfully reinstall, which is an improvement from #8249. However, it seems the newly installed version was corrupted somehow, since when I tried to open it I saw a command line window saying that it's making a crash dump appear for a split second and then nothing further happened. It seems GM was attempting to open but crashing in some early step. Repeatedly trying to open it yielded the same result every time.

The command line window:
![Image](https://github.com/user-attachments/assets/37327611-05a1-424c-a39d-142891fae546)

I manually installed 2024.11.0.700 and GM opened just fine, at which point I got the prompt to send this crash report.

Edit: I installed .686 again and repeated the process, and it worked just fine in that 2nd attempt. Repeating the process a 3rd time resulted in the same instant crashing. 4th attempt worked again. So whatever went wrong isn't a 100% repro, but not rare either.

### Steps To Reproduce
1. Update from 2024.11.0.686 to 2024.11.0.700 using the updater
2. Be me I guess

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.700 Runtime v2024.1100.0.718

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[4ad480ce-9fdd-4a4a-9192-4b7ca5c3447e](https://api.gamemaker.io/api/github/downloads/4ad480ce-9fdd-4a4a-9192-4b7ca5c3447e)

**Comment by stuckie** [comment] 2024-12-05 17:08
This appears to be falling over very early in the startup while trying to load our main IDE assembly - hence why nothing gets logged out.
Specifically, it seems that it cannot load the MQTTnet dependency.
If this triggers again, it would be interesting to see if MQTTnet.dll is in the install directory.

**Comment by stuckie** [comment] 2024-12-07 08:14
It's been confirmed that MQTTnet.dll *is* missing when the crashes occur.
![Image](https://github.com/user-attachments/assets/4aad1b8c-87a3-4fb4-be03-02eff25b2c34)

**Comment by YYDan** [comment] 2024-12-11 15:50
Beta IDE 710 has an attempt to fix this by adding a few waits before moving on to the next phase of the updater, so we give any permissions issues time to resolve themselves before we try launching the IDE, plus a fix to stop multiple updaters being able to be launched at once and potentially work on adding/removing files at the same time.

**Comment by YYDan** [comment] 2024-12-12 09:12
@KormexGit Is 710 -> 713 now reliable on your machine also?

**Comment by KormexGit** [comment] 2024-12-12 11:01
@YYDan Yup, seems to be working every time. Tried about 10 times I think?

**Comment by stuckie** [comment] 2024-12-13 10:02
Closing as seems to be fixed now!
Final updates added extra waits between uninstall and install, and a check to ensure it's the only instance running.

**Closed by stuckie** 2024-12-13 10:02 UTC
Labels: crash, dump

**Comment by YYDan** [comment] 2024-12-13 10:25
Verifying per the above comments also. All has been fine for us internally for a while.
