### ISSUE TITLE
In-Game: Changes new in runtime 2024.600.0.603 make call stacks show the wrong line number

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6333] opened 2024-06-19 00:58 UTC
### Description
This uses the project from https://github.com/YoYoGames/GameMaker-Bugs/issues/6332. When running the project for windows VM in debugger mode, one element from the callstack shows the wrong line number.

### Steps To Reproduce
1. Put a break point at BschemaSchemas.gml line 136
2. Run the project under the dev config for windows VM export in debugger mode
3. When the break point is reached, see that in the Call Stack, in `BschemaSchemaSchema.gml`, the line should be 14 instead of 3.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.577 Runtime v2024.600.0.603

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[4063b60c-fbe8-45dd-a725-55098205e047](https://api.gamemaker.io/api/github/downloads/4063b60c-fbe8-45dd-a725-55098205e047)

**Comment by shichen85** [comment] 2024-06-19 00:58
![GameMaker-Beta_Y5OTmMgiam](https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/666362de-7c72-4422-b891-c110660a287d)

**Comment by YYDan** [comment] 2024-06-19 10:00
Suspected to be caused by the fix for https://github.com/YoYoGames/GameMaker-Bugs/issues/6190 - will take that one out again just now and investigate a different fix.

**Comment by YYDan** [comment] 2024-06-21 09:11
See my comment on the related issue for more. tl;dr all seems fine to me in runtime 605, but I never actually reproduced this in 603 (although, clearly other errors).

@shichen85 can you confirm you no longer have this problem with your original repro steps, please?

**Comment by shichen85** [comment] 2024-06-21 13:40
> See my comment on the related issue for more. tl;dr all seems fine to me in runtime 605, but I never actually reproduced this in 603 (although, clearly other errors).
> 
> @shichen85 can you confirm you no longer have this problem with your original repro steps, please?

Replied!

**Comment by rwkay** [comment] 2024-06-26 10:04
Fixed in 2024.8??? I am a bit more dubious about this one as I cannot replicate it but problem code from 603 has been fixed.

**Closed by rwkay** 2024-06-26 10:04 UTC
Labels: ide-bug

**Comment by scott-dunbar** [comment] 2024-08-26 08:42
This appears to be fixed as far as I can tell - verified in  IDE v2024.800.0.614  Runtime v2024.800.0.637
