### ISSUE TITLE
Preferences: Opening certain sections in "Text Editors" or "Feather Settings" introduces a lag opening other sections thereafter or closing Preferences itself in Beta IDE 472

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#4466] opened 2024-01-23 16:19 UTC
### Description
When opening:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/9cf17d31-1683-4ba7-9a80-887901052f71)
or
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/622a2edf-bc79-493b-b017-65c5b97e6124)

There's noticeable lag in IDE (1-5 seconds).

What's more, when pressing Cancel after opening any of above, there's 5+ seconds lag.

Additionally, it's possible to get the "failed mouse click" mentioned in step 7 below when changing to (m)any other Preferences screens thereafter - the issue is not limited to just the two sections shown above.

### Steps to Reproduce
1. Start GameMaker
2. Open Preferences
3. Open "Text Editors" and observe this likely loads immediately
4. Now click the child "Code Editor" and observe this will have a short pause before it loads
5. Click "Visual Editor" and observe this likely loads immediately
6. Click "Code Editor" again and observe this likely loads immediately
7. Now begin slowly clicking any random one of "Text Editors", "Code Editor", and "Visual Editor" each time and observe that periodically your mouse click on the Preference tree will be ignored and the chosen section will not be opened
8. At any time, click either the Cancel button or the close X in the top-right corner and observe a longer delay before Preferences actually closes (this does not depend on which page of Preferences is open at the time)
Repro: 100% (although you might need to click through any number of times before you see step 7, as this seems to vary for me but it usually fairly quick to occur)

Alt
1. Repeat steps 1 and 2 above
2. Open "Feather Settings" and observe this likely loads immediately
3. Now click the child "Message Severity" and observe this will have a short pause before it loads
4. Now repeat ultimately the same things as steps 5-8 above, but using the various child pages of "Feather Settings" instead of "Text Editors" and observe you can recreate the same results
Repro: 100% (again, you might need to click through any number of times before you see step 7 above)

[466fe39d-c2ca-4781-81fc-f74839d96ef0](https://api.gamemaker.io/api/github/downloads/466fe39d-c2ca-4781-81fc-f74839d96ef0)

**Comment by YYDan** [comment] 2024-01-24 10:56
Closing as duplicate of #1935 - but have taken a lot of the expanded info from here and put it onto that one.

**Closed by YYDan** 2024-01-24 10:56 UTC
Labels: ide-bug
