### ISSUE TITLE
Code Editor 2: "Language server failed to load" notification appears often when starting GM

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7161] opened 2024-08-08 02:57 UTC
### Description
I've been periodically having the language server for CE2 fail to load at all, with an error message in the top right of the IDE. The message disappears super fast though, so I wasn't able to screenshot it. I'm reporting this right after it happened in hopes that maybe some of the log files will show what happened, since it seems to be fairly random. What specific project I open doesn't seem to have an affect, since I've had it happen for projects that were almost entirely empty.
Once it fails to load, GM has to be restarted to fix it. The issue specifically happens when the first project is opened after opening GM, loading multiple projects without closing GM does not trigger it.

### Steps To Reproduce
Start GM, open up a project, and see if the language server fails to load. Close GM and repeat. When it happens seems to be random, sometimes it won't happen for dozens of starts in a row, and other times it will happen multiple times in just a few starts.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[2aca7b7c-03bc-4531-81ab-ccf1ad74926f](https://api.gamemaker.io/api/github/downloads/2aca7b7c-03bc-4531-81ab-ccf1ad74926f)

**Comment by KormexGit** [comment] 2024-08-10 03:38
Had it happen again and managed to snap a screenshot before it vanished, the parts I redacted was just my account name and project name/filepath.

![image](https://github.com/user-attachments/assets/ab10ba2b-83aa-40bc-a6fd-e11cd28edfe9)

When this happens, none of the code gets colored properly, no feather tooltips appear, no autocomplete appears, no diagnostics appear, and more. Persists through loading any number of projects, only fixed by a full restart of GM itself.

**Comment by KormexGit** [comment] 2024-08-18 16:02
This frequency of this issue seems to have increased, I often have to start GM 2-3 times to be able to use CE2. I also had it trigger when swapping projects, so it's not just on initial GM load.

**Comment by KormexGit** [comment] 2024-10-08 00:08
In latest beta I haven't had this happen in the 3 days I've been using it so far

**Comment by sihammill** [comment] 2024-11-07 09:47
@sykhro is this bug fix still ok to be implemented for Nov24 or does it need punting on?
I'm just very aware that this bug fix hasn't yet being started.

Cheers

**Comment by sykhro** [comment] 2024-11-07 11:19
> [@sykhro](https://github.com/sykhro) is this bug fix still ok to be implemented for Nov24 or does it need punting on? I'm just very aware that this bug fix hasn't yet being started.
> 
> Cheers

This bug in particular was already fixed, the issue is manifesting again due to a different cause (#8271).

**Comment by zreedy** [comment] 2024-11-08 20:34
This regression has been fixed in the PR for the above private ticket. Please be mindful that future changes to the project format may regress this again with the fix being to readdress the above private ticket.

**Closed** 2024-11-12 10:32 UTC
Labels: ide-bug

**Comment by sihammill** [comment] 2024-11-12 11:59
I have open and closed the latest Beta IDE many times now and I've not had one instance of the Language Server failing.
Tested using IDE v2024.1100.0.681  Runtime v2024.1100.0.703
