### ISSUE TITLE
Text - draw_color overwrites text effects

### ISSUE THREAD

**Issue by patrickrocheyoyo** [YoYoGames/GameMaker-Bugs#7663] opened 2024-09-16 11:27 UTC
### Is your feature request related to a problem?

draw_color effects everything about text, including effects. White text, for example, with a blue outline becomes red text with a purple outline if you use draw color if the user sets draw_color to red. It feels like it should not impact text effects.

### Describe the solution you'd like

For draw color to not impact text effects

**Comment by attic-stuff** [comment] 2024-09-16 14:06
afaik this is by design, draw_set_color is a global change to vertex color in the current vertex batch, which effects everything but sprites and changing it to not effect text would be a massive compatibility blow, breaking lots of projects. but yeah, the vertex color is multiplied by the texture color, giving you the result you see. if you want to use draw set color, but skip text, you should be doing this:

```js
/* store the current color instruction */
var current_color = draw_get_color();
/* set the new instruction to white */
draw_set_color(#ffffff);
/* draw your text here */
/* reset the instruction */
draw_set_color(current_color);
```

**Comment by stuckie** [comment] 2024-09-17 08:44
Closing as above. Thanks!

**Closed by stuckie** 2024-09-17 08:44 UTC
Labels: feature request
