### ISSUE TITLE
Closing GameMaker while having an excessive number of workspace windows open causes GameMaker to keep showing as open in the task manager even when closed, and allows having two GameMaker in the task manager at the same time if re-opened

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7658] opened 2024-09-16 09:13 UTC
### Description
Probably related to #7654. If you close GM while having hundreds of windows open in the workspace, GameMaker's window will go away and it will show as closed in the taskbar, but opening the task manager shows it as still being an active process, with it using up CPU and memory as if it was never closed. In fact, CPU usage spikes after it's closed.

I had to stop the recording right before quitting, because closing GM crashes shareX's recording for some reason.

https://github.com/user-attachments/assets/54edd789-3fbf-44e5-9d6c-699362e8876f

After closing GM:
![image](https://github.com/user-attachments/assets/8819d9df-3626-4c44-afcb-940d0ca2ee53)

Additionally, if you re-open GM, the task manager will show two GM processes at the same time.

After re-opening GM:
![image](https://github.com/user-attachments/assets/3803553c-226d-4e45-8d1b-a61a1acb1f86)

Edit: After several minutes, the ghost GM did eventually disappear from the task manager. So I guess it just takes a really long time for it to process closing the workspace windows, even after the main GM window is gone?

Edit2: I tried this same thing on 2024.6, and in 2024.6 GM disappears from the task manager in just a couple seconds when repeating this same process, so it does appear to be some sort of lag issue that's new to 2024.8.

### Steps To Reproduce
1. Create 100+ assets and open them all in the workspace. GameMaker should start getting pretty laggy.
2. Open the task manager.
3. Close GM.
4. See GM still showing up in the task manager.
5. Re-open GM. There will now be two GM in the task manager.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[a407808f-3ff0-45c7-8947-55625b96c4b0](https://api.gamemaker.io/api/github/downloads/a407808f-3ff0-45c7-8947-55625b96c4b0)

**Comment by stuckie** [comment] 2024-10-07 08:04
This very likely was a duplicate of #7676 .. can you verify this is no longer the case in recent betas?
I haven't been able to reproduce this locally.

**Comment by KormexGit** [comment] 2024-10-07 09:11
Yup looks to not be happening for me anymore in beta

**Comment by stuckie** [comment] 2024-10-29 09:24
Closing as above.

Thanks for letting us know!

**Closed by stuckie** 2024-10-29 09:24 UTC
Labels: ide-bug, project
