### ISSUE TITLE
Can't build on Linux when Steamworks script copy dependencies

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4961] opened 2024-03-09 16:04 UTC
### Description
Building from Windows IDE on Linux fails, tested on two different machines

```[STEAMWORKS] INIT: Script initialization succeeded (v1.6.2 :: 1).
"Copying Linux (64 bit) dependencies"


    Directory: C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC


Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----        09/03/2024     16:54                _temp                                                                




C://GMS//extensions//Steamworks\post_build_step.bat DONE (0)
mkdir -p /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\Ref.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/Ref.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYGML.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYGML.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYRValue.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYRValue.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYSlot.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYSlot.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\YYStd.h /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/YYStd.h
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\libyoyo_yyc-x64.a /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/libyoyo_yyc-x64.a
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\makefile /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/makefile
pscp C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163\linux\execute.sh /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/execute.sh
chmod +x /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/execute.sh
mkdir -p /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/Game/
pscp C:\Users\user\AppData\Local\GameMakerStudio2\GMS2TEMP\Chronique_des_Silencieux_2E5660C4_YYC\Game\ /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux/Game/
rsync -c -r /home/tom/GameMakerStudio2/yyc/FromPC/Chronique_des_Silencieux /home/tom/GameMakerStudio2/yyc
unshare -mUprf sh -c 'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin && cd /tmp/ && make -C /tmp/ -j `nproc --all`"' -- /home/tom/GameMakerStudio2/yyc/Chronique_des_Silencieux /opt/steam-runtime
make: Entering directory '/tmp'
mkdir -p out
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasAppSurf.gml.o Game/gml_GlobalScript___CanvasAppSurf.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasCleanupQueue.gml.o Game/gml_GlobalScript___CanvasCleanupQueue.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasError.gml.o Game/gml_GlobalScript___CanvasError.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasGC.gml.o Game/gml_GlobalScript___CanvasGC.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasSurfFormat.gml.o Game/gml_GlobalScript___CanvasSurfFormat.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasSystem.gml.o Game/gml_GlobalScript___CanvasSystem.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CanvasTrace.gml.o Game/gml_GlobalScript___CanvasTrace.gml.cpp -DYYLLVM
clang-3.8 -std=c++14 -m64 -O3 -Wno-deprecated-writable-strings -I Game  -include-pch out/pch.hpp.pch -c -I . -o out/gml_GlobalScript___CleanConfig.gml.o Game/gml_GlobalScript___CleanConfig.gml.cpp -DYYLLVM
make: Leaving directory '/tmp'
System.Exception: command 'unshare -mUprf sh -c 'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin && cd /tmp/ && make -C /tmp/ -j `nproc --all`"' -- /home/tom/GameMakerStudio2/yyc/Chronique_des_Silencieux /opt/steam-runtime' failed with exit status 2
   at Igor.LinuxBuilder.plink_async(String command, Boolean fail_on_error)
   at Igor.LinuxBuilder.LinuxSendAndBuildMakefile(String _dir)
   at Igor.LinuxBuilder.Package()```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0


[beebd193-0f06-4b5e-b397-f72a6f3a062f](https://api.gamemaker.io/api/github/downloads/beebd193-0f06-4b5e-b397-f72a6f3a062f)

**Comment by stuckie** [comment] 2024-03-11 10:22
Closing as duplicate of #4962

**Closed by stuckie** 2024-03-11 10:22 UTC
Labels: build-bug, project
