### ISSUE TITLE
Deleting path nodes in a room will also delete the currently selected object

### ISSUE THREAD

**Issue by slyddar** [YoYoGames/GameMaker-Bugs#1863] opened 2023-10-07 04:14 UTC
### Description

In the IDE, while in a room and having an object selected, if you then select a path layer and select a path node, then press delete, it will delete the node, but will also delete the object you had selected.

### Expected Change

The object should deselect when the path is selected, and should not be deleted

### Steps To Reproduce

1. Start GameMaker
2. Create a new path with a few nodes
3. Add a path layer to the room
4. Assign the path to the path layer
5. Create an object
6. Add object to the instances layer in room
7. With the instance selected, select the path layer
8. Select a path node and press the delete key

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.1 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2023-10-31 16:44
Duplicate of #1264

**Closed by YYDan** 2023-10-31 16:44 UTC
Labels: ide-bug
