### ISSUE TITLE
Multiple processes stack drawing on the same window

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1673] opened 2023-09-12 03:13 UTC
### Description

I have 2 projects which make use of launching 1 or more additional processes of the game application.
The first one makes use of additional processes which are hidden to add multi processing, this actually isnt much of an issue as (at least on windows) i can make use of `draw_enable_drawevent(false);` Which prevents the stacked processes in the same window from running their draw events.
Although for the second project, I wish to launch an additional window as an external control panel to change scenery, objects, and events for use with streaming, So the main process would be the window which is streamed, and the second process would be a detached window which has a GUI for manipulating the scene on the fly. This is no longer possible to do with in the same repo.
[doot.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12581994/doot.zip)

### Steps To Reproduce

1. Compile my Multi Processing Library: https://github.com/tinkerer-red/MultiProcessing

Here is several examples of the effects when running it with different hide options:
![Example](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/a81d9f67-7816-448e-8322-e4565af5595f)
![Example2](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/2e337ccb-d11f-4af6-a4a2-18fa79deb504)
![Example3](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/3a40af63-15ee-4267-8787-e952f14d3975)

(Note previous versions of Stable do not produce these effects)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by tinkerer-red** [comment] 2023-09-12 03:18
Note, this also makes it impossible to do fast testing of online multiplayer because multiple instances of the same game will all stack on one another.

**Comment by tinkerer-red** [comment] 2023-11-22 17:31
Appears `game_change`'s internals essentially highjacks the ability to launch an additional window of the same game, or another GM game.

Test project which has code for [XProcess]() by Samuel Venable, but using [execute_shell_simple](https://yellowafterlife.itch.io/gamemaker-execute-shell-simple) by YellowAfterLife will also produce the same results.
[xprocess_test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13442702/xprocess_test.zip)


![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/ece7a287-084f-42f6-ad33-37bbe0271da6)
I was able to produce the same results by using a pre-dated version of gamemaker 2023.6 to compile the test project, while the update.exe is 2023.8. And the same results occur. the update.exe will take control of my window and pause all execution.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/b20c8a3e-c9ce-4aa4-a987-155fefa2d3eb)
The debug message doesnt show up at all
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/b6943a66-350b-4c34-a7ff-b840004b24b1)
but when I close the game...
https://gyazo.com/27875ce6e594b64d880bbcccfc0cd566.mp4
and this is also when a new window of the original game appears.

**Comment by rwkay** [comment] 2023-11-22 17:50
This should be fixed (I think) - I think there is a duplicate bug (that will have the fix info on it)

**Comment by tinkerer-red** [comment] 2023-11-22 17:52
> This should be fixed (I think) - I think there is a duplicate bug (that will have the fix info on it)

Do you by chance know what that ticket number is so I can keep up to date with it?

**Comment by rwkay** [comment] 2023-11-22 17:58
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1790

which is fixed in 2023.11

**Closed by rwkay** 2023-11-22 17:58 UTC
Labels: runner-bug

**Comment by time-killer-games** [comment] 2023-11-22 19:52
Thanks Russell, pkraif, and everyone else involved for the help.
