### ISSUE TITLE
Code Editor: Ability to convert selected lines into a new #region

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4175] opened 2023-06-06 14:39 UTC
### Description

It would be amazing to select a piece of code and then either right click, or press a shortcut to surround that select code in a region and have the cursor at the region's name.

**Comment by YYDan** [comment] 2024-02-26 11:39
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3063

**Closed by YYDan** 2024-02-26 11:39 UTC
Labels: feature request, import
