### ISSUE TITLE
Code Editor 2: ctrl + z with a highlighted selection breaks the highlighting in various ways

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7097] opened 2024-08-04 06:15 UTC
### Description

Undo with highlighted selection can break the selection in various ways.

![ce2 ctrl z breaks highlighted sections](https://github.com/user-attachments/assets/708eecf5-4860-40dc-a02f-fa3770583d39)

CE1 appears to preserve highlighted regions on the undo stack.

![the correct ctrl z highlight behavior](https://github.com/user-attachments/assets/785894bc-6701-4b16-a690-76c32cad1311)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment] 2024-08-04 06:16
this might be a more general case of #7037

**Comment by stuckie** [comment] 2024-08-06 09:07
Duplicate of #7037

**Closed by stuckie** 2024-08-06 09:07 UTC
Labels: ide-bug
