### ISSUE TITLE
Closing 122 sprites takes 3 minutes

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7676] opened 2024-09-17 09:48 UTC
### Description
In 2024.8 there seems to be some weird bug with memory allocation, so closing sprite takes huge amount of time.

I've imported 112 sprites to project (which took around 3 minutes - this also seems to be a bug), and then opened them all. 
Then, I've used "close all" command, and it took ~3 minutes before IDE became responsive (2:48 to be precise)

This might be connected to #7599, #7627, #7658

### Steps To Reproduce
1. Right Click on Sprites group and select `Edit All`, it would take some time (around 20-30 seconds)
2. Right Click on Workspace and select `Close All`
3. Take your time to make tea or coffe , as IDE is not responsive anymore
4. After nearly 3 minutes, IDE would start to response

Alternatively:
2. Open new Workspace, close `Workspace 1`

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.0.169 Runtime v2024.8.0.216

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

*I've used sprites from https://kenney.nl/assets/scribble-dungeons*

[70e4eb4a-1b6d-4f42-960d-e533dd87186b](https://api.gamemaker.io/api/github/downloads/70e4eb4a-1b6d-4f42-960d-e533dd87186b)

**Comment by stuckie** [comment] 2024-09-18 08:37
Duplicate of #7654

**Closed by stuckie** 2024-09-18 08:37 UTC
Labels: ide-bug, project
