### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by LemonpieGBS** [YoYoGames/GameMaker-Bugs#7106] opened 2024-08-04 17:39 UTC
### Is your feature request related to a problem?

Using draw_text() function on GameMaker and trying to draw emojis doesn't work currently, I'd love a solution for it.

### Describe the solution you'd like

Just implement emoji support on the draw_text() functions.

### Describe alternatives you've considered

The only alternative would be using an external library with image on text support but that would require having every emoji as an image, so please do add emoji support :pray:

**Comment by L-Clouds** [comment] 2024-08-06 02:21
Duplicate of #6320, isn't it?

**Comment by stuckie** [comment] 2024-08-06 09:15
Duplicate of #6320

**Closed by stuckie** 2024-08-06 09:15 UTC
Labels: feature request
