### ISSUE TITLE
In-Game: "mip_markedonly" does not affect Separate Texture Page textures with the "generate mipmaps for separate texture pages" setting

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6800] opened 2024-07-20 10:31 UTC
### Description
If you use the "generate mipmaps for separate texture pages" setting, enabling `mip_markedonly` will still use the settings of the texture page that the texture has been assigned to.

Inheriting texture page settings is probably fine if the "generate for separate texture pages" setting is turned off, but if it's on that should take precedence.

### Steps To Reproduce
1. Run the sample project
2. Make sure the "generate mipmaps..." setting in Game Options is enabled (I don't know if those settings are uploaded with the bug reporter automatically)
2. Hit Space to cycle through mip states
3. Mipmaps are only enabled on the ground texture with `mip_on`
4. Assign the texture of spr_ground to tex_mip
5. Run the project again
6. Mipmaps are now enabled on that texture by default - or at least it attemps to, since that appears to be bugged too

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[515d8056-23fe-4a01-a306-ca94453bbfea](https://api.gamemaker.io/api/github/downloads/515d8056-23fe-4a01-a306-ca94453bbfea)

**Comment by JonnoRobson** [comment] 2024-07-30 15:50
I'm not entirely clear on the expected behaviour when following the steps to reproduce. When the "spr_ground" texture is assigned to the "tex_mip" group it does actually correctly use mipmaps when rendering in both the "marked on" and "on" modes. The visual difference between the two modes occurs because the normal map texture "spr_ground_normal" uses mipmapping in the "on" mode but does not in the "marked on" mode. Assigning both textures to the "tex_mip" group makes the visual match in both modes.

**Comment by DragoniteSpam** [comment] 2024-07-30 16:06
My argument is that if "generate mips for separate texture pages" is enabled, all sprites set to their own texture pages should count as "marked" even if they're not in the Default texture group.

**Closed** 2024-07-31 09:59 UTC
Labels: runner-bug, project

**Comment by DragoniteSpam** [comment] 2024-07-31 16:18
I suppose removing the setting would make the whole thing a non-issue...

**Comment by YYDan** [comment] 2024-08-01 13:28
@gurpreetsinghmatharoo One to review what the manual says about these options.

@JonnoRobson Did you file a FR to have the control removed? Does this need to be factored-in to any manual changes?

**Comment by JonnoRobson** [comment] 2024-08-01 14:22
@YYDan I've created a FR for removing the option here https://github.com/YoYoGames/GameMaker-Bugs/issues/7045. As I mention in the FR the option is currently documented in the Game Options documentation (https://manual.gamemaker.io/monthly/en/#t=Settings%2FGame_Options.htm) which should be removed alongside the option itself.
