### ISSUE TITLE
Project Save: GM crash when creating new projects into a OneDrive folder and the write is blocked

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#954] opened 2023-07-31 15:10 UTC
GM-6689

As you can see from the attached log file and ticket, this user is getting a reliable GM crash every time they attempt to create a new project inside their OneDrive folder OR they try to open that broken project later on.

The log file shows an error each time that the write is blocked and also that the File Watcher has been denied access, and then you can see GM exits. For example:

{quote}[22:02:17:617(14d2)] Trying to ProjectLoadSave.LoadProjectDialog
[22:02:19:376(14d2)] No Filename selected for 'Project|Load'
[22:02:24:688(14d2)] No GMX selected
[22:02:29:589(14d2)] --------------------------------------------------------------------------------
[22:02:29:604(14d2)] IDE Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\rmurl\OneDrive\Documents\GameMakerStudio2\SpeedRunner'.
File name: 'C:\Users\rmurl\OneDrive\Documents\GameMakerStudio2\SpeedRunner'
   at System.IO.FileSystem.GetAttributes(String fullPath)
   at YoYoStudio.Plugins.CorePlugins.StartScreen.NewProjectPanel.<CheckProjectLocation>b__91_0(Object _result, Object _userData)
   at YoYoStudio.FileAPI.FileSystem_Local.<>c__DisplayClass34_1.<GetDirectoryEntries>b__3()
   at YoYoStudio.FileAPI.FileRequest.ResultOperation()
   at YoYoStudio.Core.Utils.FileAPI.ThreadedAsyncQueue.DispatchCompletedRequests(Int32 _amount)
   at YoYoStudio.FileAPI.FileSystem_Local.Tick(Boolean _applicationIsBackground)
   at YoYoStudio.IDE.Tick()
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
[22:02:29:604(14d2)] --------------------------------------------------------------------------------{quote}

They are using the Steam IDE also, but no idea if that matters to repro.

*Steps:*
Have not reproduced so far.

**Comment by YYDan** [comment] 2024-03-04 17:28
Super-old report that we could not reproduce at the time, so Closing. We're planning a number of changes to avoid OneDrive causing problems, so hopefully that will take care of this one also if there are still problems on that machine.

https://github.com/YoYoGames/GameMaker-Bugs/issues/4372 for that planned change.

**Closed by YYDan** 2024-03-04 17:28 UTC
Labels: ide-bug, import
