### ISSUE TITLE
Feather: GM1041 error when using undefined to skip an optional argument in a built in function

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5835] opened 2024-05-12 18:41 UTC
### Description
I downloaded the survivors template game cuz why not, and found this feather error appearing many times:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/35bd69de-c252-4510-a803-0764550b0356)

### Steps To Reproduce
Call audio_play_sound, and pass undefined to skip one of the optional arguments.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[cf35da78-13b6-49c9-aad4-9ac086e2f6a5](https://api.gamemaker.io/api/github/downloads/cf35da78-13b6-49c9-aad4-9ac086e2f6a5)

**Comment by toby-yoyo** [comment] 2024-05-13 10:22
Duplicate of #5384.

**Closed by toby-yoyo** 2024-05-13 10:22 UTC
Labels: ide-bug, project
