### ISSUE TITLE
Right Mouse Button pressed acting like Left Mouse Button pressed

### ISSUE THREAD

**Issue by genetix307** [YoYoGames/GameMaker-Bugs#7517] opened 2024-09-04 15:00 UTC
### Description

Just installed the latest (August) build that released yesterday (9/4/2024) and noticed that for my mobile games where I have actions that depend on a "Double Tap" (which is resolved by a Right Mouse Button Clicked event) the event now seems to act like a standard "Left Button Pressed" instead. Have seen a few others in the forums reporting the same behavior when using the latest update. Rolling back to a previous update fixes this problem, seems to be introduced with the new patch.

### Expected Change

Right Mouse button event should resolve from Double Tap again

### Steps To Reproduce

1. Start GameMaker
2. Use Right Mouse Click event to handle a Double Tap
3.  Run game and attempt to Double Tap object that uses the Right Mouse Click event.
4. See the issue - Doesn't trigger the Right Mouse Click event, does trigger a Left Mouse Click event instead.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, Android

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by gnysek** [comment] 2024-09-05 09:50
Duplicate of #7506 ?

**Comment by iampremo** [comment] 2024-09-06 08:14
Duplicate of #7506

**Closed** 2024-09-06 08:16 UTC
Labels: runner-bug
