### ISSUE TITLE
Colors support for IDE's console

### ISSUE THREAD

**Issue by Gamer-XP** [YoYoGames/GameMaker-Bugs#4844] opened 2024-03-01 03:55 UTC
### Is your feature request related to a problem?

A pretty silly request, but nevertheless.

I'm using some external console apps to process the project before the build, and I color code info so it's easier to read. Thing is, it works fine when I test them normally, but GM's console ignores any info on colors.

I'm talking about stuff like this:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/76241557/4894132a-26c8-47f1-8382-207e0a8502af)

### Describe the solution you'd like

GM's console to actually take into account text and background colors if specified

### Additional context

Actually, this will be nice if show_debug_message will have color as one of its arguments or color tag support. So I can have error messages shown in red or something.

**Comment by YYDan** [comment] 2024-07-29 10:13
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3428

**Closed by YYDan** 2024-07-29 10:13 UTC
Labels: feature request
