### ISSUE TITLE
In-Game: audio_stop_sound() is not able to stop currently-playing sounds after calling room_goto()

### ISSUE THREAD

**Issue by mistletoe** [YoYoGames/GameMaker-Bugs#7347] opened 2024-08-19 17:37 UTC
### Description

I've encountered an unexpected behavior with audio_stop_sound(), and here's some code for a solution.

Here's some logic I've written in an Object's Step, that looks like it should Just Work:

	//Switches sounds when conditions met.
	if(global.theMuzakSound != audio_control_current_Music){
		show_debug_message("the Muzak Sound has changed!");
		audio_stop_sound(audio_control_current_Music);//Stops current music / ambient
		audio_control_current_Music = global.theMuzakSound;
	}

This doesn't work, when the Room is no longer the same as it was last frame. It appears that when Room transitions happen via room_goto(), audio that was already playing continues to play, but is no longer _detectable as playing_ for the audio_stop_sound() command.

At first I was really puzzled by this problem, because this code worked... sometimes, but not always. Then I realized it had something to do with switching Rooms (which my game does pretty rarely).

So, for anybody else trying to figure out how to do smoother sound transitions, etc., this code works:

	var needsToSilenceAll = (global.current_room != room);//Now checks a global, initialized at the Beginning of Time.
	//Switches sounds when conditions met.
	if(global.theMuzakSound != audio_control_current_Music){
		show_debug_message("the Muzak Sound has changed!");
		if(needsToSilenceAll) {
			audio_stop_all();
			global.current_room = room;//Resets this variable.
		} else {
			audio_stop_sound(audio_control_current_Music);//Stops current music / ambient
		}
		audio_control_current_Music = global.theMuzakSound;
	}

While I'm on this topic....

1. It'd really be very nice to have smooth audio cross-fade between Sound A and Sound B, rather than having to cut it off immediately, for smoother musical transitions in general. 

2. When a sound is played, it's controlled by the Channel; the only way to pull this off without getting deep into the weeds about a sound's playback position, etc., is to have many different Channels under active management. In my case, I'd need five, to manage two music and two ambient tracks and one for standard sound effects. 

Currently I have three, and that requires a fair chunk of management code.

Something like audio_cross_fade(looping_sound_A, looping_sound_B, time_in_milliseconds) would be nice.

3. Because of the multi-Channel situation, I cannot use streaming at all.

The limitation of streaming to only the default Channel, and lack of control over volume of a currently-playing sound, isn't ideal, basically. 

### Expected Change

audio_stop_sound() should still function as expected after room_goto()

### Steps To Reproduce

1. Write code the plays a really long sound, like music. Assign said sound id to a global.
2. Switch Rooms via room_goto(), and attempt to use audio_stop_sound() to kill that sound.
3. See the issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by toby-yoyo** [comment] 2024-10-01 16:23
The information in the description is not sufficient to determine whether or not there is an engine bug here. The code snippet does not show the entirety of the playback-related code (as no playback function is included), so without the whole picture we cannot recreate what you are seeing in your project.

I've attached a small example which successfully stops a sound after calling `room_goto`: [gmb-7347-x.zip](https://github.com/user-attachments/files/17212995/gmb-7347-x.zip)

I imagine this will look nothing like your project, but that is why we encourage submissions to include them.

I am going to close this particular issue as 'cannot reproduce', but if you resubmit the issue with your project then we will be very happy to take another look.

Finally, please submit any additional bugs or feature requests in their own issues, rather than compiling many bugs/requests into one issue.

**Closed by toby-yoyo** 2024-10-01 16:23 UTC
Labels: runner-bug
