### ISSUE TITLE
In-Game: array_sort() does not work if passed a global-scope function rather than a method

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#191] opened 2023-07-28 12:36 UTC
### Description

When using array_sort() with a custom method this sorts fine, but a function does not sort at all.

### GameMaker Version

2.3.2

### Steps

1. Start GameMaker and import [sortest-Dan.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13427213/sortest-Dan.zip)
2. Run the attached project for Windows
3. Notice the global function array is in the incorrect order, but the method array is fine
4. Run for HTML5 also and observe this is the same results

**Comment by Totobal5** [comment] 2023-11-21 11:35
i think this one is fixed already...because i use them in my game

**Comment by rwkay** [comment] 2023-11-21 11:36
This is already fixed... closing...

**Closed by rwkay** 2023-11-21 11:36 UTC
Labels: runner-bug, import

**Comment by YYDan** [comment] 2023-11-21 14:01
Not sure if this is the correct fix or not, but the _2022_.8 release notes say there is a fix for:

"In-Game: array_sort() calling custom sorting functions no longer causes errors in StructSort... project"

So this might have been fixed for quite a while. (The original bug report is certainly old enough, as it came from 2.3.2.)

**Comment by YYDan** [comment] 2023-11-21 14:02
I found the original sample project and cleaned it up, and confirmed the results for this specific issue show that it is fixed.

However, the original report was actually a 2-for-1 and the second part still remains an issue in 2023.1100 Betas, so I will open a separate issue for this.
