### ISSUE TITLE
In-Game: audio_stop_recording() fails to find non-zero indexed recording devices

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#38] opened 2023-07-28 12:28 UTC
GM-7893

This looks like a logic error, where the wrong index (the device index) is used to access the correct container (the recording info array) - so the recorder info is not found unless the the device index happens to match the index of the corresponding info, which will generally only happen with whatever the zero-indexed device is.

*Reproduction*
* Connect more than one audio input device to your machine.
* Open and run the example project [^GM-7893.yyz] .
* Select the non-zero indexed device (using the up/down arrow keys).
* Press '1' to start recording and say something to be recorded.
* Press '2' to stop recording - in the console output you should see the message "audio_stop_recording : recorder X is not currently recording"
* Press '3' to play whatever has been recorded and keep talking - you will begin to hear things you said after you pressed '2', showing that the input device did not close.

**Comment by toby-yoyo** [comment] 2024-11-06 16:28
This is not an engine bug, but one in the example project.

The project incorrectly passes the recorder index to `audio_stop_recording`. Instead, the recorder channel (which is returned by `audio_start_recording`) should be passed into that function.

With a minor tweak to implement that, the project seems to work as intended. Attached is the tweaked version: [gmb-38-x.zip](https://github.com/user-attachments/files/17650104/gmb-38-x.zip)

Closing as 'not a bug'.

**Closed by toby-yoyo** 2024-11-06 16:28 UTC
Labels: runner-bug, import
