### ISSUE TITLE
m_pAudioClient->GetMixFormat failed, using closest match

### ISSUE THREAD

**Issue by SaphiLC** [YoYoGames/GameMaker-Bugs#2563] opened 2023-12-20 18:33 UTC
### Description

Whenever i use `audio_start_recording` i get this message in the console `m_pAudioClient->GetMixFormat failed, using closest match`. If i let the game run for too long (10 minutes?) the game closes without giving any error, just this message in the output console:
`FAILED: Run Program Complete. For the details of why this build failed, please review the whole log above and also see your Compile Errors window.`

If you use `audio_stop_recording` and then `audio_start_recording` the message `m_pAudioClient->GetMixFormat failed, using closest match` appears again and again each time you start recording. Also while recording the CPU usage sky rockets (in the attached project i get over 30%, in my current project over 50%, and i need the recording as long as the game is open since is voice controlled).

[bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13730933/bug.zip)

### Expected Change

No error message in the output console, no random crashes and hopefully less cpu usage

### Steps To Reproduce

1. Start GameMaker
2. Add the `audio_start_recording` code
3. Check the Output
4. See the issue after the main loop starts (or whenever you initialize the code)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment] 2024-01-26 14:50
This seems to be a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2530. As a fix for that has now been merged, I'm going to close this one as not planned. Note that although the console message wasn't mentioned in that issue, it was still dealt with.

**Closed by toby-yoyo** 2024-01-26 14:50 UTC
Labels: runner-bug

**Comment by sihammill** [comment] 2024-01-31 15:00
Fix verified in IDE v2024.200.0.476  Runtime v2024.200.0.491

**Comment by SaphiLC** [comment] 2024-02-01 16:32
> Fix verified in IDE v2024.200.0.476 Runtime v2024.200.0.491

I have no idea how to get the IDE and Runtime numbers you are using, mine says 2023 and is not offering to update and the download in the website is v2023. Downloaded the beta IDE v2024.00.0.475 Runtime v2024.200.0.490 and that one still shows the message and still closes on its own... actually it closes faster than before and still uses around 30% CPU and up.

**Comment by toby-yoyo** [comment] 2024-02-01 16:45
@SaphiLC IDE v2024.200.0.476 Runtime v2024.200.0.491 is still an internal build. The message above just indicates that this issue has now gone through our internal QA process, and so the fix should appear in the next beta update, which will be either the version quoted or a higher one.

**Comment by SaphiLC** [comment] 2024-02-01 16:51
@toby-yoyo oh ok, sorry, I'll wait then. Thanks and sorry again ^^U
