### ISSUE TITLE
New function: debug_break_when(condition)

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#7122] opened 2024-08-05 10:07 UTC
### Is your feature request related to a problem?

A common pattern I encounter is needing to break in the debugger when a certain condition is true. This happens quite often when I have some instance or struct where there are tens or hundreds of them running, but I want to hit a breakpoint in the debugger only on one or a handful of them. Doing so is currently rather tedious due to GM debugger/compiler behavior.

Example:
```gml
if trace {
} <-- breakpoint here
some_more_code();
```
Unfortunately this fails completely:
![image](https://github.com/user-attachments/assets/013035df-26f2-42c0-8da2-7149aa7fbeb1)
Not only does the debugger break *outside* of the if block, but it breaks regardless of the condition :(

To solve this, we need a statement inside the if block that we can break on. Previously I had a macro DEBUG_BREAK set to `var f = "f"` just to have a quick way to add a line that the debugger would actually hit:
```gml
if (something_bad)
    DEBUG_BREAK
```

However in 2024.6+, the way the compiler handles macros results in the same failed behavior as above:
![image](https://github.com/user-attachments/assets/4b442e40-c3d8-4219-8a47-997f249a0f8b)

This means I no longer can use an easy to enter macro, I have to manually type in some valid statement in order to get the break point to hit.

### Describe the solution you'd like

At this point I think the best solution is a new function:
`debug_break_when(condition)`
The behavior of this function should be such that,when `condition == true`, the debugger will stop on that line. When not running in debug mode the statement can be compiled out.

This is similar to e.g. `Debugger.Break()` in C#

### Describe alternatives you've considered

It's already possible to make my own `debugger_break_when` by defining a function myself and setting a breakpoint inside it, but this has a few drawbacks:
1) Debugger stops inside that function and I have to manually navigate back to the place where it was called. This may seem like a small cost but it really adds up when you're trying to get through ~10 breakpoints trying to nail down some horrible bug.
2) The breakpoint is only within my project, which means collaborators or library consumers have to remember to go set the breakpoint for themselves.

**Comment by rwkay** [comment] 2024-08-05 10:10
How would you expect this to work???

Essentially the condition would need to be checked after every statement.... That would dramatically slow down execution.

A much better idea would be conditional breakpoints (i.e. insert a breakpoint and then add a condition to it) - when the breakpoint is hit then the condition is evaluated, that means the slow down only happens when the breakpoint is hit. Keeps everything much more local.

**Comment by shdwcat** [comment] 2024-08-05 10:21
@rwkay I would only expect it to check the condition when it hits that line!

```gml
doSomeStuff();
debug_break_when(something_bad); // only checked here!
doMoreStuff();
```

Conditional breakpoints are nice but I will say I barely use them in C#/Visual Studio because they're kind of a pain to set up, and have the same drawback #2 mentioned above that they're only local to the project. With libraries I may want to insert debug breakpoints via code so that developers using the library hit a breakpoint when something happens and can inspect the state of the system to see what went wrong.

**Comment by nesrocks** [comment] 2024-08-05 13:50
When using emulators for modding it is almost a universal feature to break for example when a certain memory address is written to. This would be very useful to have in gamemaker and could be translated to "break when this specific variable is written to".

**Comment by DragoniteSpam** [comment] 2024-08-05 16:10
for reference, here's a FR on conditional breakpoints #3349 and breakpoints for a specific variable #3243

**Comment by gnysek** [comment] 2024-08-07 10:50
While this looks interesting, Conditional Breakpoints are more common to my knowledge, and I would vote for them instead.

**Comment by YYDan** [comment] 2024-10-24 10:14
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3349 (or rather, this request has clearly been outvoted in favour of sticking with 3349 ;) )

**Closed by YYDan** 2024-10-24 10:14 UTC
Labels: feature request
