### ISSUE TITLE
CE2: String "text" will not be loaded with the right colours when first open

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6449] opened 2024-06-30 18:57 UTC
### Description
like title say the "String" format and colours will not be loaded on start correctly

### Steps To Reproduce
1) Open the attached project
2) uiMenu Draw gui line 10
3) Watch how the string colours are wrong.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[4a4e5e3e-d040-4a46-8e12-c06f8f826051](https://api.gamemaker.io/api/github/downloads/4a4e5e3e-d040-4a46-8e12-c06f8f826051)

**Comment by Totobal5** [comment] 2024-06-30 21:43
Other example

![GameMaker-Beta_QiyA9TUUYQ](https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/65cda923-a6ec-4b19-a608-5b46a7c67d48)

**Comment by zreedy** [comment] 2024-11-21 17:57
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6456

**Closed by zreedy** 2024-11-21 17:57 UTC
Labels: ide-bug, project
