### ISSUE TITLE
Particle: part_system_layer crash when passing a layer_id

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6019] opened 2024-05-28 21:35 UTC
### Description
part_system_layer does not accept layer_id but accept layer_name

### Steps To Reproduce
var lyr = layer_create(0);
part_system_layer(ref, lyr);

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[92febae4-e773-445d-b432-1040a6db3727](https://api.gamemaker.io/api/github/downloads/92febae4-e773-445d-b432-1040a6db3727)

**Comment by YYDan** [comment] 2024-05-29 08:37
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5728

**Comment by YYDan** [comment] 2024-05-29 08:38
Should be fixed in the 600 Betas already, btw.

**Closed by YYDan** 2024-05-29 08:37 UTC
Labels: ide-bug
