### ISSUE TITLE
Scribble fails to "recognize font" in latest Beta

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#8304] opened 2024-11-05 04:02 UTC
### Description
Title basically - importing Scribble into a blank project and trying to render text, in the latest Beta, renders a "Font xxx not recognised". This happens in all platforms.
 
Now I realize this is a third-party library, but it works perfectly both in monthly, LTS and the previous Beta, so it has to do with something that was changed in this last iteration.

### Steps To Reproduce
1. Create a blank project with a room and an object
2. Import Scribble (any version, but I used Scribble Deluxe 9.3.3)
3. Type on the object's Draw event:

scribble("Hi world").draw(room_width/2, room_height/2);

4. Run

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

### Which platform(s) are you seeing the problem on?
GX.games, HTML5, Windows

[84e53f2e-f222-444f-8272-ebba745f2cb0](https://api.gamemaker.io/api/github/downloads/84e53f2e-f222-444f-8272-ebba745f2cb0)

**Comment by gnysek** [comment] 2024-11-05 08:16
This seems to be not a bug. It's caused by using font name as string in GM, so preference "Automatically remove unused assets when compiling" removes that font from project.

There are two solutions:
a) disable this option in Game Options > Main
![Image](https://github.com/user-attachments/assets/77219485-58bf-4780-8bcb-ae61ac91cebe)

b) In Scribble, in script `__scribble_initialize` on line 76
https://github.com/JujuAdams/Scribble/blob/f864bc8d35375b7c91b22c3d61f00673a2d9313b/scripts/__scribble_system/__scribble_system.gml#L76
Replace:
```gml
__default_font: "scribble_fallback_font",
``` to: ```gml
__default_font: nameof(scribble_fallback_font),
```

**Comment by stuckie** [comment] 2024-11-05 09:50
Closing as above, thanks.

It's also already written in the release notes.
See also: #8198

**Closed by stuckie** 2024-11-05 09:50 UTC
Labels: runner-bug, project

**Comment by rwkay** [comment] 2024-11-05 10:10
> Scribble 9.3.4 attempts to detect when this asset stripping is enabled and will direct developers to disable it.

why not just fix it? this is a user requested feature and will be required for prefabs...

**Comment by JujuAdams** [comment] 2024-11-05 10:25
Because it is not a solveable issue my end. Users reference sprites and fonts in-line in strings and regularly reference these assets **only** in strings (and these strings may or may not be stored in external files). A "solution" would require the user to manually reference every single font and, more problematically, every single sprite that they intend to use with Scribble separately to the text content. This isn't reasonable and opens the door for human error.

I can think of further established practices in GameMaker that this feature will break. `asset_get_index($"spr_player_{jerseyColour}_walk")` and its ilk will now no longer work unless that sprite is specifically referenced without digging around in the options. For e.g. Swords Of Ditto this would be thousands of references, references that would've needed to be maintained and updated as we iterated on art assets.

This feature is too aggressive. There are situations - prefabs - where pruning at compile time is sensible but pruning the main project itself will cause many problems for games of a certain complexity. This undermines the value of the feature. There are good reasons to clean out a main project file from time to time but this should be done as a UI component where the developer and decide for themselves what is and isn't worth keeping.

**Comment by gnysek** [comment] 2024-11-05 10:39
There are cases, when it cannot be fixed in library, like:
`asset_get_index("asset_" + _variant);`
`tag_get_assets("my_selection")[0];`

Auto enabling it by default is bad IMO, I've wrote more about it in #8305 .

**Comment by rwkay** [comment] 2024-11-05 11:01
Unfortunately the compiler cannot know that you are using an asset without a reference - there are several ways you can get around that 

1. Add an array that lists all the assets that you are definitely wanting to keep i.e.  a simple `global.keepAssets = [ sprFoo, fntScribble1, fntScribble2 ]; `, would suffice
2. Use `nameof(fntScribble)` as that will keep the symbolic part of the name in place and the compiler will turn it into a string (we were looking forward when we added the `nameof` function.
3. We left in the option to switch this off - though switching it off will lead to larger executable sizes (and prefabs will still work, but you will get all the unused assets as well as the used ones)

One solution that I will experiment with is always enabling the feature - but when Using unused assets is off just setting all the assets of the main project as Used and leaving the prefabs as Unused (so the prefab assets will be stripped) - and only report the main project assets as being stripped (as that is all the user really cares about).

**Comment by Grisgram** [comment] 2024-11-05 11:13
> We don't want to add a tick box to every asset to say to "keep" it as that is an unnecessary burden on the UX and user to tick everything.

Understandable, but if gamemaker-assets are kept in the hierarchy in asset browser, you could send part of the responsibility to the user and allow him to "keep" an entire tree of assets. with one tick. not a thousand ticks.

we could organize our projects than in a way, with, say like "dynamics" as a root node in the project and just tick this one node as "keep". so everything below it, will stay.

**Comment by rwkay** [comment] 2024-11-05 16:09
Behaviour of Remove unused has been subtly changed see https://github.com/YoYoGames/GameMaker-Bugs/issues/8312
