### ISSUE TITLE
Code Editor: [Mac/Ubu IDE] Certain keyboard shortcuts do not work when using specific non-Roman language keyboard layouts

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#953] opened 2023-07-31 15:10 UTC
In the Mac and Ubuntu IDEs, certain keyboard shortcuts will not work in any Code Editor when using various non-Roman character keyboard layouts through Input Sources.

**Affected:**
Russian
Chinese
Japanese
Korean
Persian

### Steps To Reproduce

1. Open your Mac's System Preferences and open Keyboard > Input Sources (or the Ubuntu equivalent)
2. Add all of the languages listed above and check "Show input menu in menu bar"
3. Use the new icon in the top left of the menu bar to switch your keyboard layout to one of the newly-installed languages
4. Start GM and open/create any project
5. Create a new Note or Script
6. Type some letters and attempt to copy and paste them from the IME to the code editor
7. Observe the issue
Repro: 100%

**Comment by yerumaku** [comment] 2024-04-11 12:43
> This appears to affect all keyboard shortcuts expect for undo/redo.

Undo/redo also does not work.

**Comment by MahradH** [comment] 2024-04-11 12:48
Same on Ubuntu. When I open GameMaker and my language is not English (in my case Persian), no keyboard shortcut will work. changing the language to English will not fix the problem. I should close the GameMaker and reopen it while my keyboard language is English

**Comment by SmithTom6304** [comment] 2024-04-11 13:14
Will take a look at this one for the June release - thanks guys

**Comment by yerumaku** [comment] 2024-05-15 04:57
Is there any information about how difficult it is to fix this problem?

**Comment by yerumaku** [comment] 2024-08-02 09:41
@stuckie @SmithTom6304 
Will it be shifted to 2024.10?

**Comment by SmithTom6304** [comment] 2024-08-02 09:55
Sorry @yerumaku, didn't see your last comment.
It's still planned for 2024.8. Haven't had a chance to look into yet, so not sure how hard it'll be to fix.

**Comment by SmithTom6304** [comment] 2024-08-02 14:40
The problem stems from the fact that our hotkey system is based on KeyCode values, rather than ScanCode values.
ScanCode values can be thought of as the physical key on the keyboard, whereas KeyCode values are mapped to the layout of the keyboard (the language source).
For example, on a Russian keyboard the key `Ч` replaces the key `X` on an english keyboard. With the russian language source active pressing this key would produce a KeyCode of `Ч`, but still produce a Scancode of `X`.
Since our hotkeys are currently tied to the KeyCode values, it is impossible to press `Ctrl + X` (cut) on a russian keyboard as there is no `X` KeyCode on a russian keyboard.

Fixing this will require reworking our internal hotkey handling to instead use scancodes. This is fairly straightforward, but unfortunately is too much of a rework to go into 2024.8 and so will go into 2024.10 to give our QA team enough time to verify the change.

**Comment by yerumaku** [comment] 2024-08-02 15:34
Thank you for your reply, I hope that I will be able to see the results in Beta in September-October, and hopefully this fix will apply to LTS.

**Comment by yerumaku** [comment] 2024-08-21 21:55
@SmithTom6304 

Was there any information about whether replacing the methods of getting from the keyboard helps?

> until we know it works it is unlikely to get into LTS

As far as I understand, LTS is already close enough, but LTS is unpleasant to use on macOS/Linux due to input difficulties.

Is it possible to make some kind of wrapper over the input, and a flag to be able to switch the method of getting the key code?

**Comment by YYDan** [comment] 2024-09-10 09:12
There is no Ubuntu IDE LTS.

**Comment by SmithTom6304** [comment] 2024-09-30 11:26
No new information I'm afraid - other work has taken a priority.

**Comment by Emc1923** [comment] 2024-12-06 11:04
Unable to reproduce this issue on Windows as of  IDE v2024.1100.0.703  Runtime v2024.1100.0.719

**Comment by mgeddesGM** [comment] 2024-12-06 11:05
unable to reproduce  on windows  IDE v2024.1100.0.703  Runtime v2024.1100.0.719, additionally i used an external keyboard

**Comment by SmithTom6304** [comment] 2024-12-09 09:09
@yerumaku I'd asked QA to take a look on Windows as well.
I have a fix that should be ready to go in soon. The fix won't be in v2024.11, but will be in the v2024.13 betas

**Comment by SmithTom6304** [comment] 2024-12-09 15:27
Fix has now gone in, and should appear in the first 2024.13 beta.

**Closed as completed by SmithTom6304** 2024-12-09 15:27 UTC
Labels: ide-bug, import

**Comment by Emc1923** [comment] 2025-01-07 12:26
Verified in  IDE v2024.1300.0.714  Runtime v2024.1300.0.727 for Mac/Ubuntu.

**Comment by SmithTom6304** [comment] 2025-02-12 11:08
@yerumaku glad to hear it! Just to let you know, I've made an additional change to now display the actual key, rather than the scancode. This means that for example on Russian keyboards, `Cut` will now display as `Ctrl + ч`. The displayed key will change as the keyboard layout changes.

Functionally it all works the same on the backend, so this shouldn't affect using hotkeys at all. It should just make it clearer as to what key you need to press for which hotkey. Let us know if you have any problems!
