### ISSUE TITLE
In-Game: [Ubuntu] A particular combination of sound assets in the project causes the game to segfault immediately upon launch

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#201] opened 2023-07-28 12:36 UTC
GM-2234

Bug Type: Bug with in-game functionality
Ide Version: 23.1.1.397
Runtime Version: 23.1.1.377
Platforms: Ubuntu
Components: Amazon Fire,In-Game Crash,Ubuntu

Description: When building the project on Ubuntu and attempting to run, the game compiles successfully however segfaults immediately upon launch. Removing any of the 4 sound assets in the sample project provided should cause the game to launch and run successfully. It only segfaults if all 4 are included at the same time.

This crash does not occur when running on Windows

System information: Linux version 5.11.0-36-generic (buildd@lcy01-amd64-004) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) [#40|https://yoyogames.zendesk.com/agent/tickets/40]~20.04.1-Ubuntu SMP Sat Sep 18 02:14:19 UTC 2021

**Comment by toby-yoyo** [comment] 2024-11-08 14:48
I cannot reproduce this on Beta IDE v2024.1100.0.674 Beta Runtime v2024.1100.0.700.

Here is an updated version of the example project which not only runs, but plays each of the 4 sound assets mentioned in the description: https://drive.google.com/file/d/1EobzKy49j2OnPKJOVhlPyVb_PSC_TeVn/view?usp=sharing

It seems like another report from the same user ([found here](https://bugs.opera.com/browse/GM-2508)) may have pointed to the cause of the issue here. Given that issue was verified as being fixed and that this one can no longer be reproduced, I am considering this bug as having already been fixed.

Closing as 'cannot reproduce'.

**Closed as not planned by toby-yoyo** 2024-11-08 14:48 UTC
Labels: gms2-bug, import
