### ISSUE TITLE
the debug overlay says fps where it should say fps_real

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#5461] opened 2024-04-12 13:54 UTC
### Description

![Capture](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/47b2e816-dc34-4a62-949a-f212ed1c45a5)

this should say ``fps_real`` not ``fps`` for clarity all that.

### Expected Change

fps should say fps_real

### Steps To Reproduce

1. Start GameMaker
2. turn on the debug overlay
3. notice it says fps instead of fps_real
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2024-04-15 09:06
Closing as not a bug - this is the fps at that time.

**Closed by stuckie** 2024-04-15 09:06 UTC
Labels: runner-bug
