### ISSUE TITLE
Error thrown in a `with` statement prevents `catch` exception declaration

### ISSUE THREAD

**Issue by Mtax-Development** [YoYoGames/GameMaker-Bugs#7422] opened 2024-08-25 13:19 UTC
### Description

Consider the following code:
```
try
{
	with ({})
	{
		show_error("", true);
	}
}
catch (_exception)
{
	show_message(_exception);
}
```

It seems that using the `with` exception will prevent `_exception` from being accessible and a `catch` statement actually is a cause of a crash. Reading `_exception` in this case will result in a `variable not set before reading` error. This error can be then caught by nesting `try` statements, although in a project I attached, it just causes a silent crash.

[with-exception crash.zip](https://github.com/user-attachments/files/16740368/with-exception.crash.zip)

### Steps To Reproduce

​

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment] 2024-08-26 09:04
Fixed already in Betas:

![image](https://github.com/user-attachments/assets/fff2f587-f6d5-41be-9771-89a33dc1aabb)

Beta IDE v2024.800.0.613  Runtime v2024.800.0.636

**Comment by YYDan** [comment] 2024-08-26 09:04
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6190

**Closed by YYDan** 2024-08-26 09:04 UTC
Labels: runner-bug
