### ISSUE TITLE
Latest Monthly fails to import older 2.3.x packages

### ISSUE THREAD

**Issue by nkrapivin** [YoYoGames/GameMaker-Bugs#4312] opened 2024-01-11 13:39 UTC
### Description
A user has reported that they are having trouble importing my NekoPresence extension.
The latest build of that extension was made when GameMaker introduced macOS M1 support, so I think it's 2.3.7, maybe 2.3.5? Not sure.
I can import that yymps on LTS just fine, but on Monthly it produces a corrupted extension with missing files (see attached project, .yy is missing name fields)
I also attached the yymps so you can try re-importing it yourself, it's a Marketplace Signed version made a long time ago (still works perfectly).

### Steps To Reproduce
1. Run GameMaker Monthly
2. Open attached project
3. Observe that the extension is corrupt
4. Run GameMaker LTS
5. Import the attached signed yymps in an empty project
6. Observe that it imports perfectly

[97912802-bc06-4ab9-99a2-b8c870a456c6](https://api.gamemaker.io/api/github/downloads/97912802-bc06-4ab9-99a2-b8c870a456c6)

**Comment by stuckie** [comment] 2024-01-12 10:15
Duplicate of #2649

**Closed by stuckie** 2024-01-12 10:15 UTC
Labels: ide-bug
