### ISSUE TITLE
"Search & Replace" - pressing "enter" does nothing while window is docked(?) to the side

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4972] opened 2024-03-11 13:13 UTC
### Description

Docking (not sure if that's the correct term) the search & replace window to the side of the screen and pressing "enter" will not "find all" - instead, nothing happens. 

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/40671879/2a960c4e-df77-439f-aa89-e62853a58b04)

### Steps To Reproduce

1. Start GameMaker and open a project
2. Press Ctrl+Shift+F to open "find & replace"
3. Drag the window to the right side of the screen 
4. Type text into search and press "enter"
5. See the issue - no search is performed

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2024-03-12 15:12
Closing as duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/854

**Closed by stuckie** 2024-03-12 15:12 UTC
Labels: ide-bug
