### ISSUE TITLE
CE2: Static function folding no work

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5959] opened 2024-05-24 22:40 UTC
### Description
In a proyect the folder function simply just not work.

### Steps To Reproduce
1) Open the attached project
2) Open script Lens and go to line 830.
3) Try to fold the static function "toString"
4) Cry.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[96bd75da-da85-45b9-b633-c31c1eade7fc](https://api.gamemaker.io/api/github/downloads/96bd75da-da85-45b9-b633-c31c1eade7fc)

**Comment by stuckie** [comment] 2024-07-26 14:42
Duplicate of #5549

**Closed by stuckie** 2024-07-26 14:42 UTC
Labels: ide-bug, project
