### ISSUE TITLE
Debugger: F5 and F6 keys do nothing if the game is not running at that time

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#8095] opened 2024-10-23 05:36 UTC
### Description

Continue and Restart take presidence when the game is running,
![image](https://github.com/user-attachments/assets/6d9d9465-8a25-4113-b7de-a070f6d78210)
However when ever the runner is no longer active the F5 and F6 keys still do nothing.

This has been bothering me for months and finally felt it was annoying enough to mention something. Ideally I don't actually care for those keybinds taking presidency over a feature since (at least) gm6. But if they must remain, that at the least they shouldn't consume input when not available.

### Expected Change

Assuming the runner/game is not active, pressing F5 or F6 while the debugger window has focus it should still allow for you to run your project. This generally should be true for any keybind where the option is greyed out, the input of the keybind should not be consumed.

### Steps To Reproduce

1. Start GameMaker
2. Run debug tool
3. Close game
4. return to IDE, and press F5 or F6
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-10-23 08:46
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5330

**Closed by YYDan** 2024-10-23 08:46 UTC
Labels: ide-bug

**Comment by tinkerer-red** [comment] 2025-03-13 20:10
This is not the same issue as redefining keys, even if the same keybinds are bound to multiple functions, if the ability to activate this feature is disabled it should not consume the input, and instead should waterfall down to the next input.
in the given event:
![Image](https://github.com/user-attachments/assets/114b0b32-75ca-4ed2-b6b2-435d997712cc)
Pressing F5 or F6, the key inputs will get consumed by the `Continue` and `Reset game` of the debugger, despite that not actively being possible since the game is not running in the first place. Those inputs shouldn't be captured but instead allowed to pass on down to the next operation. in this case `Run` or `Debug`

Would like for this ticket to be reopened as is is not specific to the key configuration but the input consumption.

**Comment by tinkerer-red** [comment] 2025-12-06 10:47
How can I edit the supplied files to simply remove this until it's fixed?
