### ISSUE TITLE
Add Kotlin and Swift support for Android and iOS extensions

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4258] opened 2023-06-06 14:35 UTC
Ticket #207256
Feature Type: feat_change_ide
Description: Currently Android extensions on GMS only supports Java files, and iOS extensions only works with obj-c files. And both Google and Apple named their main language for development is Kotlin and Swift respectively.
Benefit: Currently more and more Android development are switching to Kotlin and staying on Java gives a feel of usage of an outdated technology. While technically there is no difference if you are use Java or Kotlin for Android but more and more examples and libraries are switched to Kotlin and over time Java becoming less relevant with respect to android development.

And even worse situation with Objective-C on iOS (and MacOS).

While creating extensions for Android an iOS when researching a problem I found that on iOS any code examples and snippets in 90% (approximately) cases will be in Swift so usually I need to rewrite code I found into Objective-C. For Android by feeling is around a half (more or less) on code found on the internet already in Kotlin and its percentage is only growing.
Link:

**Comment by YYDan** [comment] 2024-10-21 14:52
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/4413

**Closed by YYDan** 2024-10-21 14:52 UTC
Labels: feature request, import
