### ISSUE TITLE
CE2: mouse wheel scroll setting

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6218] opened 2024-06-11 15:35 UTC
### Is your feature request related to a problem?

CE1 scrolls 2 lines per scroll.
CE2 scrolls 5 lines per scroll.

There should be a setting to change number of lines when scrolling (by mouse wheel and page up/down).

### Describe the solution you'd like

Add new setting in preferences.

### Describe alternatives you've considered

Set it same as in CE1.

**Comment by KormexGit** [comment] 2024-06-11 16:21
Some videos showing the difference for reference, CE1:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/adae681c-ab92-434f-b51e-74e9b3fcfa5b

CE2:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/aa92f32b-e022-4c1a-8616-df7d97e55fb6

**Comment by YYDan** [comment] 2024-06-11 16:30
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5303

**Closed by YYDan** 2024-06-11 16:30 UTC
Labels: feature request

**Comment by YYDan** [comment] 2024-06-11 16:31
But I did add your videos to the other report - ta ;)
