### ISSUE TITLE
In-Game: Reusing a macro name as the name of an instance variable does not set the variable correctly in 2023.11

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2295] opened 2023-11-26 08:05 UTC
### Description
In 2023.8, doing something like putting a macro as the name of a variable in the variable definitions window caused a compile error. In 2023.11, it does not, but also does not set the variable properly, as self.macro_name still shows whatever the macro is for.
If it's not intended for this to work, then it should go back to giving an error. If it's intended for this to work, then it should set the value properly.

### Steps To Reproduce
#macro debug show_debug_message

Add a variable to variable definitions called debug, with a value of 0.

In 2023.8, this will give a compile error. In 2023.11, this will compile, but doing show_message(self.debug); on the object will show the value of show_debug_message, not 0. This can cause various undesirable and difficult to debug results.

[dc91d5ec-dd49-403b-9ca0-383fc94ebdf1](https://api.gamemaker.io/api/github/downloads/dc91d5ec-dd49-403b-9ca0-383fc94ebdf1)

**Comment by rwkay** [comment] 2024-01-25 15:08
Unable to reproduce on current HEAD of 2024.2 - several issues around `self` and macros have been fixed in last few days.

**Closed by rwkay** 2024-01-25 15:08 UTC
Labels: build-bug, project

**Comment by mgeddesGM** [comment] 2024-01-30 16:48
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
