### ISSUE TITLE
Prefabs: Assigning a prefab sprite to an object and then uninstalling the prefab causes unhandled exceptions and project load failures

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8333] opened 2024-11-07 20:36 UTC
### Description
If you uninstall a prefab after assigning a sprite from it to an object, compiling will give an unhandled exception:
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
```

If you then reload the project, you will get a project load failure and be unable to open the project to remove the prefab sprite assignment. The only way to un-brick the project is to reinstall the prefab before opening it. If for some reason you were unable to reinstall the prefab, the project would be impossible to open without manually editing the files.

### Steps To Reproduce
1. Install any prefab with a sprite
2. Assign that sprite to an object
3. Uninstall the prefab
4. Try to compile. It will give an unhandled exception
5. Try to reload the project. It will give a project load failure

The same results will also happen when placing a sprite on an asset layer instead of assigning it to an object

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.674 Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[3f395ec7-f2ba-443b-b830-dde99343eb5d](https://api.gamemaker.io/api/github/downloads/3f395ec7-f2ba-443b-b830-dde99343eb5d)

**Comment by Emc1923** [comment] 2024-11-08 08:43
Dupe of https://github.com/YoYoGames/GameMaker-Bugs/issues/8339

**Closed** 2024-11-08 09:48 UTC
Labels: ide-bug, project
