### ISSUE TITLE
Running Exported Live Wallpapers in companion app not loading

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#6405] opened 2024-06-26 11:11 UTC
### Description
After creating or uploading Live Wallpaper mod to GX.Create the windows standalone version of the live wallpaper app  v0.0.37 will not load the wallpaper created. 

Happens to projects exported from both green and beta.

### Steps To Reproduce
Beta IDE v2024.600.0.583  Runtime v2024.600.0.607

Create blank like wallpaper from default template.
Upload onto gx.create
Download the live wallpaper
Run through the standalone desktop live wallpaper app
(Use systray -> Wallpapers ->  Live -> Wallpaper Name to set)
Wallpaper will not load

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.583 Runtime v2024.600.0.607

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
GX.games, Windows

[dc8fbc77-bf9e-48e2-8cde-2ebd0471e4d9](https://api.gamemaker.io/api/github/downloads/dc8fbc77-bf9e-48e2-8cde-2ebd0471e4d9)

**Comment by Emc1923** [comment] 2024-06-26 13:15
Confirmed issue with the Live Wallpaper companion app v0.0.37. Tested with a previous version of the app and the issue is not present.

**Comment by rwkay** [comment] 2024-07-03 13:20
Fixed in LWCS (Live Wallpaper companion app v0.0.41) - code singing certificate hash needed updated.

**Closed by rwkay** 2024-07-03 13:20 UTC
Labels: build-bug, project
