### ISSUE TITLE
Direct script asset references show up as numbers

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#4515] opened 2024-01-26 12:23 UTC
### Description
When script asset is referred to in the code by its identifier, it's evaluated as a number while it should be a script handle instead. Functions are correctly evaluated as their handles.

### Steps To Reproduce
1. Create a blank project
2. Add a Script1 script
3. Add `show_debug_message(Script1); show_debug_message(is_handle(Script1);` to the script.
4. Run the game and check the output.

Expected output is something like "ref script 100000" and "1" but received output is "100000" and "0" instead.

[da2a8181-ce34-4b06-b5c4-9f4a1685ec69](https://api.gamemaker.io/api/github/downloads/da2a8181-ce34-4b06-b5c4-9f4a1685ec69)

**Comment by rwkay** [comment] 2024-01-29 12:35
Unable to reproduce in 2024.2 HEAD - I think an earlier fix was done for this.

**Comment by scott-dunbar** [comment] 2024-01-31 13:52
Issue still occurs as described in  IDE v2024.200.0.476  Runtime v2024.200.0.491 - this was built yesterday morning from 2024.2 branch.

[scriptref.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14112479/scriptref.zip)

**Comment by rwkay** [comment] 2024-02-01 16:40
Fixed in 2024.2 
Ensure top level scripts are turned into script refs.

* this was mostly working - it was just the global scripts themselves that were not getting turned into refs.
* Scott's example is not correct either as he is calling the script function `myfunc` rather than referring to it (so it is printing the return value to that (which is `undefined`)

**Closed by rwkay** 2024-02-01 16:40 UTC
Labels: runner-bug

**Comment by mgeddesGM** [comment] 2024-02-05 14:05
verified as of  IDE v2024.200.0.483  Runtime v2024.200.0.499
