### ISSUE TITLE
In-Game: [HTML5] Tilemap precise collisions are not working in 2024.8.1

### ISSUE THREAD

**Issue by UnlimitedTrees** [YoYoGames/GameMaker-Bugs#8364] opened 2024-11-10 20:52 UTC
### Description

Precise tilemap collision just does not work at all in HTML5, with the whole tile being completely solid (even if it's completely empty). This has happened with multiple different projects that use tilemap collisions, including [DarkD04's Harmony Framework](https://github.com/DarkD04/Harmony-Framework/commits/main/)
![Image](https://github.com/user-attachments/assets/5ef93e9d-2b75-49c6-a045-b057dc824775)

https://api.gamemaker.io/api/github/downloads/35d31996-93a4-4fb1-97ba-1998e3133d71

### Expected Change

For precise collisions to work with tilemaps in HTML5

### Steps To Reproduce

1. Start GameMaker
2. Create a tileset with its collision set to '**Precise (Slow)**'
3. Use any collision check on the tileset, such as **collision_point** and **collision_line**

Alternatively, you can see this in the [Harmony Framework](https://github.com/DarkD04/Harmony-Framework/commits/main/), which I'm using for a project. There's also a separate issue where the game crashes on startup in HTML5 which I don't understand, but this can be ignored by going to **obj_global**'s 'Game Start' code and changing the '**room_goto_next()**' line to '**room_goto(rm_arboreal_agate1)**'

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

HTML5

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment] 2024-11-11 10:44
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/8264

**Closed by jackerley** 2024-11-11 10:44 UTC
Labels: runner-bug
