### ISSUE TITLE
Code Editor 2: GameMaker crash when typing the character 7 into a Note using a Cyrillic font

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#6439] opened 2024-06-28 19:35 UTC
### Description
I have attached a screen recording, a broken project and a UI log (everything is in the archive).

There is a problem when rendering the source text of a note in the case when something is entered that seems incorrect to the parser or renderer. [Specifically,] if there is a digit 7 at the beginning of this line.

Environment: Macbook M3.

Video included in this attachment (which differs from the one lower): [68f88179-a6c0-430b-8d56-eac083d2eb8d](https://api.gamemaker.io/api/github/downloads/68f88179-a6c0-430b-8d56-eac083d2eb8d)

### Steps To Reproduce

1. Start GameMaker using a Cyrillic font as the IDE font
2. Open Note (as shown in video).
3. Select first word on 58 line.
4. Press number 7 (broken view).
5. Place cursor after first word on 58 line.
6. Press number 7 (crash IDE).

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Mac 14.5

[82de4e44-410e-49e8-8b2e-8956354be872](https://api.gamemaker.io/api/github/downloads/82de4e44-410e-49e8-8b2e-8956354be872)

**Comment by zreedy** [comment] 2024-06-28 20:50
Unable to reproduce. I strongly suspect this was fixed internally with a related tab spacing calculation.

**Comment by yerumaku** [comment] 2024-06-29 11:24
Screen video and UI log:
- #6444

**Comment by YYDan** [comment] 2024-07-01 08:09
Have combined all the info into the one issue, so I'll remove the duplicate bug report - you are free to attach videos (and other files) in your comments, btw.

**Comment by zreedy** [comment] 2024-07-01 21:35
What font specifically is being used?

**Comment by yerumaku** [comment] 2024-07-03 03:53
> What font specifically is being used?

### JetBrainsMono.ttf
 _from https://www.jetbrains.com/lp/mono/_
Size 10
<details><summary>screens</summary>

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/21119896/e6ee3f16-acbb-4f73-b59a-2eb0f083bd34)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/21119896/9a517acd-7db4-4732-9b71-4cdb9a4d3ad4)
</details>

**Comment by zreedy** [comment] 2024-07-04 20:45
Unable to reproduce. The `ui.log` seems to indicate that this issue has been fixed as apart of the tab bugs which are fixed internally but not in a public beta. Closing for now, please reopen if you find this is reproducible in the first .800 beta.

**Closed by zreedy** 2024-07-04 20:45 UTC
Labels: project, crash
