### ISSUE TITLE
Collapsible Switch Cases

### ISSUE THREAD

**Issue by PureNukage** [YoYoGames/GameMaker-Bugs#6114] opened 2024-06-04 13:25 UTC
### Is your feature request related to a problem?

Not really

### Describe the solution you'd like

For there to be the collapse button (+/-) in the Code Editor for Switch Cases similar to function blocks and Regions.

### Describe alternatives you've considered

Replacing a comment above the Case with a Region and an End Region after the Case's break.

**Comment by YYDan** [comment] 2024-06-04 13:55
Yup, as you have seen yourself, this is already requested and part of the backlog. As that other issue shows, it's very easy already to achieve _the end result_ you want - just not without typing extra braces yourself ;)

**Comment by YYDan** [comment] 2024-06-04 13:56
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2781

**Closed by YYDan** 2024-06-04 13:56 UTC
Labels: feature request
