### ISSUE TITLE
Follow-up to #5375 crash after "Clean"

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#5376] opened 2024-04-07 16:11 UTC
### Description
Hey again,

maybe the second dump helps.
This crash happened after doing a "Clean" and "Clean Graphics" on all project configurations, where i got the message in the log
```
 Texture group is missing for sprite... resetting to "default"
```

I was in good hope, clicked a sprite... and crash!

Hope you can find that, the project is completely damaged, can't do changes in here (this is a production project)

I also can't create a "new " project and move my sources over there as i also would have to transfer the sprites to the new project... and this does not work.
I am caught in a deadlock.
Will try to go back in git history until i find a point where the project is usable, but still i have no idea how to import the needed sprites but i will tag the version until you have a fix, so I can try to redo the import from that point.

cheers, gris

## Update
On my third attempt, I could get it to work in a completely new project, with a new name, and sprites imported piece-by-piece (texture group by texture group).

This leaves me with 2 possible sources of the bug:
- Either GMS struggles when importing sprites from multiple texture groups in a single package
- Something in the cache files on my machine, which does not get touched by the "Clean" commands in the Build-Menu is in an unrecoverable state.

I will delete all caches and all temp files from gms now, except the runtimes.
Then i will try to rename the (new) project back to its original name.

## Update 2
as soon as i clicked "save" here in the first update, GMS crashed in the new project with the same error. Nope, this project is dead. Currently it is impossible to transfer sprites between projects when your project has more than 1 texture group.

## Update 3
Found a workaround:
- In the asset browser, single-click one of the damaged sprites (a double click makes gms crash)
- Then go to the "Inspector" and select the desired texture group but only in default configuration
- The inspector seems to "heal", whatever is damaged.
- I can now edit my texture groups again but only in default configuration
 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/19487451/df77f09a-abc4-460b-8ded-3bcea0e14643)
These are the configs in the project.
All configs compile and run fine, but i may only EDIT when I set GMS to "default". all other configs crash GMS when i try to open/edit a sprite... So the project is kind-of-half-repaired...

Please look into this.

Maybe the inpector-thing helps finding the root cause!

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[1753c4ee-6a8d-4ed5-916c-fe582b531bdf](https://api.gamemaker.io/api/github/downloads/1753c4ee-6a8d-4ed5-916c-fe582b531bdf)

**Comment by stuckie** [comment] 2024-04-10 11:08
Closing as duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5333 as per comments in #4955

**Closed by stuckie** 2024-04-10 11:08 UTC
Labels: crash, dump
