### ISSUE TITLE
Clicking on any sound asset crashes the IDE

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4600] opened 2024-02-02 18:22 UTC
### Description
I'm on a new mac set up, I've followed the setup guide, installed Xcode.

Not sure if it's related but I can't properly build either. Some sound assets are not found (will do a separate bug report for it)

### Steps To Reproduce
Just click on any sound asset

[09c11c47-9e58-4233-914c-fa6ecc21603c](https://api.gamemaker.io/api/github/downloads/09c11c47-9e58-4233-914c-fa6ecc21603c)

**Comment by toby-yoyo** [comment] 2024-02-02 19:23
This may be a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2592 - do you have Rosetta installed?

**Comment by patchuby** [comment] 2024-02-02 19:37
Ah might be, I had read on release notes that Rosetta wasn't required anymore. I am on the M1 chip,

**Comment by YYDan** [comment] 2024-08-29 14:41
Ahh, the Rosetta change got reverted very quickly and so it's still required in the version of GM you were using at the time you made this report (apologies for any confusion with the old release notes). Closing as Duplicate, as given above.

**Closed by YYDan** 2024-08-29 14:41 UTC
Labels: project, crash
