### ISSUE TITLE
Spine animation with disabled Slots import error

### ISSUE THREAD

**Issue by mbeytekin** [YoYoGames/GameMaker-Bugs#5386] opened 2024-04-08 10:35 UTC
### Description

If you export all images (regions) in the slots of your Spine file as disabled, it gives an unsupported version error because in the Gamemaker sprite window, it can't find anything to show by default. Let me explain; you've prepared an Spine animation , but you don't want any image in any slot to be visible/enabled by default. You want to make the necessary slots visible/enabled in animations. Unfortunately, Gamemaker doesn't accept this json. However, if you load the same file in real-time, it doesn't give an error. My guess is that the sprite editor can't find an image to display.This is very confusing, and I spent about 1-2 hours trying to solve it. Additionally, I have a file with a lot of animations, and for Gamemaker to accept it, I either have to activate an invisible(transparent) image by default or make each slot that appears by default in each animation invisible one by one.

### Expected Change

In cases where all slots are disabled, it can display an empty sprite.

### Steps To Reproduce

1. Start GameMaker
2. Create new sprite
3. Import a Sprite JSON file where all slots are default disabled.
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2024-04-09 08:36
Duplicate of #1283

**Closed by stuckie** 2024-04-09 08:36 UTC
Labels: ide-bug
