### ISSUE TITLE
Could not start projects and could not log in

### ISSUE THREAD

**Issue by Freeflip** [YoYoGames/GameMaker-Bugs#5732] opened 2024-05-03 07:49 UTC
### Description

I just updated to the new version and now I can no longer log-in for lack of internet (in fact there is and antivirus and firewall DO NOT block GM).

And I can’t start any projects, either in the old address or moving them to the new address.

I need urgent help as GM does not allow me to work.

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-05-03 08:32
There is no log file here, so we cannot give detailed advice - however, I suspect that the "projects" side of your issue is a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5719

In terms of not being able to log in, we would need the log file in order to know if there is an error there.

**Comment by Freeflip** [comment] 2024-05-03 09:28
I attach the file

Il giorno ven 3 mag 2024 alle ore 10:32 Daniel Cleaton <
***@***.***> ha scritto:

**Comment by Freeflip** [comment] 2024-05-03 09:34
Anyway it’s not the same error of #5719
<https://github.com/YoYoGames/GameMaker-Bugs/issues/5719>
Is different.
I can open all the projects BUT I don’t go to run time

Il giorno ven 3 mag 2024 alle ore 11:28 Santiago Calzolari <
***@***.***> ha scritto:

**Comment by Freeflip** [comment] 2024-05-07 09:00
I just installed the new runtime and now everything works perfectly.

Thanks

Il giorno mar 7 mag 2024 alle ore 10:39 Steven Campbell <
***@***.***> ha scritto:

**Comment by stuckie** [comment] 2024-05-08 08:35
Thanks for getting back to us.
Marking as resolved.

**Closed by stuckie** 2024-05-08 08:35 UTC
Labels: build-bug
