### ISSUE TITLE
network_send_raw can only be used once per step per socket.

### ISSUE THREAD

**Issue by TheoryGeorgiou** [YoYoGames/GameMaker-Bugs#2655] opened 2024-01-05 20:29 UTC
### Description

If you try to use this function more than once per step, it returns the packet size (signifying success) but it does not send.

either this is the case or the async network event cannot process more than tcp incoming packet per step per socket, because this event is async I don't think this is the case but that the packet is never sent in the first place.

I've not tested this with the non raw networking functions but I suspect it's bugged as well.

### Steps To Reproduce

1. Start GameMaker
2. setup raw networking
3. try to send more than one network_send_raw() function from client to server in a single step.
4. See the issue
[contact-help-file.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13846303/contact-help-file.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by sukus21** [comment] 2024-01-07 16:51
This is not a bug, this is how the raw connections work.
When sending packets in non-raw format, each packet has a header, signifying that this is a GameMaker packet, and contains the length of the packet. This header is not appended when using `network_send_raw`.

The error is on the receiving end. When you receive a packet, check the length/contents of it, and you'll see that the missing packets have been appended to it.
When using raw packets, it is your responsibility to seperate them. GameMaker just receives a datastream, and has no idea what data belongs to which packet.

Hope this helps!

**Comment by TheoryGeorgiou** [comment] 2024-01-07 22:32
Thank you, did not realize it was combining the packets. I will refactor the project to use to non raw and see how it goes.

**Comment by stuckie** [comment] 2024-01-08 10:24
Passing to documentation to ensure it's mentioned in the manual.

**Comment by gurpreetsinghmatharoo** [comment] 2024-01-09 04:57
It's not mentioned in the manual currently. Will be added.

**Comment by gurpreetsinghmatharoo** [comment] 2024-01-16 06:40
Fixed, closing

**Closed by gurpreetsinghmatharoo** 2024-01-16 06:40 UTC
Labels: docs-bug
