### ISSUE TITLE
Allow method to create Broadcast Messages via code

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3975] opened 2023-06-06 14:58 UTC
Ticket #196782
Feature Type: feat_addition_ingame
Description: Creating a function like broadcast_message(message); that can be called via script that would essentially execute all defined broadcast message events with the message specified, as if it was reached in a sprite or sequence.
Benefit: This would expand the usefulness of the Broadcast Message system already present in Gamemaker and would make setting up systems like event listeners and certain state machines less of a hassle.
Link:

**Comment by YYDan** [comment] 2024-09-02 08:27
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6153

**Comment by YYDan** [comment] 2024-09-02 08:28
"Duplicate", as obvs this is much older, but lacks the detail of the newer issue template ;)

**Closed** 2024-09-02 08:28 UTC
Labels: feature request, import
