### ISSUE TITLE
Middle click on functions doesn't open the correct URL

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#2674] opened 2024-01-08 08:55 UTC
### Description
No function I tried to middle click opened the documentation at the right spot. Instead it brings me here:

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FPaths%2FPath_Manipulation%2Fpath_add_point.htm

In the browser I see the welcome page.

### Steps To Reproduce
1. Middle click any GM function
2. Browser brings you to welcome page of the docs.

[6bcb09ec-fabd-4403-87a1-4f5c7d579030](https://api.gamemaker.io/api/github/downloads/6bcb09ec-fabd-4403-87a1-4f5c7d579030)

**Comment by stuckie** [comment] 2024-01-08 10:49
Duplicate of #2660

**Closed by stuckie** 2024-01-08 10:49 UTC
Labels: ide-bug
