### ISSUE TITLE
"Attempt to dispatch event on non-instance object" showing up repeatedly in random instances

### ISSUE THREAD

**Issue by dvtzr** [YoYoGames/GameMaker-Bugs#2418] opened 2023-12-08 14:57 UTC
### Description
Hello! I am sending a report about this once again because I was told to do so if this error persists in the new runtime, and it did!
It has persisted for almost a year now, and without any solution, despite me reporting it numerous times.
The following error message shows up at random intervals during the game's runtime:
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_bm_test:

Attempt to dispatch event on non-instance object############################################################################################
The error message is extremely nonspecific, citing the first object inside a room in the instance creation order and with no real direction as to when it happens or why. 
This has made finding the steps to reproducte this error message next to impossible, instead hoping that it shows up (or doesn't show up) by sheer luck.
I don't know why it happens. I've combed through the code of the project dozens of times trying to find a cause (aswell as fixing any code errors/suggestions that were introduced by feather) and could not find a probable cause for this.
I am using a 64x Windows 10 Computer, with the latest runtime and with all of the required dependencies.
At the very least, I would like it it someone would atleast point me on where to look for? Because I am honestly at wit's end here.

### Steps To Reproduce
That said, It seems like the following steps can help trigger this error message. They are NOT 100% reliable, as sometimes they do not trigger it, but they are worth a shot:
1. Getting hit seems to sometimes trigger this message
2. It usually happens in stage 1 or stage 3
3. It usually happens when using the first character, babel.
I am also attaching a screenshot of when the error happened, hoping it might help.

[b2eb456d-35d3-41d9-bddc-4f9602770d6d](https://api.gamemaker.io/api/github/downloads/b2eb456d-35d3-41d9-bddc-4f9602770d6d)

**Comment by DarocMike** [comment] 2024-01-20 06:23
I keep encountering this bug, and so far, no one has been able to help me. In my case, it always crashes in the Create Event of obj_game. When I look at the code there, everything seems fine. Unfortunately, the error message doesn't specify exactly which line the crash occurs in. I also doubt by now that there is any issue in the Create Event of the object; rather, it seems to be SOMETHING else. My Android game is on the verge of release, and I've worked on it for over 3 years. Now, I don't know whether to publish the game with this bug or not.

**Comment by gjoyner** [comment] 2024-01-29 18:49
Also experiencing this error. Some notes for my issue:
- I have a struct that stores a reference to the instance that "owns" that struct.
- The struct is used to manage a time source acting as a metronome
- The line causing the error is after a delay (initiated by a time source as well), so there has been enough time for the instance to be created.
- The line immediately before the error is `instance_exists`, which returns true (in fact, the line where the error occurs is enclosed in an `if(instance_exists(obj_erroring))`, so it most definitely exists).
- This error occurs no matter what way you get an instance. `instance_find`, passing the instance as an argument into the time source, or an instance stored in the struct. All of those still cause the error, and all of them return true for `instance_exists`

See the attached project for an example of the error.
[Metronome.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14088357/Metronome.zip)

**Comment by gjoyner** [comment] 2024-01-31 02:23
> I keep encountering this bug, and so far, no one has been able to help me. In my case, it always crashes in the Create Event of obj_game. When I look at the code there, everything seems fine. Unfortunately, the error message doesn't specify exactly which line the crash occurs in. I also doubt by now that there is any issue in the Create Event of the object; rather, it seems to be SOMETHING else. My Android game is on the verge of release, and I've worked on it for over 3 years. Now, I don't know whether to publish the game with this bug or not.

I'm assuming the debugger isn't stopping on the line that's crashing while running it in the debugger? You can always breakpoint and step through line-by-line to see when it crashes too, if you haven't tried that already.

**Comment by DarocMike** [comment] 2024-01-31 08:12
@gjoyner
I must admit that I have limited experience with the debugger and have only used it a few times, so I'm not quite familiar with how it can assist me in investigating this bug. Is it sufficient to start the debugger, wait for the crash to occur, and then somehow inspect the last displayed line of code in the debugger?

The bug occurs very sporadically, sometimes taking hours to manifest, making it challenging for me to figure out how to approach the issue. obj_game is extensively referenced and contains a significant amount of code, making it even more difficult to pinpoint the problem.

The bug seems to occur during active gameplay but also when transitioning from the pause menu or moving between rooms. Unfortunately, it's so infrequent that I can't accurately predict when it will happen.

I would greatly appreciate any tips or suggestions you might have. Do you have any ideas on how to tackle this issue, given its elusive nature?

**Comment by jackerley** [comment] 2024-01-31 10:29
@gjoyner  I've looked at your project and I think yours is a different issue, you are calling event_perform_object and passing an instance in, which isn't going to work (and I will add a check in to the source to warn you better) I think what you want to be doing in your callback is 

with(sourceObj)
{
	event_user(0)
			
}

**Comment by jackerley** [comment] 2024-01-31 10:38
@dvtzr  I haven't been able to reproduce your issue, I do notice that you are calling instance_change() in a number of places in your code and there have been reports of problems associated with that call (under the hood it is a really nasty function) Could you try removing those calls and instead destroying the instance that would have been changed and creating a new instance, see if that helps?

**Comment by gjoyner** [comment] 2024-01-31 16:46
@jackerley Ooooh. I keep forgetting about `with`! What's the use case for `event_perform_object` then? Do I pass the actual asset to it instead of an instance? Good thinking on adding the warning!

@DarocMike It'll be hard to summarize all of how to use the debugger here, but it's definitely worth learning for any project. Pressing F6 (or clicking the bug icon) will launch the game with the debugger active. If there's an error, the game will halt at the line causing the error, and you can look at the value of any variables in that section of code (usually by just mousing over). You can also set breakpoints by clicking to the left of (nearly) any line of code (between the line number and the code itself). It'll put a red dot on that line. While the debugger is active, the game will halt at the breakpoint you placed. From there you can check variable values, "step into" a line (for when you're calling a function/script and want to enter that function/script to see what it's doing), "step over" a line (move to the next line of code, running it without necessarily going into any functions), or "step out" (go up one level to the calling function/script). It'll also tell you things like how much memory you're using. You can find Yoyo's breakdown of the debugger [here](https://gamemaker.io/en/tutorials/debugger).

**Comment by jackerley** [comment] 2024-01-31 16:55
@gjoyner event_perform_object allows you to call another object's event from a different instance, so if you wanted to call ObjectA's draw event from an instance of ObjectB you can. (Which is a pretty horrid thing to do, you'd be much better using a separate function, but this is legacy stuff so we're stuck with it for now)

**Comment by gjoyner** [comment] 2024-01-31 17:03
@jackerley Ah ok. I can definitely see where that could get hairy fast. I'll consider using the method you mentioned. I appreciate the info!

**Comment by dvtzr** [comment] 2024-02-03 21:45
@jackerley after removing all instances of instance_change() and switching them to with deleting the object and performing the events neccesary, i am very cautiously optimistic to say that the issue seems to have been resolved! i suppose it might have also been the fact that the code performed extra actions AFTER the instance has been changed, which probably was where the issue stemmed from. as code with instance_change() exists in most objects in the game, that was probably why it was so hard to discern.
however... i'd still really want to somehow help @DarocMike resolve their issue, as it's thanks to them that this got the attention in the first place, and i want them to find what's causing it aswell. hopefully the information here has helped in some way, but if possible, please keep this open until we find a solution for them aswell!!
thank you very much everyone!! this issue has been eluding me for almost a year now, it's nice to finally see it being laid to rest.

**Comment by jackerley** [comment] 2024-02-05 09:13
thanks @dvtzr glad that's helped. @DarocMike if you can provide your project and any reproduction instructions I can take a look and see what's happening for you?

**Comment by DarocMike** [comment] 2024-02-05 11:02
@jackerley Since the crash occurs very irregularly, I cannot guarantee that it will definitely happen when you test it. It might be that you play for half an hour or even longer, and nothing happens. In the coming days, I will likely build a version where certain processes in the game run automatically, allowing you to let the game run in the background until the crash occurs without having to play or interact with the app. I could then possibly send you that version. Regarding the instance_change issue: I use instance_change at various points in the game, but not in an event of obj_game and not with obj_game; I replace other objects (with other objects that also aren't obj_game). Could this still be the problem? As mentioned, the error message points to the Create Event of obj_game.

**Comment by jackerley** [comment] 2024-02-05 13:44
@DarocMike  I would recommend removing any calls you have to instance_change() I think this may well be the cause of your problems.  I will close this issue now, but please submit an issue if you are still having problems when you've made the changes to your project and removed any instance_change calls. Thanks, Fritz

**Closed by jackerley** 2024-02-05 13:44 UTC
Labels: runner-bug, project

**Comment by DarocMike** [comment] 2024-02-06 10:10
@gjoyner Unfortunately, it seems that the debugger is not helping me with this issue. I have managed to trigger the crash again after approximately 1.5 hours of playing, and nothing is being displayed in the debugger. Previously, as a test, I intentionally crashed the game while in debugger mode to see how the debugger would indicate where the game crashed. That worked well, but for this specific error, it's not showing me anything. Following jackerley's recommendation, I will now remove all instance_change functions from the game and see if that helps...
