### ISSUE TITLE
Login "Remember me" doing nothing.

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#2460] opened 2023-12-12 21:45 UTC
### Description

To prefix this, I'm using a legacy account which may be the root of the issue but unsure.

It's checked by default, how ever despite checking it and unchecking it, I do not remain signed in for anything more then a few hours. When internet goes out it means that many of my projects are unable to be worked on as it refuses to keep me signed in. This has been a problem for a while but only reporting it now do to consistent internet outages in the area. If I'm not mistaken this started happening a month or so before the free changes.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/04bdb015-f5ef-4d14-9d79-e6a018ef765d)

### Expected Change

Stay signed in regardless of closing GM, restarting computer, power outages, or internet issues.

### Steps To Reproduce

option 1)
Sign in, close GM, openGM.
option 2)
Sign in, restart computer, openGM.

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment] 2023-12-15 13:34
So yes sign-in should be preserved between IDE restarts if you have "Remember me" checked when signing in, and assuming you don't have preference General Settings->"Sign out on exit" checked; Testing in IDE v2023.11.0.121, both offline and online login seemed to functioning correctly and I could not find any issues.
Might be worth just signing in at https://gamemaker.io/account with your legacy account just to see if there's any obvious issue with the account; otherwise, if you can attach a ui.log , there may be some clues in there.

**Comment by yyalansavage** [comment] 2024-01-08 15:09
Closing as cannot reproduce for just now as unable to find any problems; can re-open if issue persists, in which case please provide a ui.log and ensure "Enable Verbose Logging" is checked in Preferences->General Settings

**Closed by yyalansavage** 2024-01-08 15:09 UTC
Labels: ide-bug
