### ISSUE TITLE
Autofill recommendations in template strings

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#8104] opened 2024-10-23 16:24 UTC
### Description

Autofill recommendation showing up inside the string part of a string template.
![Image](https://github.com/user-attachments/assets/3e9d567d-f775-45b1-bf16-a6c48bbe2c2c)

### Expected Change

recommendations should only show up in between curly brackets `{}` and not in between any of the following `"{`, `}{`, `}"`, `""`

### Steps To Reproduce

```
/// add a `g` and see issue
var _t = $"show_debu"
```

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-10-24 08:47
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/7145

**Closed by YYDan** 2024-10-24 08:47 UTC
Labels: ide-bug
