### ISSUE TITLE
Pressing enter to search with the search & replace window doesn't work if the window is docked

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6135] opened 2024-06-06 06:00 UTC
### Description
If you hit ctrl + shift + f to open the search and replace window, you can type something and then press enter to do the search. However, if the search and replace window is docked somewhere in the IDE, pressing enter to search no longer works.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/fb8d889b-0ab4-4319-ba07-579b3ed9639d

### Steps To Reproduce
Press ctrl + shift + f. Drag the window so it's docked somewhere. Type something to search for and hit enter.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.562 Runtime v2024.600.0.580

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c0ee60bb-2a98-4f7a-be14-910e92f23887](https://api.gamemaker.io/api/github/downloads/c0ee60bb-2a98-4f7a-be14-910e92f23887)

**Comment by YYDan** [comment] 2024-06-06 08:25
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/854

**Comment by YYDan** [comment] 2024-06-06 08:25
Although, I am going to add your lovely video onto that one ;)

**Closed by YYDan** 2024-06-06 08:25 UTC
Labels: ide-bug
