### ISSUE TITLE
Bug Reporter: IDE bug reports failing with "(403) Forbidden"

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6932] opened 2024-07-28 20:54 UTC
### Description

Don't know if this is a temporary outage or not, but reporting just in case. IDE bug reports are giving back a 403 Forbidden error when trying to submit.
![image](https://github.com/user-attachments/assets/0f926281-95dc-45ff-b826-e471eef3eed0)

### Expected Change

The bug reporter to not error

### Steps To Reproduce

Submit a bug report through the IDE

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-07-30 15:37
Yes, there was a brief temporary disruption on Sunday, caused by someone trying to DDOS our web services. This was rectified shortly after and bugs have been fine ever since.

Closing, as this was a Web thing, rather than a GameMaker bug.

**Closed by YYDan** 2024-07-30 15:37 UTC
Labels: ide-bug
