### ISSUE TITLE
Importing of spine JSON files into GameMaker to create sprite asset throwing error

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#2338] opened 2023-11-30 12:54 UTC
### Description

Importing of spine JSON files into GameMaker to create sprite asset throwing error message.

Spine JSON file C:\Users\adouglas\Documents\GitHub\-live-wallpaper\-Live-Wallpaper\sprites\Sprite14\2d39def2-5748-499d-b2dd-875bfe23fb7e.json uses version 4.1.24 - may not be supported
Error reading animation: Front_Dance
The given key 'name' was not present in the dictionary.
Spine Error : Sprite14 : Invalid JSON file C:\Users\adouglas\Documents\GitHub\-live-wallpaper\...-Live-Wallpaper\sprites\Sprite14\2d39def2-5748-499d-b2dd-875bfe23fb7e.json
elapsed time 00:00:00.5420147s for command "C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2023.1100.0.459/bin/assetcompiler/windows/x64/GMAssetCompiler.exe" /zpex /c /m=win /td="C:\Users\adouglas\Documents\GitHub\-live-wallpaper\-Live-Wallpaper\sprites\Sprite14" /spineimage="C:\Users\adouglas\Documents\GitHub\-live-wallpaper\-Live-Wallpaper\sprites\Sprite14\2d39def2-5748-499d-b2dd-875bfe23fb7e.json" /zpuf="C:\Users\adouglas\AppData\Roaming/GameMakerStudio2-Beta\adouglas_4227807" started at 11/30/2023 10:52:41

Version of gamemaker used was BETA IDE v2023.1100.0.450  Runtime v2023.1100.0.459 However any version has the same issue

Contact Us Package file size too big

### Expected Change

Asset would import without issue

### Steps To Reproduce

1. Start GameMaker (any version)
2. Create new sprite asset
3. Click Import button
4. Select .JSON spine file
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2023-12-01 09:38
We will need the spine sprite to verify this.

**Comment by ash0verride** [comment] 2023-12-01 09:41
[lucky.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13523584/lucky.zip)

No problem

**Comment by YYDan** [comment] 2023-12-06 09:50
From what I understood, this one is a dupe of https://github.com/YoYoGames/GameMaker-Bugs/issues/1283 but with far more info in the report, so we will keep this one - @yoyo-danielc could you let me know if that's true, please?

**Comment by yoyo-danielc** [comment] 2024-06-12 09:50
As far as I can tell, this failure might be occurring because the export is for Spine 4.1.

The provided JSON has some animations where not all attachment slots have a `name` key, which the Spine C# loader chokes on. It looks like the 4.1 version of Spine C# supports the name key being absent.

```json
"Confidence/Confidence_Face_Blink_Right2": {
    "attachment": [
        { "time": 0.6667, "name": "Confidence/Confidence_Face_Blink_Right" },
        { "time": 0.7667 },
        { "time": 1.0333, "name": "Confidence/Confidence_Face_Blink_Right" },
        { "time": 1.0667 }
    ]
},
```

Could you provide the original Spine project and/or try exporting with version 4.0 to confirm?

Thanks

**Comment by yoyo-danielc** [comment] 2024-07-25 12:52
Closing as not-a-bug per my previous comment, if this sprite does fail to load when exported as a 4.0 format JSON, please do reopen.

**Closed by yoyo-danielc** 2024-07-25 12:52 UTC
Labels: ide-bug
