### ISSUE TITLE
Feather: Autocomplete does not appear when in a GML Visual "Execute Code" node

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1924] opened 2023-09-21 10:52 UTC
### Description

When typing in the 'execute code' visual action the code autocompletion window does not appear at all, as shown in the attached video.

[Autocomplete_Visual.mp4](https://drive.google.com/file/d/1FhPmnZVUKSRnk4mT21yqW7OJRnH1t3Zp/view?usp=sharing)

### Expected Change

The autocomplete window should appear when typing in the 'execute code' visual action

### Steps To Reproduce

1. Start GameMaker and open/create any project.
2. Type some code into an object event or script.
3. Convert the code to GML visual.
4. Start typing the name of a function or variable.
5. Observe that the autocomplete does not appear.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Jun 23, Aug 23, Aug 24

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by YYDan** [comment] 2024-08-19 13:42
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/977

**Closed by YYDan** 2024-08-19 13:42 UTC
Labels: ide-bug
