### ISSUE TITLE
Issue with merge_color()

### ISSUE THREAD

**Issue by Dalmacc** [YoYoGames/GameMaker-Bugs#2526] opened 2023-12-18 12:44 UTC
### Description

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/79963414/9c4bb9e5-1659-47cb-8179-1061e1372e45)
To understand the situation, I’ll tell you in more detail: This is the main menu, three blocks are selected separately. 1 - color of the selected block, 2 - color after selecting and changing the block, 3 - color of the never selected block

I also want to point out that the game has a division by the frame rate coefficient in order to remove the FPS limitation. Without it, this problem remains, but the contrast between colors increases.
[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13703893/contactus.zip)

### Expected Change

Colors like in the second block do not exist

### Steps To Reproduce

1. Start GameMaker 
2. Use merge_color() to make a smooth color transition 
3. Get an incomplete color transition

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment] 2023-12-19 09:36
This is not a bug with GameMaker itself, but one in your project, so I will close this issue now. For coding support, please visit the [GameMaker Community](https://forum.gamemaker.io/index.php) forum and create a thread there, asking for advice.

**Closed by stuckie** 2023-12-19 09:36 UTC
Labels: runner-bug
