### ISSUE TITLE
Feather: [Mac IDE] Shortcut to open Quick Fix menu (^Q) does not work

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5699] opened 2024-05-01 11:06 UTC
### Description

When trying to use the command to open the Quick Fix menu this won't work as expected and will need to open it manually.

![screenshot_2024-05-01_at_11 58 53_720](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/11d4f319-0fe5-46c7-ab0c-99769d6cd7a1)

### Steps To Reproduce

1. Start GameMaker on a Mac
2. Open any project with feather messages
3. Try to open the Quick fix menu by using the command ^Q
4. Observe nothing happens

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment] 2024-05-02 08:45
Duplicate of #5663.

**Closed by SmithTom6304** 2024-05-02 08:45 UTC
Labels: ide-bug
