### ISSUE TITLE
Add a way to paste in the image editor without adding an extra layer or brush

### ISSUE THREAD

**Issue by flori9** [YoYoGames/GameMaker-Bugs#6557] opened 2024-07-07 20:01 UTC
### Is your feature request related to a problem?

I regularly want to paste things in the image editor (e.g. from other image editors). There are currently two ways to paste: as brush or as layer. Both are not ideal:
- pasting as a brush is never what I want and next time you try to edit a pixel, you suddenly paste again.
- Pasting as a layer is slightly better, but you eventually end up with a huge amount of layers, taking up memory and making your image harder to edit (because things are on separate layers) for no benefit. You can merge those layers, but that's an extra step that I don't think even has a keyboard shortcut (bonus suggestion!).

### Describe the solution you'd like

A third option in the Preferences for how pasting in the image editor works. This could be e.g. called Merge. It simply does the same as if you would paste as a layer, and then merge that layer. Any reasonable image editor has this, so I think GameMaker also deserves it.

**Comment by YYDan** [comment] 2024-07-08 08:58
Duplicate of one of the points on https://github.com/YoYoGames/GameMaker-Bugs/issues/2761

**Closed by YYDan** 2024-07-08 08:58 UTC
Labels: feature request
