### ISSUE TITLE
Code Editor 2: autocomplete doesn't include your own functions/assets/symbols/etc if you start typing in the middle of a line that's already been written

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6835] opened 2024-07-23 06:23 UTC
### Description

This happens pretty randomly so hard to report but at least in this project, this instance of it seems to be 100% reproducible.

![image](https://github.com/user-attachments/assets/6e440a83-276d-41d9-9313-716cbabe4b47)

In this example, the list should contain several assets that look sort of like this:

![image](https://github.com/user-attachments/assets/f74275af-ed79-4454-a51b-6795ca39a92f)

If you start typing a built-in function name, once in a while it'll show an incomplete list.

![image](https://github.com/user-attachments/assets/88477ec3-6b9b-429c-988d-d52d6d50a47f)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment] 2024-07-23 06:28
kormex thinks might be the same as #6487

**Comment by YYDan** [comment] 2024-07-23 08:04
Yeah, I was thinking that also ;)

**Comment by YYDan** [comment] 2024-07-23 08:04
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6487

**Closed by YYDan** 2024-07-23 08:04 UTC
Labels: ide-bug
