### ISSUE TITLE
Ability to automatically collapse regions

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3706] opened 2023-06-06 15:11 UTC
User request message from ticket [Ticket #185970]

 

Feature Type: feat_addition_ide
Description: Have an option so that when turned on, regions are automatically closed when opening a code window.
Benefit: The regions that can be used are very usefull. However, the usefullnes is a little negated by the fact that they open every time a code window is opened. After all, what's the use of a region if you have to close them everytime you open a new code window? If you have the option that they are automatically closed, you only have to open the region you want to adjust. This saves a click but -more importantly- also makes searching faster in larger codes.

**Comment by YYDan** [comment] 2024-02-26 11:32
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3145

**Closed by YYDan** 2024-02-26 11:32 UTC
Labels: feature request, import
