### ISSUE TITLE
Code Editor 2: while open, CE2 will steal keyboard shortcuts from other parts of the IDE, even when it's in the background

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5681] opened 2024-04-29 20:08 UTC
### Description
When you have a CE2 window open in the background, if you're trying to do something else in another part of the IDE, anything that has a keyboard shortcut with a behavior in the code editor will still happen in the code editor... even if the CE2 window is in the background

Some instances that I've run into include:
- In the sprite editor, copying (ctrl+c)/pasting (ctrl+v)/duplicating (ctrl+x) frames will copy/paste/duplicate into a CE2 window instead
- In the sprite editor, trying to delete a layer or something selected with the magic wand will delete anything selected in the Ce2 window instead
- In the Asset Browser, keys like delete/duplicate will likewise be routed to the CE2 window instead
- I assume this issue affects pretty much everything else in the IDE, but these are the only ones I've run into so far
- In some cases (but apparently not all?) CE2 windows will even appear to steal regular text entry ; for example, when I was typing out this report, things like Enter and Delete would sometimes activate  CE2 in the background

Keyboard shortcuts that **do not** have any effect in a CE2 window will stlil work, such as F2 to rename something

If you have multiple CE2 windows open, it appears that only the first one will steal the keyboard input

This is what ctrl+c and ctrl+v look like when you have frames selected in the sprite editor:
![ce2 steals keyboard shortcuts](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/ac283ebd-fba2-4342-b674-08a306da3de8)

### Steps To Reproduce
1. Open `Script1`
2. Do any of the things I mentioned above
3. Oh dear

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.136 Runtime v2024.4.0.167

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[f0ca4f65-34be-4355-a069-51cad7193dc1](https://api.gamemaker.io/api/github/downloads/f0ca4f65-34be-4355-a069-51cad7193dc1)

**Comment by YYDan** [comment] 2024-04-30 07:35
This will ultimately be because CE2 is disabled in that _internal_ IDE version, but there is an issue we have filed already where some CE2-related Redefine Keys values not being disabled at the same time. This other issue is already being investigated for a fix asap, so I will get this one checked again once that is fixed

In the meantime, you may wish to stop using our internal versions, as yes they _will_ contain bugs..........

**Comment by DragoniteSpam** [comment] 2024-04-30 15:07
I'm surprised you don't get on my case about that more often, lol. I don't mind mucking around with the unofficial builds, though it's hard to tell which bugs have already been raised internally already, for obvious reasons...

**Comment by zreedy** [comment] 2024-06-27 21:17
Unable to reproduce, probably due to these bugs being reflected in what was internal churn as the Hotkey Subsystem was being updated.
Closing as this appears fixed in current public betas...

**Closed by zreedy** 2024-06-27 21:17 UTC
Labels: ide-bug
