### ISSUE TITLE
Parent Texture Group does not affect children

### ISSUE THREAD

**Issue by cenowador** [YoYoGames/GameMaker-Bugs#2079] opened 2023-11-01 11:03 UTC
### Description
According to the documentation, changing a Parent Texture platform settings, should affect all of their children. However, nothing seems to be happening. When toggling the Windows platform on the Parent, the child continues to be drawn (and everything inside the parent stops to be drawn). The expected behavior would be that everything inside the Parent AND children would stop to be drawn

### Steps To Reproduce
You can try toggling the Parent's settings on the attached project and see that the sprite on the Child group continues to be drawn

[fe59e3a4-943b-4803-9bd5-196d698c29d0](https://api.gamemaker.io/api/github/downloads/fe59e3a4-943b-4803-9bd5-196d698c29d0)

**Comment by stuckie** [comment] 2023-11-02 09:39
This is not a bug with GameMaker itself, but a mistake in our documentation, so I will assign this issue to the docs team now.

Child Texture Groups have separate settings.

**Comment by cenowador** [comment] 2023-11-02 14:15
But this leaves me with a legitimate question: if the visibility of the parent doesn't affect the children, and neither does "dynamic/static" type, what does it do then? 🤔

**Comment by rwkay** [comment] 2023-11-02 14:27
The child texture group graphics are included on the same texture page, that is the reason for them.

**Closed** 2024-01-04 16:46 UTC
Labels: ide-bug, project
