### ISSUE TITLE
Uh

### ISSUE THREAD

**Issue by Douglas711** [YoYoGames/GameMaker-Bugs#5612] opened 2024-04-23 07:04 UTC
### Description
Unsure I was just switching from Default config to the Developer config. Hasn't happened before.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[83046724-e957-4b80-a509-a162321fdee9](https://api.gamemaker.io/api/github/downloads/83046724-e957-4b80-a509-a162321fdee9)

**Comment by stuckie** [comment] 2024-04-23 09:05
Duplicate of #4906

**Closed by stuckie** 2024-04-23 09:05 UTC
Labels: crash, dump
