### ISSUE TITLE
tab close prevention

### ISSUE THREAD

**Issue by AvioxArcade** [YoYoGames/GameMaker-Bugs#5582] opened 2024-04-19 21:14 UTC
### Is your feature request related to a problem?

it's not impossible to accidentally close a workspace or tab with a lot of open content. 
Doing so both hangs gamemaker for a long time (especially if it's a workspace) a causes a pretty big interruption when done on accident

### Describe the solution you'd like

Add a "pin tab" context option to the right click menu on a tab. pinned tabs can't be closed (and must be "un-pinned" first)

### Describe alternatives you've considered

add a confirm dialogue box when closing a workspace or similar.

**Comment by YYDan** [comment] 2024-04-22 08:18
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3037

**Closed by YYDan** 2024-04-22 08:18 UTC
Labels: feature request

**Comment by AvioxArcade** [comment] 2024-04-22 13:06
Thanks for clarifying. 
Sorry for the misunderstanding.

Perhaps an image added to the Texture Groups page of the manual to show what it does would be nice.
