### ISSUE TITLE
Imported Graphical Assets are moved to TextureGroup "default"

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4955] opened 2024-03-08 18:17 UTC
### Description
Hey there,

when you create a local package with graphical assets (sprites, fonts, ...), and import them in another project, all imported sprites and fonts and all other things are set back to the TextureGroup "default".
In a more complex project with many texture groups, this can become a nightmare quickly, when you find yourself in the situation, that the TextureGroups window shows 300+ Sprites in one endless list in "default" and you have to manually sort them back to where they where.

## Steps to reproduce
* Put a group of assets from different texture groups into a local package
* To have the same situation, I had, when I encountered it multiple times:
  * NONE of the sprites was in "default"
  * I say this, because I can't tell yet, whether it makes a difference, if at least one of the items was in "default" or not, maybe it's because of the total absence of "default" in the package... i don't know, so please try to reproduce it without anything in default when exporting
* now take another project, _that contains the same texture groups_ already, but with different or partially overlapping asset names in it
* import the package
* -> All imported assets are now in "default"

_Additional sub-bug for this ticket:_ **Sometimes** (can't reproduce yet, but as soon as I can, I will write a checklist for you), the multi-select in the "TextureGroups" window does not work. You select like 50 Sprites, right-click, "move to ->" another texturegroup and only _one_ item is moved (the one you clicked), and not all selected. Not stable reproducible yet for me, just wanted to mention, there's slumbering something in that dialog window.

Kind regards,
Gris

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[e2998e13-d37a-43c1-8896-31850fd4100f](https://api.gamemaker.io/api/github/downloads/e2998e13-d37a-43c1-8896-31850fd4100f)

**Comment by Grisgram** [comment] 2024-04-10 02:25
'morning @stuckie,
This one can be closed together with #5375, #5376 and #5378 as soon as the fix of #5378 is in place. They are all tied together.

When I import a (manually fixed) sprite from a different TextureGroup, the group is correctly interpreted. It's all the same error source.

**Comment by stuckie** [comment] 2024-04-10 11:07
I'm actually going to close this as duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1101 
We're aware we need to work on bringing in texture/audio groups properly... the extra bugs I'll verify and sort out as well.

Thanks!

**Closed by stuckie** 2024-04-10 11:07 UTC
Labels: feature request
