### ISSUE TITLE
Resizing a tile set sprite won't properly update already placed tiles

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#2480] opened 2023-12-14 10:53 UTC
### Description
If you change the width of a tileset sprite to make room for additional tiles it will mess up the rooms you already decorated.

I think it would be better if the IDE would calculate the new tile indices and update all the rooms that reference the tileset.

### Steps To Reproduce
1. Create a tile set
2. Use it in a room
3. Change the width of the associated sprite
4. The decorated room will be negatively affected.

[2ea2a8d3-ba1d-4e3a-bcce-6023368a4030](https://api.gamemaker.io/api/github/downloads/2ea2a8d3-ba1d-4e3a-bcce-6023368a4030)

**Comment by YYDan** [comment] 2024-06-19 15:44
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2874

**Closed by YYDan** 2024-06-19 15:44 UTC
Labels: ide-bug
