### ISSUE TITLE
Duplicated, empty "Feather Messages" pane in when reopening a project

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#4429] opened 2024-01-20 23:30 UTC
### Description

Contact-us package: 
[DuplicatedFeatherPane.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13999486/DuplicatedFeatherPane.zip)

The new combined "Feather Messages" pane is opening blank duplicates when a project is being closed and opened repeatedly. See this screenshot for an example:

![Screenshot 2024-01-20 at 6 28 31 PM](https://github.com/YoYoGames/GameMaker-Bugs/assets/1713490/31694430-84a4-407c-948f-a70993a229ab)

### Expected Change

That empty "Feather Messages" pane should no longer appear.

### Steps To Reproduce

1. Import the project in the attached contact-us package.
2. Click the "Home" icon to close the project.
3. Open the project again.
4. There is now a false "Feather Messages" pane that has nothing in it. You have to resize it from the right to find the original first true one that has something in it.
5. Repeat steps 2-3.
6. There is now a third "Feather Messages" pane that also has nothing in it. Again the true pane is croweded out to the right and needs to be "resized" back in.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yyalansavage** [comment] 2024-01-22 16:17
closing as duplicate of https://github.com/YoYoGames/YoYoStudio/issues/9293

**Closed by yyalansavage** 2024-01-22 16:17 UTC
Labels: ide-bug

**Comment by Emc1923** [comment] 2024-01-31 12:07
Duplicate verified fixed as of Beta IDE v2024.200.0.475 Runtime v2024.200.0.490, closing.
