### ISSUE TITLE
Install: [Win IDE] GameMaker has stopped adding its version number and icon to the info in Add/Remove Programs

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1923] opened 2023-09-21 10:52 UTC
### Description

GameMaker has stopped adding its version number to the info in Add/Remove Programs (and some branding info):

![image](https://github.com/YoYoGames/bugimport/assets/131007845/4be0a2a8-6572-4d6c-8c33-a84f0f4ab21d)

This also apparently breaks some third-party updater software customers have been using to automate when new versions are released - for example Winget (https://github.com/microsoft/winget-cli/issues/1356).

### Expected Change

The version number for GameMaker should be visible in the Add/Remove Programs, as should its icon and all other required branding values

### Steps To Reproduce

1, Install any recent version of GameMaker.
2. Open Add/Remove Programs in Windows.
3. Browse down the list to find GameMaker.
4. Observe the issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Jun 23

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by YYDan** [comment] 2023-10-25 14:24
Still an issue in internal early Nov Betas also, so have put this back to Triage so we can discuss scheduling.

**Comment by Emc1923** [comment] 2023-11-07 11:33
The icon and publisher are still missing as of  IDE v2023.1100.0.434  Runtime v2023.1100.0.447. The version is now correctly displayed. Reopening the issue for now.

**Comment by YYDan** [comment] 2023-11-22 12:40
Worth confirming also that the branding is present on the UAC dialogs and during the uninstallation process, as there was an old copy of this issue reported and open in the backlog until I just cleaned it up.

**Comment by LukeBrownYoYoGames** [comment] 2023-11-22 18:15
I can't reproduce the publisher issue, that seems to always be there for me, but the icon should now be fixed in 37be78a18d1194df8afedf76bfc15d123f6eeda7

**Closed** 2023-12-05 12:08 UTC
Labels: ide-bug
