### ISSUE TITLE
Startup: GM silent crash due to "MySQL font" virus issue still possible in 2023.11, need to add 1568 dialog in more places

### ISSUE THREAD

**Issue by user1685024** [YoYoGames/GameMaker-Bugs#4693] opened 2024-02-12 04:29 UTC
### Description

首次安装完成后的最后一步显示了这个界面，并且尝试点击打开会直接闪退，无论是官网的还是steam版本的我都尝试过了，还重启安装过，或者检查directx12，我从凌晨2点工作到5点都无法解决这个问题，并且我是中文使用者，我只能将大部分文字尝试机翻，你们的手册中仍然未找到该问题的描述。

This interface is displayed in the last step after the first installation is completed：
![Snipaste_2024-02-11_05-15-11](https://github.com/YoYoGames/GameMaker-Bugs/assets/159746974/13257829-0b71-4892-854a-c92444f9e787)

and if you try to click to open it, it will crash directly. I have tried both the official website and the steam version. I have also restarted the installation, or checked directx12. I have been working since 2 am. I still can't solve this problem until 5 o'clock, and I am a Chinese user. I can only try to translate most of the text. I still can't find a description of this problem in your manual.

### Steps To Reproduce

1. Download the installation package
2. Install
3. crash

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2024-02-12 10:51
Hello,

This might be due to firewall or other networking issues blocking the start-up.
However, as you cannot open the IDE, you will need to attach the ui.log manually so we can have a better idea on what is going on.
You can find this at: C:\ProgramData\GameMakerStudio2\ui.log or %ProgramData%\GameMakerStudio2\ui.log if your ProgramData directory is different from the default.

**Comment by stuckie** [comment] 2024-02-13 09:35
Closing this just now to keep our side tidy.
If you can get the ui.log and create a new ticket, we can investigate further.

**Comment by user1685024** [comment] 2024-02-16 08:32
> 你好，
> 
> 这可能是由于防火墙或其他网络问题阻止启动。 但是，由于您无法打开 IDE，因此您需要手动附加 ui.log，以便我们可以更好地了解发生了什么。 您可以在以下位置找到此文件：C:\ProgramData\GameMakerStudio2\ui.log 或 %ProgramData%\GameMakerStudio2\ui.log（如果您的 ProgramData 目录与默认目录不同）。

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/14308419/ui.log)
thanks!

**Comment by stuckie** [comment] 2024-02-16 09:05
From the ui.log there is an error here:
[12:00:03:493(ad70)] IDE Exception: System.UnauthorizedAccessException: Access to the path 'C:\Windows\Fonts\Mysql' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Graphics.Text.HbFontManager.DiscoverFontsFromDirectory(String fontDirectory)
   at Graphics.Text.HbFontManager.Initialize()
   at YoYoStudio.IDE.Initialise(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
[12:00:03:493(ad70)] 

We are aware of a virus that does this and have an FAQ on how to deal with this here: https://help.gamemaker.io/hc/en-us/articles/14837145219485-Startup-Crashes-Due-To-Access-to-the-path-C-WINDOWS-Fonts-Mysql-is-denied-Windows-IDE

Hopefully that helps!

**Comment by user1685024** [comment] 2024-02-20 12:04
> 从 ui.log 来看，这里有一个错误： [12:00:03:493(ad70)] IDE 异常：System.UnauthorizedAccessException：对路径“C:\Windows\Fonts\Mysql”的访问被拒绝。 在 System.IO.Enumeration.FileSystemEnumerator `1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 相对路径，字符串 fullPath) 在 System.IO.Enumeration.FileSystemEnumerator `1.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 集合) 在 Graphics.Text.HbFontManager.DiscoverFontsFromDirectory(String fontDirectory) 在 Graphics.Text.HbFontManager .Initialize() 在 YoYoStudio.IDE.Initialise(String[] _args, Int32 _initialWidth, Int32 _initialHeight) 在 YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight) [12:00:03:493(ad70) )]
> 
> 我们知道有一种病毒会造成这种情况，并在此处提供了有关如何处理此问题的常见问题解答：[https ://help.gamemaker.io/hc/en-us/articles/14837145219485-Startup-Crashes-Due-To-Access -到路径-C-WINDOWS-Fonts-Mysql-is-denied-Windows-IDE](https://help.gamemaker.io/hc/en-us/articles/14837145219485-Startup-Crashes-Due-To-Access-to-the-path-C-WINDOWS-Fonts-Mysql-is-denied-Windows-IDE)
> 
> 希望这有帮助！


Thank you for your answer, but I cannot find the folder under this link. At the same time, I tried to google this directory address: "C:\WINDOWS\Fonts\Mysql", but there was no answer. Can you tell me how to make it Show it?
PS: I checked your link. The solution is to open fonts and delete the Mysql folder. Do I understand it correctly?

**Comment by user1685024** [comment] 2024-02-20 12:05
> 从 ui.log 来看，这里有一个错误： [12:00:03:493(ad70)] IDE 异常：System.UnauthorizedAccessException：对路径“C:\Windows\Fonts\Mysql”的访问被拒绝。 在 System.IO.Enumeration.FileSystemEnumerator `1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 相对路径，字符串 fullPath) 在 System.IO.Enumeration.FileSystemEnumerator `1.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 集合) 在 Graphics.Text.HbFontManager.DiscoverFontsFromDirectory(String fontDirectory) 在 Graphics.Text.HbFontManager .Initialize() 在 YoYoStudio.IDE.Initialise(String[] _args, Int32 _initialWidth, Int32 _initialHeight) 在 YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight) [12:00:03:493(ad70) )]
> 
> 我们知道有一种病毒会造成这种情况，并在此处提供了有关如何处理此问题的常见问题解答：[https ://help.gamemaker.io/hc/en-us/articles/14837145219485-Startup-Crashes-Due-To-Access -到路径-C-WINDOWS-Fonts-Mysql-is-denied-Windows-IDE](https://help.gamemaker.io/hc/en-us/articles/14837145219485-Startup-Crashes-Due-To-Access-to-the-path-C-WINDOWS-Fonts-Mysql-is-denied-Windows-IDE)
> 
> 希望这有帮助！

Thank you for your answer, but I cannot find the folder under this link. At the same time, I tried to google this directory address: "C:\WINDOWS\Fonts\Mysql", but there was no answer. Can you tell me how to make it Show it?
PS: I checked your link. The solution is to open fonts and delete the Mysql folder. Do I understand it correctly?

**Comment by user1685024** [comment] 2024-02-20 13:53
> 正确的;从调用堆栈中的错误来看，它试图访问 C:\Windows\Fonts\Mysql 目录，但失败了（ UnauthorizedAccessException ）
> 
> 我们从之前的报告中知道这可能是病毒，因此我们建议您从“C:\Windows\Fonts”中删除“Mysql”目录，并运行病毒扫描以捕获其他内容。
> 
> 我还重新打开了此票证，因为我们需要在启动时添加额外的警告对话框，因此您无需在完成后将其关闭。

Okay, but I checked C:\Windows\Fonts. This is the font directory of the window. There is no folder in it, and the folder cannot be created, as shown in the picture. How can I "delete the Mysql directory" you said?
At the same time, I used ESET to fully scan and kill my computer.

**Comment by stuckie** [comment] 2024-02-20 15:02
Ah, it may have already been cleaned.. if GameMaker is still not able to start up, please provide a new ui.log as there may be another reason.

**Comment by user1685024** [comment] 2024-02-20 18:47
> C:\ProgramData\GameMakerStudio2

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/14349903/ui.log)

**Comment by user1685024** [comment] 2024-02-20 18:48
> 啊，可能已经清理完了。如果GameMaker仍然无法启动，请提供新的ui.log，因为可能还有其他原因。

Thank you for your patient reply, please see above

**Comment by user1685024** [comment] 2024-02-21 06:33
> 啊，可能已经清理过了。如果GameMaker仍然无法启动，请提供新的ui.log，因为可能还有其他原因。

new ui.log ,please see above

**Comment by user1685024** [comment] 2024-02-21 06:34
> Ah, it may have already been cleaned.. if GameMaker is still not able to start up, please provide a new ui.log as there may be another reason.

new ui.log ,please see above

**Comment by stuckie** [comment] 2024-02-21 09:30
Hello, the ui.log still states the same reason that it cannot start up - that there is a C:\Windows\Fonts\mysql directory which we cannot open.

You may be able to resolve this by opening the Command Prompt as Administrator,
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/795290/7768ef5e-8780-4e80-9e67-bea00856396f)

And then typing in: **rmdir /s c:\windows\fonts\mysql**
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/795290/1cee9be8-77c8-4b7f-81c7-71f8d1f00c41)

However, please be careful in how you type, so that you do not delete the wrong thing.
At this point there isn't anything else we can do from a GameMaker stand point - the issue is that there is a directory in your C:\Windows\Fonts that we know of as causing harm, and it may be advised to seek assistance elsewhere if the issue continues, as it is outwith the scope of the support we can provide.

**Closed** 2024-03-13 16:27 UTC
Labels: ide-bug, crash

**Comment by caitlinrmcintyre** [comment] 2024-04-02 09:49
Verified fix in  IDE v2024.400.0.529  Runtime v2024.400.0.550, thanks.
