### ISSUE TITLE
Struct with numeric string property doesn't compile, except we use accessor.

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7442] opened 2024-08-27 12:24 UTC
### Description

I'm having such code:
```gml
var struct = {
	"0": 1,
}
```
When trying to compile, it returns: `Script: Script1 at line 8 : invalid struct entry name 0`

However, structs which have properties/keys that are strings made if digits, are possible in GM without any issues in other way:
```gml
var struct = {}
struct[$ "0"] = 1;
show_debug_message(struct[$ "0"]);
```
They even are typecasted to string if asked using... integers/enums:
```gml
enum test {
 a
};
var struct = {}
struct[$ "0"] = 1;
show_debug_message(struct[$ test.a]); // it's same as struct[$ "0"]
```
So, strings made of digits are possible, but only using accessors, not when defining struct in normal way.

### Expected Change

Make it working without accessor too.

### Steps To Reproduce

1. Start GameMaker
2. Run
```gml
var struct = {
	"0": 1,
}
```
vs.
```gml
var struct = {}
struct[$ "0"] = 1;
```
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment] 2024-08-27 13:06
This is not a bug... the `struct[$ "0" ]` is being treated as a variable name (it would be the same as just using `0` as a variable name (id), which is an invalid variable name in GML). Because it is invalid you cannot use it in a struct literal, and using the string as the key in the literal declaration is invalid GML. 

No plans to change this at this stage

**Comment by stuckie** [comment] 2024-08-28 08:45
Closing as above

**Closed by stuckie** 2024-08-28 08:45 UTC
Labels: build-bug

**Comment by gnysek** [comment] 2024-08-28 22:42
Wait wait, so this isn't possible:
```gml
var struct = {"0": 1}
```
but this is?
```gml
var struct = {true: false}
```
...

**Comment by rwkay** [comment] 2024-08-29 08:17
Yes... strings cannot be keys... but valid id's can be
