### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by Douglas711** [YoYoGames/GameMaker-Bugs#5613] opened 2024-04-23 07:16 UTC
### Description
I was just changing something small. It keeps crashing. Why

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[42644b64-90b1-4193-9618-f1c1b10925aa](https://api.gamemaker.io/api/github/downloads/42644b64-90b1-4193-9618-f1c1b10925aa)

**Comment by stuckie** [comment] 2024-04-23 09:03
Duplicate of #4906

**Closed by stuckie** 2024-04-23 09:03 UTC
Labels: crash, dump
