### ISSUE TITLE
Alt+F4 input does not close game during testing

### ISSUE THREAD

**Issue by Drillimation** [YoYoGames/GameMaker-Bugs#1636] opened 2023-09-08 18:49 UTC
### Description
Inputing the Alt+F4 combination during testing should close the game itself. No matter how many times I input the combination, nothing happens. The game does not close. If GameMaker is closed and reopened, the issue persists.

### Steps To Reproduce
This may be an IDE bug. I did not have any specific configurations or unique characteristics that led to this issue. The key combination worked in previous versions. I searched through the issue list before posting this one. I apologize if this issue is known or duplicate.

[f3a471bd-4c31-4f11-ba89-92091bbdb2ac](https://api.gamemaker.io/api/github/downloads/f3a471bd-4c31-4f11-ba89-92091bbdb2ac)

**Comment by iampremo** [comment] 2023-09-08 20:06
Duplicate of #1601

**Comment by YYDan** [comment] 2023-09-11 08:32
Closing as Duplicate - thanks for searching, and I have now pinned the original report so others can find it more easily.

**Closed by YYDan** 2023-09-11 08:32 UTC
Labels: ide-bug
