### ISSUE TITLE
There should be a way to rearrange/alphabetize texture groups or audio groups

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7015] opened 2024-07-30 16:44 UTC
### Is your feature request related to a problem?

If you have a lot of texture groups, it can be hard to find the one you're looking for if the list is all jumbled up in the order they were created. There's currently no way to alphabetize or otherwise rearrange them to make them easier to read.

![image](https://github.com/user-attachments/assets/53b5229a-217a-491d-8701-dd1354bb1987)

This is also true for audio groups, though it's less common to have this many of those.

It would also be nice if there was a way to expand this scrolling window, because right now it's pretty small and it doesn't take a lot of texture groups before the scroll bar appears.

### Describe the solution you'd like

Some kind of asset browser-like sorting for texture and audio groups. I wouldn't be opposed to adding them to the asset browser themselves, though that might be going a bit far.

The sorting order should also be stored in the resource order file.

**Comment by YYDan** [comment] 2024-07-31 08:15
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/4742

**Closed by YYDan** 2024-07-31 08:15 UTC
Labels: feature request
