### ISSUE TITLE
Error retrieving list of games when uploading to GX Games

### ISSUE THREAD

**Issue by moomoomang** [YoYoGames/GameMaker-Bugs#4394] opened 2024-01-18 04:58 UTC
### Description

When building to the GX.Games target, I get this message in the Output window:

Refreshing OAuth2 Token
Current environment: Prod
Synchronizing with Opera GX...
Starting Sign-In to Opera
Refreshing OAuth2 Token
ERROR - Retrieving List of Games
Incorrect game data received from GXC.
GXC synchronization failed

This occurs regardless of the project, and even for projects that have already been uploaded previously.

In Game Options>GX.Games>Game, the IDE fails to fetch any game info.

Contact us package
https://drive.google.com/file/d/1ACYJ7GjbGEMojcqxxKPYXD2r02Rgyulp/view?usp=sharing

### Steps To Reproduce

1. Start GameMaker
2. Change target platform to GX.Games
3. Create Executable
4. See Output window
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

GX.games

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yyalansavage** [comment] 2024-01-22 16:37
Was unable to reproduce in reported build or in latest beta ( IDE v2024.200.0.471); ui.log shows an authorization error but was not able to identify a problem in the code and all seemed to be working ok. Possibly a temporary server problem...if problem persists would suggest sign out and back in again.

**Comment by stuckie** [comment] 2024-01-23 10:18
Closing as above.
If you are able to reproduce it again, please open another ticket with as much information as you can.
Thanks.

**Closed by stuckie** 2024-01-23 10:18 UTC
Labels: ide-bug

**Comment by YYDan** [comment] 2024-02-02 15:40
Closing per the above 2 comments.
