### ISSUE TITLE
sqrt errors on small values

### ISSUE THREAD

**Issue by Gamer-XP** [YoYoGames/GameMaker-Bugs#4816] opened 2024-02-26 15:06 UTC
### Description
When you do a value comparison on a very small value - GM treats it as 0. But if you do the same with sqrt - it may throw an error if the value was negative.

So, if you check if VerySmallValueTM is >= 0 before using sqrt - it may still throw an error if the value was very small, but negative.

```
var small_value = -0.000000000000000000002323345345;
if small_value >= 0
	small_value = sqrt(small_value);
```

### Steps To Reproduce
1. Open the example and start the game
2. You'll see an error message if it reaches sqrt part

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.499 Runtime v2024.200.0.516

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[7326300a-4cf4-494e-bd7e-7925a2145348](https://api.gamemaker.io/api/github/downloads/7326300a-4cf4-494e-bd7e-7925a2145348)

**Comment by attic-stuff** [comment] 2024-02-26 15:10
i juuuuust replied to you on the forums, but just in case haha: this is not likely a bug, the epsilon is only used for comparing _not_ mathematical operations, so the sign of -0.000000000000000000002323345345 is preserved in the sqrt() call, which does not work with negative numbers.

**Comment by rwkay** [comment] 2024-02-26 15:13
How about 

```
var small_value = -0.000000000000000000002323345345;
if small_value >= 0
	small_value = sqrt(abs(small_value));
```

**Comment by Gamer-XP** [comment] 2024-02-26 15:18
Or I can check value to be 0 before calling sqrt too. But that doesn't sound as a foolproof solution since I need to remember doing it every time I use sqrt. And I can't even replace built-in sqrt with custom sqrt function. This is a good source of possible random crashes.

**Comment by attic-stuff** [comment] 2024-02-26 15:22
> This is a good source of possible random crashes.

i do not think it is, the manual describes where the epsilon kicks in pretty well and no one should expect otherwise. if the epsilon was changed to effect mathematical operations other than comparing, it would have really negative long reaching effects.

**Comment by Gamer-XP** [comment] 2024-02-26 15:29
Well, can change it so it won't break anything.
Like, if value is negative, BUT higher than -epsilon - will just return 0 instead of crashing the game.

**Comment by attic-stuff** [comment] 2024-02-26 15:32
you could put in a feature request for that, but i dont know if putting an extra branch in an already kinda slow maths function for everyone is really worth it when you can do the same check outside the function. that being said, this issue should be closed now since it is not a bug and a feature request requires a separate issue.

**Comment by Gamer-XP** [comment] 2024-02-26 15:35
It won't really slow it down. There is already a negative value check, so it will go after it. It will do a check instead of throwing an exception.

Also, I still think it's a bug because it's not really looking like something you'd expect when you check value to be above 0.

**Comment by ParodyKnaveBob** [comment] 2024-02-26 20:40
Would @Gamer-XP's solution be to simply change the `math_set_epsilon()` then?

**Comment by attic-stuff** [comment] 2024-02-26 21:15
> Would @Gamer-XP's solution be to simply change the `math_set_epsilon()` then?
> 
> EDIT: No, never mind, that function doesn't reach that many digits. Perhaps then, the real feature request should be to increase the function's reach.

this is not a rounding error. changing the epsilon changes how two numbers are compared (==, <=, >, etc) and does not effect the other math operation. even when a very small  negative number is compared to 0 and is true, when passing that number to math functions the negative sign is not ignored.

**Comment by ParodyKnaveBob** [comment] 2024-02-26 21:24
Yes, @attic-stuff, but Gamer-XP is **first** comparing in order to prevent the math from crashing.
```javascript
var small_value = -0.000000000000000000002323345345;
if small_value >= 0
	small_value = sqrt(small_value);
```
I'm suggesting Gamer-XP to request the feature of [`math_set_epsilon()` going past what the manual describes](https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FMaths_And_Numbers%2FNumber_Functions%2Fmath_set_epsilon.htm)...

> The new epsilon value (from 0 to 0.999999999).

... in order to get a more proper `if small_value >= 0` branch of `false` to thus skip `small_value = sqrt(small_value);`.

**Comment by Gamer-XP** [comment] 2024-02-27 04:07
My main issue is that this is VERY non-obvious behavior. I mean, anyone who will see game crash after they check value to be >= 0 will be very confused. I had this error before, but only just now I managed to catch it in debug to see the real issue behind it. Such basic math operation should not be THAT hard to work with. It feels like it was never adapted to GM's environtment properly.

Secondary issue is that all extra checks I have to add will affect performance. On the other hand, adding that check on sqrt side will not affect it since it will handle only rare edge case of very small negative value.

---

Other way to handle this case... well, this may lead to other issues, so better not, but can make it so >= will never pass if value is negative, even if very small.

**Comment by rwkay** [comment] 2024-02-27 11:29
Fixed in 2024.4 - now sqrt checks value against -epsilon then clamps anything negative to 0 before calculating the sqrt.

**Closed by rwkay** 2024-02-27 11:29 UTC
Labels: runner-bug, project

**Comment by ParodyKnaveBob** [comment] 2024-02-29 06:02
Mr. Russell, (@rwkay,) I disagree with your solution, and this is why:

*(**Summary:** It's inconsistent, we can already use `sign`, and the manual could fix this whole thing.)*

You have striven a lot to keep things consistent, often changing big ways the runner even worked back in the GM:HTML5 days just to make sure everything worked in tandem as expected. Your solution causes one **and only one** math function to operate inconsistently vs. every other math function -- a unique exception that should be documented.

If you don't want to change the `math_set_epsilon` function to be able to dig deeper for precision, that's fine **because** in order to check if a number is merely `>= 0` -- the problem prompting your solution -- we already have the ability to skip rounding issues and use your age-old built-in `sign` function, as I wrote here some two days ago, [the same conclusion](https://forum.gamemaker.io/index.php?threads/2024-200-betas-release-thread.108555/page-2#post-658847) @Alphish reached on the GMC, quite clearly independent of this bug report's comments. This already present solution doesn't **need** documentation, in that it's the kind of reason this function has **existed** for decades now.

However, being that `negative_small_magnitude >= 0` works as intended but can surprise a user, especially when relying on it to avoid any math functions that could crash -- namely `sqrt` -- I believe the best and simplest route would be **restoring** functionality to be the exact same **and adding a helpful blurb** to [the relevant manual page](https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FMaths_And_Numbers%2FNumber_Functions%2Fsqrt.htm)(s), in both Note and Example forms. For instance, I propose changing `sqrt`'s manual page example from...
```gml
num = sqrt(exp);
```
> The above code will set the variable "num" to hold the square root of the value contained in "exp".

...to...
```gml
if (sign(num) > -1) {
    root = sqrt(num);
}
```
> The above code will check the sign of the value contained in "num". If it is not negative, then set the variable "root" to hold the square root of "num".

(...and of course take your pick on `> -1`, `!= -1`, `>= 0`, whatever).

**Comment by rwkay** [comment] 2024-02-29 09:59
I disagree with your assessment the C++ code was incorrectly guarding against <0 when passing it into the C++ function sqrt it should have been guarding against < -epsilon as that is all the GML code can guard against.

The fix stands and it is not an outlier, other functions are epsilon aware.

**Comment by ParodyKnaveBob** [comment] 2024-02-29 16:27
My happy mistake! I took @attic-stuff's statement at face value (instead of testing it myself, sorry,) that math functions surprisingly didn't use the epsilon. Since you say they do, like should be expected, I'm glad to see a proper fix, then! Tyvm. $:^ ]

**Comment by attic-stuff** [comment] 2024-02-29 20:07
then the manual should be updated to reflect this, since it says that the epsilon value is only used for <, >, <=, >=, !=, and ==

**Comment by YYBartT** [comment] 2024-04-24 15:18
The `sqrt` part of this ticket is now documented with a note and will be in the next release of the manual. The new ticket for the more general case of the inconsistencies can be found here: https://github.com/YoYoGames/GameMaker-Bugs/issues/5132

**Comment by mgeddesGM** [comment] 2024-04-30 10:46
verified as of  IDE v2024.400.0.555  Runtime v2024.400.0.569
