### ISSUE TITLE
Remove room speed restriction on Box2D

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GameMaker-Bugs#7212] opened 2024-08-11 14:21 UTC
### Is your feature request related to a problem?

With the current Box2D implementation, we cannot interfere with the physics timer - in such cases where we need to slow down the simulation.

### Describe the solution you'd like

Remove the room speed restriction at the Box2D world step.

**Comment by YYDan** [comment] 2024-08-12 08:29
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6994

**Closed by YYDan** 2024-08-12 08:29 UTC
Labels: feature request
