### ISSUE TITLE
CE2 - Tab spacing is broken

### ISSUE THREAD

**Issue by Hyomoto** [YoYoGames/GameMaker-Bugs#6810] opened 2024-07-20 20:51 UTC
### Description
Tabs only work properly when starting a line. You can see the tab separation at start of the line, but if you put a tab in the middle of the line it will simply push it to the furthest extent of the tab rather than aligning to the neartest column.  This doesn't happen when the tab type is set to spaces.

### Steps To Reproduce
We can see the tab columns clearly in the right image, using the prior editor and how everything aligns nicely.  Open the same code in CE2 and we get the left image where anything tabbed at the start of the line works as expected, but any tabs later in the line just behave as "full length" tabs and do not align with the expected columns.

Probably related to https://github.com/YoYoGames/GameMaker-Bugs/issues/6452 but I didn't see that until after posting this since it seems to suggest it has something to do with = and it appears, from my tests, to happen any time a tab is used after a line has started.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

### Attached Files:
spacing.png

[efa64722-7993-45e9-96df-95f597a89d5a](https://api.gamemaker.io/api/github/downloads/efa64722-7993-45e9-96df-95f597a89d5a)

**Comment by stuckie** [comment] 2024-07-22 09:08
Duplicate of #6452

**Closed by stuckie** 2024-07-22 09:08 UTC
Labels: ide-bug
