### ISSUE TITLE
In-Game: Constructor inheritance is broken in internal 2024.1100 Beta, due to new code error that was added

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7752] opened 2024-09-24 05:27 UTC
### Description
The following code is now broken:
```gml
function parent() constructor{}
function children(): parent() constructor{}
function grandchildren(): children() constructor{}

new parent();
new children();
new grandchildren();
```
Where instantiating `children` throws the error:
```
calling a constructor directly - constructors should only be called using new
 at gml_Script_parent (line 2) - function children(): parent() constructor{}
```

### Steps To Reproduce
1. Run the sample project in windows VM

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.624 Runtime v2024.1100.0.652

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[e7233255-1e18-4efc-af86-982ecd7c6a06](https://api.gamemaker.io/api/github/downloads/e7233255-1e18-4efc-af86-982ecd7c6a06)

**Comment by rwkay** [comment] 2024-09-24 21:19
OK this is a bug but not the one you think it is...

you are using the wrong syntax there is no need for the brackets after the base function name... i.e. it should be `function children() : parent constructor { }` notice the `parent` with no brackets (so it is not a function call)

 I will fix the bug that it is not erroring when the brackets are present...
 
 currently this is generating two calls to the base constructor which will cause some... errr...  oddities.

Not sure why this has leaked into the general consciousness as I see several bugs with the same constructs

**Comment by rwkay** [comment] 2024-09-25 00:29
OK so looks like I had anticipated this on YYC and HTML5 but for some reason I did not check VM...

**Comment by rwkay** [comment] 2024-09-25 00:53
Apologies... fixed in 2024.11 - YYC and HTML5 is working but VM was broken... fixed now

**Closed by rwkay** 2024-09-25 00:53 UTC
Labels: runner-bug, project

**Comment by Shoozes** [comment] 2024-09-26 03:21
Is this issue related?

So with the "new" runtime exception, how would you go about instantiating constructors dynamically? It seems the use of child/parent constructors is the issue here which may actually be incorrectly calling the error.


For example, this would work previously, but now returns the "new" error:


```
function inst_create(actor_struct, xx, yy, zz) {
	if (is_struct(actor_struct)) {
	    // Check if actor_struct is a constructor and apply 'new' explicitly
	    var new_instance = new actor_struct(); //<---- using 'new' right here

	    // Add the new instance to the global array and assign its index
	    new_instance.ind = array_length(global.instances_array);
	    global.instances_array[new_instance.ind] = new_instance;

	    // Assign the properties to the instance
	    new_instance.pos = [xx, yy, zz];
	    new_instance.create();

	    return new_instance; // Return the new instance for external use
	}
    }
}

// Define actor constructor child of mini_instance() constructor
act_tree = function inst_tree() : mini_instance() constructor { } 
inst_create(act_tree, 0, 0, 0); // Instantiate actor constructor
```

Returns the error:
calling a constructor directly - constructors should only be called using new

**Comment by YYDan** [comment] 2024-09-30 13:13
Reproduced the issue in IDE v2024.1100.0.629 Beta Runtime v2024.1100.0.652, works fine in the same IDE with Runtime v2024.1100.0.654
