### ISSUE TITLE
Num Lock deactivated by default on GameMaker launch

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2105] opened 2023-11-05 00:12 UTC
### Description
Each time GameMaker is launched, it either deactivates the keyboard's Num Lock key or believes that the keyboard's Num Lock status is turned off.  As a result, when using the numeric keyboard to enter numbers into the script editor (or anywhere else that accepts text input), they numeric keypad keys behaves like arrow keys instead of inputting text.  I am forced to hit the Num Lock key to be able to enter numbers with the keypad.  If I shut down GameMaker and launch it again, the Num Lock status is once again deactivated.

Note: I am using a Steelseries Apex Pro on a Mac, if that makes any difference.

### Steps To Reproduce
1) Launch GameMaker
2) Open the script editor
3) Type keys on the numeric keypad and observe that no numbers are actually inputted into the script editor, but moves the cursor around as though I were hitting the arrow keys.
4) Press Num Lock.
5) Type keys on the numeric keypad and observe that numbers are now being entered into the script editor.
6) Quit GameMaker.
7) Re-Launch GameMaker.
8) Goto #3.

[bf69d267-554e-4dbd-95f5-480d69f9e183](https://api.gamemaker.io/api/github/downloads/bf69d267-554e-4dbd-95f5-480d69f9e183)

**Comment by YYDan** [comment] 2023-11-06 10:49
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/862

**Closed by YYDan** 2023-11-06 10:49 UTC
Labels: ide-bug
