### ISSUE TITLE
In Game: Left/right audio seems reversed when using audio emitters/listeners

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#157] opened 2023-07-28 12:34 UTC
GM-3090

If you use an instance's X and Y position for its listener/emitter, the audio will appear swapped.

For example, if EmitterA is to the left of ListenerA, the audio will come from the right speaker.
h3. Reproducing

See the attached project for an example. Press LMB to move the emitter.

To fix this, you need to change the listener's orientation with the following line of code:

{{audio_listener_orientation(0, 0, -1, 0, 1, 0);}}

**Comment by toby-yoyo** [comment] 2024-11-07 16:58
As documented in the [manual](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Audio/Audio_Listeners/audio_listener_set_orientation.htm) (and shown in the image below), the default listener orientation has its up-y value set to 1, which places it upside-down relative to how sounds are intuitively perceived. This is the reason the sound comes from the left instead of the right as you might expect. Setting up the intended orientation of the listener is standard practice when working with positional audio.
![Image](https://github.com/user-attachments/assets/7cc40c83-37f3-4d05-a9de-d70679b382ed)

Closing as 'not a bug'.

**Closed by toby-yoyo** 2024-11-07 16:58 UTC
Labels: runner-bug, import
