### ISSUE TITLE
[Ubuntu] Fail to compile appimage on latest version

### ISSUE THREAD

**Issue by SunCatMC** [YoYoGames/GameMaker-Bugs#6364] opened 2024-06-21 10:33 UTC
### Description
I updated gm, decided to compile my project on new version, but it failed

```
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at Igor.LinuxBuilder.plink_async(String command, Boolean fail_on_error)
   at Igor.LinuxBuilder.BuildAppImage(String work_dir, String exe_path, String assets_zip_path, String projectName, Boolean package)
   at Igor.LinuxBuilder.Package()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Igor complete.
```

compiling as zip on the other hand is successful

### Steps To Reproduce
- Grab the project
- Compile as appimage

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Linux Ubuntu 24.04 LTS kernel 6.8.0.35

### Which platform(s) are you seeing the problem on?
Ubuntu

[8bcc9068-7572-45fe-ab26-0919d9d01d97](https://api.gamemaker.io/api/github/downloads/8bcc9068-7572-45fe-ab26-0919d9d01d97)

**Comment by YYDan** [comment] 2024-06-21 11:18
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6326

**Closed by YYDan** 2024-06-21 11:18 UTC
Labels: build-bug, project
