### ISSUE TITLE
[PS5] audio_sound_gain error

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#117] opened 2023-07-28 12:32 UTC
GM-4775

When running your game on PS5, if you run the audio_sound_gain function with the secondary input being global.SoundON, your game will flag an error up and then present you with the option to close the game.

 

Steps to reproduce:
 # Import attached project
 # Run project on PS5
 # Observe

**Comment by toby-yoyo** [comment] 2024-11-08 10:32
The original ticket this was created from was already closed as 'not a bug'. This was also verified by the developer that submitted the project.

See the relevant issues below:
- https://bugs.opera.com/browse/GM-4775
- https://bugs.opera.com/browse/GM-4776

Closing this one as 'not a bug' too.

**Closed by toby-yoyo** 2024-11-08 10:32 UTC
Labels: runner-bug, import
