### ISSUE TITLE
Getting rid of GUID in image(s) names especially when replacing sprites

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#3238] opened 2023-06-13 16:17 UTC
### Is your feature request related to a problem?

Currently, when replacing sprite using "Load image", it will get new random name (GUID.png) for each frame.
This is highly unuseful, when re-importing images exported from graphical tools like Photoshop/Krita/Affinity, and also works very bad with .git, as doesn't help to follow changes between versions (github allows to compare images when checking diff, same for some tools like Beyond Compare).

### Describe the solution you'd like

When replacing images, especially if amount of frames is same, frames should keep same names.

Preferable names are:

`<sprite_name>_frame_<n>.png` for frames and
`<sprite_name>_frame_<n>_layer<m>.png` for layers for each frame

**Comment by stuckie** [comment] 2024-03-25 18:19
Closing as duplicate of #5104

**Closed by stuckie** 2024-03-25 18:19 UTC
Labels: feature request
