### ISSUE TITLE
Make global search and replace work with the variable definitions window 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#3042] opened 2023-08-06 09:28 UTC
### Is your feature request related to a problem?

Not sure if this one has been requested already, but I looked a bit and didn't see it so I'm going ahead and submitting this request for it.
Refactoring or changing variable names when they're defined in variable definitions can be annoying, since search and replace does not work in the variable definitions window. It can also be difficult to track down mistakes that happened in variable definitions when they don't appear in the search.

### Describe the solution you'd like

Make it so variable definitions content appears in search and replace, and can be changed by the replace button.

**Comment by YYDan** [comment] 2024-06-10 08:59
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1287

**Closed by YYDan** 2024-06-10 08:59 UTC
Labels: feature request
