### ISSUE TITLE
middle clicking function opens manual landing page, not relevant page

### ISSUE THREAD

**Issue by jack27121** [YoYoGames/GameMaker-Bugs#2670] opened 2024-01-08 02:50 UTC
### Description
middle clicking function opens manual landing page, not relevant page.

The url looks to be relevant, but regardless it's not the right page when you see
https://manual.gamemaker.io/monthly/en/index.htm#t=%23t%3DGameMaker_Language%252FGML_Reference%252FGame_Input%252FKeyboard_Input%252Fkeyboard_check.htm

### Steps To Reproduce
middle click a function

[7e301171-7f9f-4c46-b2bf-e05d954eaeb5](https://api.gamemaker.io/api/github/downloads/7e301171-7f9f-4c46-b2bf-e05d954eaeb5)

**Comment by stuckie** [comment] 2024-01-08 10:45
Duplicate of #2660

**Closed by stuckie** 2024-01-08 10:45 UTC
Labels: ide-bug
