### ISSUE TITLE
Code editor 2: Copy pasting, deleting, and enter always are applied to the top of the first tab open

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5631] opened 2024-04-24 07:23 UTC
### Description
Edit: I just realized this bug also applies to the enter key, so I suspect it may be the same source issue as #5560 since the same keys are involved in each.

As of the latest beta, copy pasting will paste into a completely different document from the one currently selected.

(don't mind the tooltip, that's the persistent tooltip bug)

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/af2cfaae-8a2b-4a19-ade0-c10d42a6142d

The delete key is similar, it will always delete whatever is at the top of the first tab if you have multiple open

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/70e9e234-86f0-4887-86d0-ee67e15d6f5d

### Steps To Reproduce
Open two code tabs. Copy some code, then try to paste it into the 2nd tab. It will paste into the first tab instead. Now try to delete some code in the 2nd tab. It will delete from the first tab instead.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.549 Runtime v2024.400.0.567

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7b473fc8-2ee8-4ae6-b876-5198e879dc4f](https://api.gamemaker.io/api/github/downloads/7b473fc8-2ee8-4ae6-b876-5198e879dc4f)

**Comment by Bubblesloth** [comment] 2024-04-24 12:05
I have the same bug, If you find a solution please tell me
I can't work anymore :(

**Comment by KormexGit** [comment] 2024-05-24 16:22
In the 2024.6 beta that came out today, backspace, enter, copy, and paste are fixed. However it appears some other keys still apply to the first tab, such as ctrl + A, page up, page down, ctrl + q, and delete (specifically the delete key, not backspace)

**Comment by zreedy** [comment] 2024-06-04 16:25
This bug was related to hotkey regression issues, all of which are fixed.

**Comment by zreedy** [comment] 2024-06-04 16:31
Marking as fixed since all issues appear fixed now.

**Closed by zreedy** 2024-06-04 16:31 UTC
Labels: ide-bug

**Comment by mgeddesGM** [comment] 2024-06-10 11:45
verified as of  IDE v2024.600.0.571  Runtime v2024.600.0.597
