### ISSUE TITLE
Code Editor 2: Changing font size while editor is open makes random letters appear instead of the actual code

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#5250] opened 2024-04-02 21:47 UTC
### Description

When using CE2, changing font size (in my case it was Jetbrains Mono, from size 10 to 11), code started to display as some random letters:

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/9b71a144-aad8-4bd1-a8a7-6c525ae9545f)

However it was only visual - changing font back from 11 to 10 made it readable again:

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/bd2659cc-7cf6-4420-96c1-772f5b25026b)

### Steps To Reproduce

1. Start GameMaker
2. Open preferences while code editor is active, go to CE2 > Theme, change font size
3. Observe random letters
4. Change font size again - and random letters are gone

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

**Comment by DragoniteSpam** [comment] 2024-04-02 22:07
this is actually the secret key by the GameMaker illuminati to divulge the release date of New Runtime

**Comment by zreedy** [comment] 2024-04-10 15:44
Probably related to https://github.com/YoYoGames/GameMaker-Bugs/issues/5300
Unable to reproduce, suspected GPU-specific issue.

**Comment by zreedy** [comment] 2024-06-04 18:37
This issue was most likely related to a fix to the cache key resolvement, which was fixed with last month's Font Rendering bug fixes.

**Comment by caitlinrmcintyre** [comment] 2024-06-06 11:32
Reopening this as changing the font size is now causing the IDE to go unstable.

**Comment by zreedy** [comment] 2024-06-06 19:11
Regression on this ticket is related to regression on https://github.com/YoYoGames/GameMaker-Bugs/issues/5787 which is now fixed.

**Closed** 2024-06-18 14:28 UTC
Labels: ide-bug

**Comment by mgeddesGM** [comment] 2024-07-15 13:53
verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
