### ISSUE TITLE
GM froze and then crashed with no error message after creating a sprite, renaming it, and then trying to open it

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4928] opened 2024-03-07 01:49 UTC
### Description
I duplicated a sprite, imported a new sprite over it, renamed it, and then double clicked on it to focus it in the workspace GM froze for a while, and then eventually closed.
Edit: Dragonite informed me this is the same as #4906, changing my config back to default made it stop crashing. Gonna leave this open in case the log files here help at all with tracking it down

### Steps To Reproduce
Edit: I just reopened GM, and trying to open the sprite again made GM crash again in the exact same way

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[3f254908-5efa-4413-8653-e25ff0f0a7c6](https://api.gamemaker.io/api/github/downloads/3f254908-5efa-4413-8653-e25ff0f0a7c6)

**Comment by stuckie** [comment] 2024-03-08 10:24
Resolving as duplicate of #4906

**Closed by stuckie** 2024-03-08 10:24 UTC
Labels: crash, dump
