### ISSUE TITLE
Ignore region name text in search results when "ignore comments" is checked

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7842] opened 2024-10-01 02:07 UTC
### Is your feature request related to a problem?

These should be treated as comments as far as code search is concerned:

![image](https://github.com/user-attachments/assets/ff943500-1f06-45d6-aba8-0974f3df7f3a)

### Describe the solution you'd like

Region text is treated like comment texct

**Comment by YYDan** [comment] 2024-10-01 08:46
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5883

**Closed by YYDan** 2024-10-01 08:46 UTC
Labels: feature request
