### ISSUE TITLE
In Game: layer_tilemap_get_id is not working correctly for layers created at runtime

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#342] opened 2023-07-28 12:43 UTC
GM-705

Issue:
 layer_tilemap_get_id is not working correctly for layers created at runtime

Repro:
# Import attached project
# Run project
# Observe output shows tilemap_set() - couldn't find specified tilemap

**Comment by YYDan** [comment] 2023-09-12 16:30
Duplicate of #1662

**Closed by YYDan** 2023-09-12 16:30 UTC
Labels: runner-bug, import
