### ISSUE TITLE
In Game: part_system_create_layer is not working like last versions

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5758] opened 2024-05-05 05:12 UTC
### Description
I create a particle system in a specify layer, in the last version this was working as expected now it throw the next error:

############################################################################################
ERROR in
action number 1
of Create Event
for object oStaticLight:

part_system_create_layer argument 1 invalid reference to (layer) - requested 216 max is -1
 at gml_Script_anon@6161@anon@5744@gml_Object_oCoFernando_Create_0 (line 214) -                             partsys = part_system_create_layer(layer, false, psCoCanalizarCargar);
############################################################################################
gml_Script_anon@6161@anon@5744@gml_Object_oCoFernando_Create_0 (line 214)
gml_Script_event@anon@1133@VueltaMethod@vt_Method (line 34)
gml_Script___update@anon@1442@VueltaManager@vt_Manager (line 81) -                             _eventReady = event();

### Steps To Reproduce
1) Check oCoFernando create event
2) see anaimCanalizar method.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[bf21f86d-059b-431a-a66b-6a036acd483f](https://api.gamemaker.io/api/github/downloads/bf21f86d-059b-431a-a66b-6a036acd483f)

**Comment by pkraif** [comment] 2024-05-07 09:30
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5728

**Closed by pkraif** 2024-05-07 09:30 UTC
Labels: runner-bug, project
