### ISSUE TITLE
Stability: [Ubuntu IDE] Random freezing and subsequent crashes

### ISSUE THREAD

**Issue by atesingucu** [YoYoGames/GameMaker-Bugs#5675] opened 2024-04-29 04:41 UTC
### Description

Unfortunately I can't use the program. 

### Steps To Reproduce

1. Start GameMaker
2. I wait a while and then it freezes.
3. Then it shut down even though I didn't send a shutdown signal.
4. It froze even though I installed the necessary packages.
5. See the issue

Terminal Code;

/opt/GameMaker-Beta/GameMaker %F

No LSB modules are available.
CrashDumpInit:Exception:System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps/dump_pid'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.AppendAllText(String path, String contents)
   at YoYoStudio.Program.CrashDumpInit()
Starting......
Critical: Doing Validate Folder check... %F macOS=False
**************************************  04/26/2024  **************************************
Logger.Initialise
Skin: /opt/GameMaker-Beta/x86_64/GUI/Skins/Dark
GameMaker, Version=2024.400.0.549, Culture=neutral, PublicKeyToken=null
Initialise()
Command line arguments:
%F
ProcessId:6479
SteamAPI Init returned : False
Loading proxy settings
Discovered system fonts via kernel in 0ms
Initialise(0.0)
File exception 'Could not find a part of the path '/opt/GameMaker-Beta/x86_64/user_cache_directory/Styles'.'
Failed to load layout 'OperaGXDeviceEditor' from file '/opt/GameMaker-Beta/x86_64/GUI/Skins/Dark/Layouts/build_platform_device_editor.xml' as it has a duplicate name
Failed to load layout 'ObjectEditorEvents' from file '/opt/GameMaker-Beta/x86_64/GUI/Skins/Dark/Layouts/object_editor_layouts.xml' as it has a duplicate name
Layout Manager: Attempting to register 'YoYoStudio.GUI.Gadgets.Inspector.MultiSelectListBox+ItemGadget' from assembly 'IDE'. The gadget name 'ItemGadget' is already in use, this may be caused by conflicting plugins
Initialise(0.1)
Prefs: Error loading ${system_directory}/org_settings.json
Prefs: file not found
Prefs: Error loading ${system_directory}/machine_settings.json
Prefs: file not found
Prefs: Error loading ${system_directory}/language_settings.json
Prefs: file not found
Local Pref - machine.General Settings.Environment.Prev Environment = 0
Local Pref - machine.General Settings.Environment.Prev Path to Environment =
Local Pref - machine.General Settings.Environment.Prev Environment = 0
Local Pref - machine.General Settings.Environment.Prev Path to Environment =
Initialise(0.2)
Initialise(1)
Initialise(1.1)
Initialise(2)
Font that isn't scalable is invalid: /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf
Discovered system fonts via filesystem in 731ms
Discovered 317 fonts in 67ms.
Using 0.006037712mb in font ram cache
Initialise(3)
Initialise(4)
FNA-Info: FNA3D Driver: OpenGL
FNA-Info: OpenGL Renderer: NVC1
FNA-Info: OpenGL Driver: 4.3 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
FNA-Info: OpenGL Vendor: Mesa
FNA-Info: MojoShader Profile: glsl120
Initialise(4.1)
Initialise(4.2)
Initialise(4.3)
Initialise(4.4.1)
Initialise(4.4.2)
Image Loading exception ImageMagick.MagickMissingDelegateErrorException: NoDecodeDelegateForThisImageFormat `ICO' @ error/blob.c/CustomStreamToImage/806
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadStream(IMagickSettings`1 settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller) in /_/src/Magick.NET/Native/MagickImageCollection.cs:line 844
   at ImageMagick.MagickImageCollection.AddImages(Stream stream, IMagickReadSettings`1 readSettings, Boolean ping) in /_/src/Magick.NET/MagickImageCollection.cs:line 2030
   at YoYoStudio.Core.Utils.YoYoImage.CreateFromStream(Stream _baseStream, String _filename)
Initialise(4.5)
Check (1)
Check (2)
Initialise(4.6)
Initialise(4.7)
Initialise(4.8)
Initialise(4.9)
Initialise(4.10)
Initialise(4.11)
Initialise(4.12)
Initialise(5)
Initialise(6)
Initialise(7)
Initialise(7.1)
Initialise(8)
Initialise(9)
Initialise(10)
LoadingState: AwaitNetworkConnectivityCheck
Initialise(11)
Initialise(11.5)
Initialise(12)
Audio Device Connected: PCM2902 Audio Codec Analog Stereo
Audio Device Connected: Dahili Ses Sayısal Stereo (IEC958)
Checking network....
LoadingState: StartUp
LoadingState: Languages
Startup Language:
LoadingState: BeginUserLogin
LoadingState: UserLogin
Current assembly revision is 2024.400.0.549
Update found - got 78 items
Latest revision 2024.400.0.549 found
We do NOT need to update
LoadingState: Preferences
Local Pref - machine.General Settings.Environment.Prev Environment = 0
Local Pref - machine.General Settings.Environment.Prev Path to Environment =
Prefs: Error loading ${user_directory}/cloud_settings.json
Prefs: file not found
Prefs: Error loading ${user_directory}/local_settings.json
Prefs: file not found
Creating temp directory /tmp/GameMakerStudio2-Beta/GMS2TEMP
LoadingState: CheckingRSS
LoadingState: DownloadManualRSS
Download File /home/atesingucu/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.400.0.567/379ac8b5update-manual-beta.rss to https://gms.yoyogames.com/update-manual-beta.rss
LoadingState: InitDnD
DnD: Installing gadgets from IDE
Discarding document c9f89f5a-0e2d-40a4-b668-3fe039e0a8dd.gml
DnD: Gadget name conflict on YoYo Games.DnD_CodeInput, change gadget name.
DnD: Gadget name conflict on YoYo Games.DnD_CodeInput, change gadget name.
LoadingState: PluginGUIResources
LoadingState: AddPluginsToLoadQueue
LoadingState: ResolvePluginLoadQueue
LoadingState: LoadPlugins
LoadingState: Devices
Splash screen: loading devices...
...initialising device manager
Device Manager Load Failed: file not found
...moving to welcome page end
LoadingState: CheckLaunchProject
...done!
LoadingState: VerifySkinning
LoadingState: End
Adding fnames: /home/atesingucu/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.400.0.567/operagx/fnames
MQTT - Started server: mqtts://unknownUser:756E6B6E6F776E55736572@192.168.1.45:9001?thumbprint=C7EAF318AC25ADD2C4DF0E6B5C5090D525B76036&thumprint256=5A4AFCD825603E876C3B24510249F35CA4307B4281C9177C2F3DE5288C9905C5&topic=GameMaker
MQTT - Subscribed to GameMaker/goodbye with GameMaker/goodbye
MQTT - Subscribed to GameMaker/GameMaker/logs with GameMaker/GameMaker/logs
MQTT - Subscribed to GameMaker/event/# with GameMaker/event
MQTT - Subscribed to GameMaker/all/startGame with GameMaker/all/startGame
MQTT - Subscribed to GameMaker/hello with GameMaker/hello
envDumpName:
CrashReporter:Dump directory: /home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps
####################################
####################################
Break in WriteBinary (FileSystem_Local_NonAsync:618)
Break in WriteBinary (FileSystem_Local_NonAsync:618)
Reason: Could not find a part of the path '/home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps/dump_pid.new'. ( /home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps/dump_pid )
Reason: Could not find a part of the path '/home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps/timestamp.new'. ( /home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps/timestamp )
####################################
####################################
File exception 'Could not find a part of the path '/home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps/timestamp.new'.'
File exception 'Could not find a part of the path '/home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps/dump_pid.new'.'
File exception 'Could not find a part of the path '/home/atesingucu/.local/share/GameMakerStudio2-Beta/Dumps'.'
LanguageManager - Initialize
LspConfig - Process - "GameMakerLanguageServer" "" (source.gml)
StartScreen Init: Display Size w:1920 h:1010 dpiScale:1.0625
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 307.8912ms
Started: 04/26/2024 11:59:13
Finished: 04/26/2024 11:59:13
Diff: 00:00:00.3105627
ParticleEditor: registered 11 GMPresets
MQTT - Received msg: GameMaker/event/start_ide/client_version = 2024.400.0.549
MQTT - Received msg: GameMaker/event/start_ide/os_type = linux
MQTT - Received msg: GameMaker/event/start_ide/num_cpu = 6
MQTT - Received msg: GameMaker/event/start_ide/cpu_type =  AMD FX(tm)-6300 Six-Core Processor
MQTT - Received msg: GameMaker/event/start_ide/language = tr
MQTT - Received msg: GameMaker/event/start_ide/country = TR
MQTT - Received msg: GameMaker/event/start_ide/culture = tr-TR
MQTT - Received msg: GameMaker/event/start_ide/gfx_renderer = OpenGL, 4.3 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2, Mesa, NVC1
MQTT - Received msg: GameMaker/event/start_ide/laptop = 0
MQTT - Received msg: GameMaker/event/start_ide/laptop_mode = True
MQTT - Received msg: GameMaker/event/start_ide/laptop_desktop_enable = False
MQTT - Received msg: GameMaker/event/start_ide/seat_type = default
MQTT - Received msg: GameMaker/event/start_ide/is_free = 1
MQTT - Received msg: GameMaker/event/start_ide/is_internal = 0
MQTT - Received msg: GameMaker/event/start_ide/platform_os_version = Linux Mint 21.3 kernel 5.15.0.105
MQTT - Received msg: GameMaker/event/start_ide/beta_optin = False
MQTT - Received msg: GameMaker/event/start_ide/splash = 0
MQTT - Received msg: GameMaker/event/start_ide/telemetry = 343
MQTT - Received msg: GameMaker/event/start_ide/telemetry2 = EAAAAJs6OMUUvY49MQPXzSApNSawLI5BwEyyjiL5GEIHyheG
MQTT - Received msg: GameMaker/event/start_ide/data1 = operagx,operagx.build_module,test
MQTT - Received msg: GameMaker/event/start_ide/region = 235
MQTT - Received msg: GameMaker/event/start_ide/ide_language = English / English
MQTT - Received msg: GameMaker/event/start_ide/ide_font = Open Sans
MQTT - Received msg: GameMaker/event/start_ide/manual_language = English / English
MQTT - Received msg: GameMaker/event/start_ide/online_manual = False
MQTT - Received msg: GameMaker/event/start_ide/ide_skin = Dark
MQTT - Received msg: GameMaker/event/start_ide/is_steam = False
MQTT - Received msg: GameMaker/event/start_ide/quick_access = True
MQTT - Received msg: GameMaker/event/start_ide/feather_enabled = True
MQTT - Received msg: GameMaker/event/start_ide/rtl_enabled = False
MQTT - Received msg: GameMaker/event/start_ide/script_language = None
MQTT - Received msg: GameMaker/event/start_ide/fullscreen_script = False
MQTT - Received msg: GameMaker/event/start_ide/fullscreen_shader = False
MQTT - Received msg: GameMaker/event/start_ide/fullscreen_event = False
MQTT - Received msg: GameMaker/event/start_ide/gmpm =
MQTT - Received msg: GameMaker/event/start_ide/remaps_file = False
MQTT - Received msg: GameMaker/event/start_ide/snippets_file = False
MQTT - Received msg: GameMaker/event/start_ide/ce2_enabled = False
MQTT - Received msg: GameMaker/event/start_ide/editor_object_editor = 1
ProcessCrashDumps failed to find files
{"4":{"position":4,"title":"Education","link":"https://gamemaker.io/en/education","modal_title":"Education","modal_description":"GameMaker Education","image_url":"https://dvovpqt3h0n7u.cloudfront.net/1xome2fyebt3cawgn0p3ximdqujb","modal_image_url":"https://dvovpqt3h0n7u.cloudfront.net/2mcf7rz9rw6js5xbrkbmjkiju6sj","subscription_type":"all","meta_data":{}},"3":{"position":3,"title":"Youtube","link":"https://www.youtube.com/@GameMakerEngine","modal_title":"Video Tutorials","modal_description":"GameMaker Video Tutorials","image_url":"https://dvovpqt3h0n7u.cloudfront.net/yfy9hvahwc3bcektsrv2eurgexj9","modal_image_url":"https://dvovpqt3h0n7u.cloudfront.net/0wud4d1aa5ekk52ogi0jnops27zh","subscription_type":"all","meta_data":{}},"1":{"position":1,"title":"Tutorials","link":"https://gamemaker.io/en/tutorials","modal_title":"Tutorials","modal_description":"GameMaker Beginner Tutorials","image_url":"https://dvovpqt3h0n7u.cloudfront.net/7dy5gjwxamhaqtdewcf0yrrvfnox","modal_image_url":"https://dvovpqt3h0n7u.cloudfront.net/hpqwt497z8fn2dmbq5f04w8pta7g","subscription_type":"all","meta_data":{}},"2":{"position":2,"title":"News \u0026 Blogs","link":"https://gamemaker.io/en/blog/category/beginner","modal_title":"Blogs","modal_description":"GameMaker Blogs","image_url":"https://dvovpqt3h0n7u.cloudfront.net/g3h01lpewgfym6y9c1g0djusl7ig","modal_image_url":"https://dvovpqt3h0n7u.cloudfront.net/7f336m10t4ba8aghmoo687c32972","subscription_type":"all","meta_data":{}},"0":{"position":0,"title":"Space Rocks Tutorial","link":"https://gamemaker.io/en/tutorials/make-arcade-space-shooter","modal_title":"Space Rocks","modal_description":"SPACE ROCKS:\r\nMAKE YOUR OWN ARCADE CLASSIC","image_url":"https://dvovpqt3h0n7u.cloudfront.net/zkzj1ms5lqg9ssue4q34fmp6kc46","modal_image_url":"https://dvovpqt3h0n7u.cloudfront.net/ynhszq0o0dwi4d33xq3x31ip1aq0","subscription_type":"all","meta_data":{}}

Forum: https://forum.gamemaker.io/index.php?threads/game-maker-studio-2-some-problem-from-linux.111838/

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by atesingucu** [comment] 2024-04-29 15:42
My problem is not solved. I still can't use the program.

**Comment by stuckie** [comment] 2024-11-01 17:49
The November betas have had various stability fixes for random issues like this, so I'm hoping that your issue is now fixed.
If you can upgrade and let us know, that would be helpful, as the later IDEs will also give more complete logs and bug reports, which would help pin down and problems should it still occur.

As I was not able to reproduce this here, and you weren't able to give me any further information, I'm going to close this ticket now.
Again, if upgrading to the November betas still give you trouble, then please file a new issue so we can get more information.

Thanks!

**Closed by stuckie** 2024-11-01 17:49 UTC
Labels: ide-bug
