### ISSUE TITLE
F2 to rename layer goes to rename "inspector" instead

### ISSUE THREAD

**Issue by arzulo** [YoYoGames/GameMaker-Bugs#4855] opened 2024-03-02 10:06 UTC
### Description
As the title says, if you try to click the rename hotkey (F2) to rename a layer within a room, it instead is focused on the "inspector" tab and tries to rename that.
It is not possilbe to rename a layer with F2 right now.

### Steps To Reproduce
1. Create a room
2. Create a layer
3. Try to rename the layer with F2
4. See that it is renaming the Inspector tab, not the layer.

[77a8f049-bc70-431f-91a3-b49f6f5fab82](https://api.gamemaker.io/api/github/downloads/77a8f049-bc70-431f-91a3-b49f6f5fab82)

**Comment by WangleLine** [comment] 2024-03-02 11:21
https://github.com/YoYoGames/GameMaker-Bugs/assets/34343336/a3e2e126-7f27-4f8d-b645-1802dd91e37f


Confirming this also happens on my end, using Steam, IDE v2023.11.1.129, v2023.11.1.160

**Comment by tabularelf** [comment] 2024-03-02 12:48
In addition, I like to confirm that this behaviour does not happen on LTS, and it instead appropriately renames the layer. IDE v2022.0.2.51  Runtime v2022.0.2.49
https://github.com/YoYoGames/GameMaker-Bugs/assets/26135221/19eb4da7-58e3-416e-9ab5-6142f10ce50d

**Comment by YYDan** [comment] 2024-03-07 11:06
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2665

**Closed by YYDan** 2024-03-07 11:06 UTC
Labels: ide-bug
