### ISSUE TITLE
Feather: Quick-fixing unfolds your code blocks

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#2146] opened 2023-11-09 14:00 UTC
### Description
Whenever I use Quick fix for my feather ruling, it just unfolds every code block for that event. It really is annoying, and what worse about it is if your code is unfolded via that problem, you cannot use any folding or folding shortcut key, unless you break a feather rule like deleting an curly bracket or something... or just write nonesense.

### Steps To Reproduce
*Open folding in preferences
*Write a code using If or anything that folding rule applies
*Break a feather rule
*Quick fix that rule
*Observe the unfolding

[8afefd85-d13b-4ff0-8165-a69f699a03c3](https://api.gamemaker.io/api/github/downloads/8afefd85-d13b-4ff0-8165-a69f699a03c3)

**Comment by Totobal5** [comment] 2023-11-18 21:31
i think is a duplicated of #918

**Comment by YYDan** [comment] 2024-09-24 09:21
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/918

**Closed by YYDan** 2024-09-24 09:21 UTC
Labels: ide-bug
