### ISSUE TITLE
Code Editor 2: Macro definition bodies are not color coded

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6892] opened 2024-07-26 00:50 UTC
### Description
See picture

### Steps To Reproduce
1) Project attached line 69 script __GameConfig
2) layer_get_id is not collored
3) Other macros or objects too are not colored bad

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files:
GameMaker-Beta_DUsa9gdcZu.png

[2bc02e39-0e96-4758-83df-f51ee6f06171](https://api.gamemaker.io/api/github/downloads/2bc02e39-0e96-4758-83df-f51ee6f06171)

**Comment by zreedy** [comment] 2024-11-21 17:03
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6757

**Closed by zreedy** 2024-11-21 17:03 UTC
Labels: ide-bug, project
