### ISSUE TITLE
Adding a empty draw event does not override default drawing until you type something into the event and then delete it

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4397] opened 2024-01-18 11:58 UTC
### Description
If you just add an empty draw event to an object, the default draw does not get overwritten. If you type something into the event and then delete it, it will.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6d6fa60f-e457-4016-9a1c-0b20728e3469

### Steps To Reproduce
Add a draw event to an object, and then immediately run the game. The object will still draw.
Type anything into the draw event, delete it, and then run the game again. The object will not draw.

[c97316e9-c5db-4fe0-9d1a-07428b061efe](https://api.gamemaker.io/api/github/downloads/c97316e9-c5db-4fe0-9d1a-07428b061efe)

**Comment by rwkay** [comment] 2024-01-19 11:18
Unable to replicate it in 2024.2 HEAD at all...

**Comment by KormexGit** [comment] 2024-01-19 12:33
I'm able to replicate it on the public 2024.2 beta 100% of the time, even when repeatedly deleting and re-adding the draw event to the same object

**Comment by rwkay** [comment] 2024-01-19 12:42
Hmmm just realised that you had nothing in the default text... I am wondering if the behaviour is different (I had the default text in there) - can you please test with something in the default text for a script at your end... and I will test the opposite here

**Comment by rwkay** [comment] 2024-01-19 12:48
OK I can confirm @stuckie that this does happen if the Event does not have anything in it at all - I suspect that the IDE is not writing a GML file at all and the asset compiler is not adding the Event because of that - I will take a look to see what can be done at the IDE level.... this is not related to the changes for 2023.11 to omit events... it is purely down to the IDE not saving the GML file if it is completely empty.

**Comment by rwkay** [comment] 2024-01-19 14:27
Fixed in 2024.2

**Closed** 2024-01-19 14:30 UTC
Labels: runner-bug

**Comment by alicemoretti** [comment] 2024-02-01 14:43
Verified fixed on IDE v2024.200.0.478  Runtime v2024.200.0.493. Thank you.
