### ISSUE TITLE
Code Editor 2: Enter and Backspace keys incorrectly add and remove tab characters, depending on the indentation of the line the caret is moving to

### ISSUE THREAD

**Issue by yunzlp** [YoYoGames/GameMaker-Bugs#5946] opened 2024-05-24 16:27 UTC
### Description

You shouldn't get tabs here.
![screenshots](https://github.com/YoYoGames/GameMaker-Bugs/assets/13077757/e51a3059-34b8-4576-ab2d-ba2a35b0783e)

If you don't get extra tabs here, you shouldn't automatically delete extra tabs that you add manually.
![screenshots](https://github.com/YoYoGames/GameMaker-Bugs/assets/13077757/1605530c-e327-48b5-8930-748c1265d389)

ps:This submission has no package

### Expected Change

normal logic

### Steps To Reproduce

1. Start GameMaker
2. Enable Editor 2
3. Create a script. Write something.
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment] 2024-06-28 15:25
Unable to reproduce. This was likely fixed in a duplicate ticket.

**Closed by zreedy** 2024-06-28 15:25 UTC
Labels: ide-bug
