### ISSUE TITLE
In Game: "Compressed - Streamed" option does not work in all instances for sound.

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#147] opened 2023-07-28 12:33 UTC
GM-3558

Bug Type: Bug with in-game functionality
Ide Version: 2022.1.0.609
Runtime Version: 2022.1.0.482
Steam Ide: on
Platforms: Windows
Components: Windows

Description: I am trying to use the Compressed - Streamed option for the music in my game, but when that option is selected for a piece of music (for example, I used this option for mus_gateway_galaxy, as seen in the compiler log), that music does not play anymore. The other three options work fine and the music will play when Compressed - Streamed is not chosen.

I was unable to replicate the issue in a fresh project, so I have uploaded the yyz of my game to mediafire

I get the issue using the following steps:
1. Run game
2. Press left shift to go to map selection
3. Click on the map named "Mooned", at the bottom center of the screen
4. Click any of the icons that show up (this is simply difficulty selection)
5. The map starts without any music playing (in this case it should be playing mus_gateway_galaxy)

This issue seems able to be replicated with any of the other sound files in the game -- so if you switch it to Compressed - Streamed, it won't play that sound anymore when it should.

Additional notes: a friend suggested to replace the ffmpeg and ffprobe executables in the runtime folder (C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2022.1.0.482\bin\ffmpeg\windows) with the full 75MB binary, and I noticed the current executables there were only 381KB. I'm not sure if that was normal. Unfortunately, swapping out the executables did not fix the issue.

##RP

 I couldn't replicate initially but the user has now confirmed that the compressed - streamed sounds only fail to play when running in VM or debugging - when exporting via YYC it plays without an issue . See their project attached

**Comment by toby-yoyo** [comment] 2024-11-08 12:11
The original example project had a slight compilation issue (an empty audio asset), so I've fixed that and also added a few lines of debugging code to it. The tweaked project can be found here: https://drive.google.com/file/d/1SIXo8qNc1HZIx6_BJfbfqYUVHWkY4H-J/view?usp=sharing

Following the instructions from the description, you can see in the audio debug view that the mentioned asset `mus_gateway_galaxy` does play as expected.

I also tried changing `musTitle` to Compressed - Streamed and that also continued to play as expected.

Tested using:
- IDE v9.9.1.846 / Runtime v9.9.1.994
- IDE v2024.1100.0.674 / Runtime v2024.1100.0.700
- IDE v2024.8.1.171 / Runtime v2024.8.1.218

It seems pretty safe to say that whatever this issue was has been resolved in the ~3 years since it was reported.

Closing as 'cannot reproduce'.

**Closed by toby-yoyo** 2024-11-08 12:11 UTC
Labels: runner-bug, import
