### ISSUE TITLE
Refactoring asset names doesn't work

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7095] opened 2024-08-04 04:52 UTC
### Description

I dunno if this is the same bug as #960 or not because this was definitely working fine not too long ago

![gm refactor references is broken](https://github.com/user-attachments/assets/520b6674-85f8-4f5a-8571-99744863faec)

[test - refactor.zip](https://github.com/user-attachments/files/16486362/test.-.refactor.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment] 2024-08-04 04:58
#5395 probably

**Comment by stuckie** [comment] 2024-08-06 09:06
Duplicate of #5395

**Closed by stuckie** 2024-08-06 09:06 UTC
Labels: ide-bug
