### ISSUE TITLE
Preferences-General Settings-Paths-GameMaker Project Path

### ISSUE THREAD

**Issue by lcizzle** [YoYoGames/GameMaker-Bugs#8311] opened 2024-11-05 14:42 UTC
### Description
I changed the GameMaker Project Path location in Preferences->General Settings->Paths. Even though I pointed it to a new location every time I open gamemaker it is still creating the original folder in my user home directory.

### Steps To Reproduce
Open Preferences
Click General Settings
Click Paths
Change GameMaker Project Path.
Open Windows Explorer and delete the orginal projects folder in your home directory.
Close and Open GameMaker
Original folder returns even though I changed the GameMaker project path.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

[92cc475e-3cc6-4f51-9fc7-d97b63aafed7](https://api.gamemaker.io/api/github/downloads/92cc475e-3cc6-4f51-9fc7-d97b63aafed7)

**Comment by YYDan** [comment] 2024-11-05 14:45
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/4620

**Closed by YYDan** 2024-11-05 14:45 UTC
Labels: ide-bug
