### ISSUE TITLE
Edit object variable definitions in sequence editor

### ISSUE THREAD

**Issue by FriendlyRobot117** [YoYoGames/GameMaker-Bugs#2693] opened 2024-01-04 13:17 UTC
### Is your feature request related to a problem?

Currently, when you edit an object in the object editor workspace you have access to the variable definitions. (bottom left)

![workspace object](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/86304647/49c924f3-125d-416f-a085-1711bea4e937)

However, in the Sequence editor you cannot edit these values for the object in the sequence. 

![sequence instance](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/86304647/cfe525ba-1b09-4b9b-81b5-df48827a6946)

Having this feature would be very beneficial for having different properties for different instances of the object within the sequence. (for my case, multiple hitboxes in the same attack sequence, each with different knockback or damage values). 

### Describe the solution you'd like

Ideally the inspector for the object in the sequence would be the same as the inspector for objects placed in the room. example:

![room instance](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/86304647/7259c199-d996-4c48-8d7d-893e859ae91e)

Where you have access to the variable definitions. (this is how I set properties for different instances of objects in the levels. moving platform start/end points or speed etc).

### Describe alternatives you've considered

My current workaround for using hitboxes is to have a function which I can feed these variables custom values from the enemy object creating the hitbox. 

![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/86304647/d21fe9db-7f7b-4359-96ec-c6eb8da2a09e)

however this doesnt allow me to have multiple instances of the hitbox object as I have to use the sequence_instance_override object to replace the one in the sequence with this one I create with the correct values.

**Comment by iampremo** [comment] 2024-02-21 09:38
Duplicate of #4178

**Closed by iampremo** 2024-02-21 09:38 UTC
Labels: ide-bug
