### ISSUE TITLE
Korean input does not work even in the beta version.

### ISSUE THREAD

**Issue by OnlookerRian** [YoYoGames/GameMaker-Bugs#8458] opened 2024-11-19 16:21 UTC
### Description
I had hoped for this issue to be resolved with each update, but since no progress has been made, I am reporting it again. 

I will write more detailed reproduction steps.

Currently, this issue is manageable on Windows, but it is quite severe on macOS.

On macOS, if a Korean IME is present, input does not work at all, and even keyboard shortcuts fail to function.

I heard about these issues today at a meetup in Korea and received feedback from around 20 people regarding their inconvenience.

Looking at previous reports, I’ve seen that Japanese users have also expressed inconvenience regarding IME-related issues. This problem needs to be addressed.

For reference, these issues are not limited to the code editor but affect the entire IDE.

### Steps To Reproduce
1. Register the Korean keyboard through IME on Windows and manually switch to Korean input.  
![Image](https://github.com/user-attachments/assets/63272e7f-95c5-4cef-b87e-25f44ff240ff)

2. If the code editor or ide does not have a Korean font, use an example font such as [D2Coding](https://github.com/naver/d2codingfont) and set it.  
3. Enter `rkskekfk` (expected output: 가나다라).  

4. From the `rk` input onward, when typing sequentially, the input does not register correctly after `rk`.
   - `rk` = 가  
   - `sk` = 나  
   - `ek` = 다  
   - `fk` = 라

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[e3998bac-ba1b-4a62-b1ef-1390ca02dcc5](https://api.gamemaker.io/api/github/downloads/e3998bac-ba1b-4a62-b1ef-1390ca02dcc5)

**Comment by YYDan** [comment] 2024-11-27 11:43
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/953

**Closed by YYDan** 2024-11-27 11:43 UTC
Labels: ide-bug
