### ISSUE TITLE
Repeatedly reloading the same project without closing GameMaker causes GameMaker's memory usage to grow with every load

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6281] opened 2024-06-14 18:10 UTC
### Description
Noticed that I was getting a significant slowdown after testing #6280 several times in a row. Checking the task manager, GM's memory usage was much higher than normal. I have determined this is caused by repeatedly reloading the same project over and over using the recent projects menu. It seems to happen for projects of any size, but it goes up more per load for larger projects. Note that this happens regardless of using CE1 or CE2 in my testing.

On initial load:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/afd48a1e-8569-4dab-bfbe-744bf92c9198)

After several reloads:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6702ed41-3d82-4d93-898a-74b1e61c8996)

After many many many reloads (CPU usage is higher because this one was taken mid-load):
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/115b30f6-5fb2-411e-b620-95ce8681dc74)

I stopped there because my fans were getting very loud and I didn't want my PC to explode lol

### Steps To Reproduce
Open up a project. Reload it through the recent projects menu without closing GameMaker. Repeat this process, watching GameMaker's memory usage in the task manager. It will continuously increase with each load.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[4c1a0063-1231-433e-8d12-5e026e8e2efc](https://api.gamemaker.io/api/github/downloads/4c1a0063-1231-433e-8d12-5e026e8e2efc)

**Comment by YYDan** [comment] 2024-06-17 08:53
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5873

**Closed by YYDan** 2024-06-17 08:53 UTC
Labels: ide-bug
