### ISSUE TITLE
Function signature help text stops showing when a parameter is an anonymous function and has a semicolon

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#5867] opened 2024-05-17 03:45 UTC
### Description

When using the code editor, and typing a function that itself has callable arguments, and using anonymous (inline) functions for this matter, causes the IDE function signature help text (displayed at the status bar at the bottom of the code editor) to stop showing.

Example:
This screenshot shows partial typing of `time_source_create` to create a time source. The first three arguments are managed fine by the help text:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/28306587/5ce73881-b97d-460a-9f01-5517954538a7)

When typing the anonymous function, everything is still fine if we don't end lines in the body of the function with semicolon:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/28306587/59654560-3d44-4785-920b-cdb1545da48d)

However, as soon as semicolons are used in the body code, the help text stops showing - even when those semicolons do not end the currently typed line, but rather end a statement inside the function argument:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/28306587/8f397d30-48d2-4ac7-96b0-9ed065ea1380)

Not sure if needed but I attach the "Contact Us Package".
[contact_us.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15343380/contact_us.zip)

### Steps To Reproduce

1. Start GameMaker
2. Type a function that has a callable argument
3. Type an anonymous callable argument with a body code that includes semicolons
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Grisgram** [comment] 2024-05-17 04:49
duplicate of #5100

**Comment by stuckie** [comment] 2024-05-17 08:44
Closing as above

**Closed by stuckie** 2024-05-17 08:44 UTC
Labels: ide-bug
