### ISSUE TITLE
Allow "Search & Replace" to Find All when you press Enter while docked

### ISSUE THREAD

**Issue by Vine2D** [YoYoGames/GameMaker-Bugs#3001] opened 2023-08-25 20:34 UTC
### Is your feature request related to a problem?

Currently, the Search & Replace window will implicitly activate it's Find All button when you press the Enter key while the window is floating. For organization's sake, if you dock the Search & Replace window into any of the sidebars, pressing Enter no longer works, even if you have focused the window by pressing Ctrl-Shift-F.

### Describe the solution you'd like

Pressing Enter after typing in the Search & Replace window (or if it is in focus) will Find All whether the window is docked or not. More often than not this is just Ctrl-Shift-F > type_some_stuff > Enter.

**Comment by DaveInDev** [comment] 2024-01-10 23:11
+1
this Search and Replace feature deserves some corrections.
Please see also : 
https://github.com/YoYoGames/GameMaker-Bugs/issues/854
https://github.com/YoYoGames/GameMaker-Bugs/issues/3463
https://github.com/YoYoGames/GameMaker-Bugs/issues/906
https://github.com/YoYoGames/GameMaker-Bugs/issues/2776

**Comment by YYDan** [comment] 2024-06-06 08:24
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/854

**Closed by YYDan** 2024-06-06 08:24 UTC
Labels: ide-bug
