### ISSUE TITLE
Crash after renaming a sprite

### ISSUE THREAD

**Issue by FrancisCoulombe** [YoYoGames/GameMaker-Bugs#5771] opened 2024-05-06 03:55 UTC
### Description
GM crashed after I renamed a sprite shortly after creating it by duplication.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[6aa6c902-aa1a-4c05-8573-535c7eaef09d](https://api.gamemaker.io/api/github/downloads/6aa6c902-aa1a-4c05-8573-535c7eaef09d)

**Comment by stuckie** [comment] 2024-05-08 08:06
Duplicate of #4907

**Closed by stuckie** 2024-05-08 08:06 UTC
Labels: crash, dump
