### ISSUE TITLE
instance_id Returns -4 (noone) Instead of Array Reference

### ISSUE THREAD

**Issue by ParodyKnaveBob** [YoYoGames/GameMaker-Bugs#2219] opened 2023-11-16 08:01 UTC
### Description
One cannot use array functions on `instance_id` such as `array_length(instance_id)` because `instance_id` by itself returns `-4` (`noone`) instead of an array reference.

### Steps To Reproduce
1. Start GameMaker
2. Import and run enclosed project.
3. See debug messages (before main loop via Room Creation Code).
4. Optionally, run in Debug Mode and Watch these variables:
```
instance_count
instance_number(all)
instance_id
array_length(instance_id)
instance_id[0]
instance_id[1]
instance_id[2]
instance_id[3]
```
which demonstrates the problem persists during the main game loop.

[bbbe897d-6366-4659-acdb-9645412adfaf](https://api.gamemaker.io/api/github/downloads/bbbe897d-6366-4659-acdb-9645412adfaf)

**Comment by rwkay** [comment] 2023-11-23 10:52
This is by design.. if the index is out of range then the return value is `noone` which is -4, I think the documentation needs to be updated to reflect this.

NOTE: none of the built in variables that act like arrays are true arrays and the array functions will not work on them.

I am going to assign this to documentation now to update @gurpreetsinghmatharoo  @YYBartT

**Closed** 2024-02-05 17:08 UTC
Labels: runner-bug, project
