### ISSUE TITLE
Code Editor 2: Various issues with global Replace

### ISSUE THREAD

**Issue by yyalansavage** [YoYoGames/GameMaker-Bugs#5617] opened 2024-04-23 15:20 UTC
### Description
CTRL+SHIFT+F global replace has various issues when Code Editor 2 is enabled
i)-Replace ALL will replace text on-disk, but open scripts etc are not refreshed to reflect updated file content
ii)-Replace (next) will open script window & highlight first match, but will not replace the text, and does nothing if repeatedly pressed

### Steps To Reproduce
i)-with CE2 enabled, open/create a script window with some text
-CTRL+Shift+F and Replace All for some text which occurs in the opened script
-the open script appears not to change; check the .gml file on disk to see it has been updated; if the script is closed and re-opened, you can now see the replaced content
ii) CTRL+Shift+F and click Replace for something which occurs in a script; the script will open and position cursor at the start of the match; pressing replace again will highlight the match; pressing replace again after that does nothing

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.656 Runtime v9.9.1.775

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[afaf4cb1-0067-4f5b-a04e-d13158fcb5e5](https://api.gamemaker.io/api/github/downloads/afaf4cb1-0067-4f5b-a04e-d13158fcb5e5)

**Comment by KormexGit** [comment] 2024-04-23 23:03
Same thing as #5365, could close mine since this has more detailed steps

**Comment by YYDan** [comment] 2024-04-24 07:50
Moved the steps over and Closing ;)

**Comment by YYDan** [comment] 2024-04-24 07:50
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5365

**Closed by YYDan** 2024-04-24 07:50 UTC
Labels: ide-bug
