### ISSUE TITLE
Sound Editor playback stuttering

### ISSUE THREAD

**Issue by Drillimation** [YoYoGames/GameMaker-Bugs#1906] opened 2023-10-12 14:10 UTC
### Description
When importing a sound that is more than ten seconds long such as a background music track, and when playing back the sound, the audio will stutter with the playhead also doing the same.

### Steps To Reproduce
Import any sound that is more than ten seconds long.

[ed54fa96-af64-40d7-b2b0-1d573a18e955](https://api.gamemaker.io/api/github/downloads/ed54fa96-af64-40d7-b2b0-1d573a18e955)

**Comment by toby-yoyo** [comment] 2024-11-19 10:11
Cannot reproduce this on IDE v9.9.1.853 Runtime v9.9.1.1001. Sound used was: [tri-48k-220hz-mono-1min.zip](https://github.com/user-attachments/files/17813221/tri-48k-220hz-mono-1min.zip)

I suspect that this will have been fixed by https://github.com/YoYoGames/YoYoStudio/issues/9066, which integrated the runtime audio engine with the IDE, which was initially released in 2024.2.

Note that there was a separate issue relating to crackling in some recent versions (2024.6+) which will have been caused by the same underlying bug that caused https://github.com/YoYoGames/GameMaker-Bugs/issues/8408.

**Comment by toby-yoyo** [comment] 2024-11-19 16:29
Closing as 'cannot reproduce'.

**Closed by toby-yoyo** 2024-11-19 16:29 UTC
Labels: ide-bug
