### ISSUE TITLE
Updater issues a warning after GM close that GM's instance is running

### ISSUE THREAD

**Issue by Notlea** [YoYoGames/GameMaker-Bugs#8664] opened 2024-12-10 19:21 UTC
### Description
Whenever I use auto updater in Beta, I pick close and update the IDE immediately. GM closes, updater starts but every time I see a warning, that GM is still running and can't be updated. I press OK and update continues normally. 
I had this issue for past 2-3 updates.

### Steps To Reproduce
1. Install previous IDE
2. Pick Close GM and update when prompted
3. Observe GM closing and starting updater
4. See the warning

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.710 Runtime v2024.1100.0.726

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files
* image1.png
* image2.png

[077706ce-3949-420c-91a9-395768e90c2d](https://api.gamemaker.io/api/github/downloads/077706ce-3949-420c-91a9-395768e90c2d)

**Comment by Notlea** [comment] 2024-12-10 19:24
No other GM instances like LTS or Monthly are running during that time. The issue reproduces after freshly starting my PC and launching the Beta first.

**Comment by scott-dunbar** [comment] 2024-12-10 19:57
Looks like a dupe of https://github.com/YoYoGames/GameMaker-Bugs/issues/8195

Hopefully now users are also seeing it it will get moved out the backlog

**Comment by stuckie** [comment] 2024-12-11 09:48
Duplicate of #8195

**Closed by stuckie** 2024-12-11 09:48 UTC
Labels: ide-bug
