### ISSUE TITLE
Code Editor 2: Match 3 Template does not trigger Diagnostics correctly during loading the project

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6881] opened 2024-07-25 23:38 UTC
### Description
like tilte say

### Steps To Reproduce
1) Open the Match 3 template is not working

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[651a1310-e362-49e6-9546-e5411f9c605c](https://api.gamemaker.io/api/github/downloads/651a1310-e362-49e6-9546-e5411f9c605c)

**Comment by zreedy** [comment] 2024-10-08 21:06
Appears fixed now.

**Closed by zreedy** 2024-10-08 21:06 UTC
Labels: ide-bug

**Comment by scott-dunbar** [comment] 2024-10-10 13:39
Unable to reproduce in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664

Closing as fixed
