### ISSUE TITLE
Tab key triggers without pause

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5538] opened 2024-04-17 20:00 UTC
### Description

In the newest beta the tab key triggers without pause in the IDE. Usually keys trigger once, do a pause and then trigger multiple times. Now, the tab key triggers multiple times immediately thus making you jump over the fields you actually want to jump to.

### Expected Change

Make the tab key have a short pause again after the keypress.

### Steps To Reproduce

1. Click on any field in the IDE (outside the Code Editor), e.g. the field for room width
2. Press the tab key to switch to the next field. -> You will see that it triggers multiple times and jumps over many fields.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment] 2024-04-18 08:22
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5522

**Comment by YYDan** [comment] 2024-04-18 08:23
(It got fixed in the gap between the Beta release and now, so it was in the closed list already - the fix is already in the _next_ Beta)

**Closed by YYDan** 2024-04-18 08:22 UTC
Labels: ide-bug
