### ISSUE TITLE
In-Game: [HTML5] Performance issues when effect layer is present even if effect type is set to 'None'

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#6377] opened 2024-06-21 15:59 UTC
### Description

When building to HTML5, if Effect Type is set to 'None', the game wil still have a slower framerate just as it would if there was an effect or filter selected. This is most noticeable when using high resolution monitors. This occurs in both Beta IDE v2024.600.0.579  Runtime v2024.600.0.605 and in IDE v2024.4.1.152  Runtime v2024.4.1.201.

[Sample Project](https://drive.google.com/file/d/1h2jIvH8Bd0mMiCEvU7OtNqezGnBSjZam/view?usp=drive_link)

### Expected Change

It is expected that if effect type is set to 'None' the game runs without framerate degradation.

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Ensure that both 'EffectLeaf' and 'WaterTiles' layers have framerate set to 'None'
4. Target HTML5
5. Run game
6. Click Start button in game
7. See the issue
8. If issue cannot be seen, run game with layers mentioned in step 3 deleted for comparison
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by pkraif** [comment] 2024-07-29 07:46
I'm testing this with IDE v2024.6.2.162 and runtime commit `c04ad513a7cfcc9c5b6640d130b00ed6bd49f126` from `develop` branch and I can't reproduce this issue. I can add many "None" effect layers and it doesn't decrease performance at all (I'm drawing `fps`  in GUI and it's always ~120fps, with game speed set to 9999fps in Main options). The `LayerBegin` function, which would affect performance, isn't even called for "None" effect layers. I'm closing this issue as "can't repro".

**Closed by pkraif** 2024-07-29 07:46 UTC
Labels: runner-bug
