### ISSUE TITLE
Code editor 2: Function argument helper tooltip will appear when first typing a function, but not if you click away from the function and come back

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5472] opened 2024-04-12 21:01 UTC
### Description
When you type a function and add (), a helpful argument tooltip will pop up. However, if you click away from the function and then come back and start typing arguments again, the tooltip does not reappear. The only way to get it back is to manually mouse over the function, or delete all the arguments and start over. This makes it tricky to tell what argument you're on when editing arguments for a previously typed function.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/05e78b70-2b0f-445a-bcd1-521034b59346

### Steps To Reproduce
Type half of the arguments for a function, then click away and try to resume typing the arguments. The tooltip won't come back.
Similarly, you can type all of the arguments for a function, click away, and then go back to edit one of the arguments.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[88c94412-ff59-4362-b76e-621acbd45711](https://api.gamemaker.io/api/github/downloads/88c94412-ff59-4362-b76e-621acbd45711)

**Comment by gnysek** [comment] 2024-04-15 09:54
It should show again on `Ctrl+Space` (at least it works for me, but maybe there are cases in which it doesn't work).

**Comment by zreedy** [comment] 2024-06-21 22:26
This is by design but perhaps a preference to eagerly display the tooltip if you move the cursor inside of a function would be appropriate?

**Comment by KormexGit** [comment] 2024-06-21 22:43
Yes please, my preference would be for it to always appear when my cursor is inside a function no matter what, since I often go back and change arguments on an already typed function. I mentioned it in my FR here #6287 

> This is by design but perhaps a preference to eagerly display the tooltip if you move the cursor inside of a function would be appropriate?

**Comment by zreedy** [comment] 2024-06-27 14:22
This is working as intended, and since there's a FR filed with this (and a lot more) requested I will close this ticket.

**Closed by zreedy** 2024-06-27 14:22 UTC
Labels: ide-bug
