### ISSUE TITLE
Code editor 2: Middle clicking/pressing F1 on a macro or enum does not jump to the definition

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5394] opened 2024-04-08 17:19 UTC
### Description
Jumping to definition does not work on macros or enums. In my sample project, it does nothing. In my main project, it actually can bring up the manual page for whatever the macro is set to, eg. middle clicking a macro for true takes me to the math and numbers page. I haven't been able to reproduce this result in my sample project.

### Steps To Reproduce
Make a macro or enum, use it somewhere, and middle click it/press F1 on it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[6edcd5b6-3ccc-4061-b73c-ac44f135f36a](https://api.gamemaker.io/api/github/downloads/6edcd5b6-3ccc-4061-b73c-ac44f135f36a)

**Comment by zreedy** [comment] 2024-06-21 20:40
Unable to reproduce for Enums, might have been fixed with previous changes.
Fixed for macros.

**Closed** 2024-06-25 15:39 UTC
Labels: ide-bug, project

**Comment by mgeddesGM** [comment] 2024-07-10 15:16
verified as of  IDE v2024.800.0.588  Runtime v2024.800.0.612
