### ISSUE TITLE
IDE: using Tab/Shift+Tab to navigate UI elements in the IDE updates the active UI element continuously, rather than just when the key is pressed

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5522] opened 2024-04-16 22:24 UTC
### Description

Wheeeeeeeeeeeeeeeeeeee.

![ide tab key](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/a488e928-3ab9-40c2-8dc4-24888ad3e37e)

I'm using  IDE v2024.400.0.542 so this may or may not be one of those things that happens when you play around in unreleased betas but this is too funny for me not to share.

### Steps To Reproduce

1. Start GameMaker
2. Select any UI element
3. Hit the Tab key to navigate between elements
4. Wheeeeeeeeeeeeee

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment] 2024-04-16 22:24
aw rip the gif doesn't do it justice

**Comment by YYDan** [comment] 2024-04-17 13:58
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5388

**Closed by YYDan** 2024-04-17 13:58 UTC
Labels: ide-bug
