### ISSUE TITLE
Implement NewTextureRepacker from UTMT

### ISSUE THREAD

**Issue by JeodC** [YoYoGames/GameMaker-Bugs#7807] opened 2024-09-27 16:35 UTC
### Is your feature request related to a problem?

Not related to an ongoing problem

### Describe the solution you'd like

No solution necessary as this is more of an inquiry

### Additional context

Hello, I am curious about the inner workings of GameMaker and why many games seem to perform better after they have had UndertaleModTool's [NewTextureRepacker](https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModTool/Scripts/Resource%20Repackers/NewTextureRepacker.csx) script used on them. Is it accurate to say that GameMaker loads textures individually, instead of atlassed, which can cause wasted resource consumption?

I work with small arm devices such as handhelds akin to raspberry pi, and for a few games now I have ended up using external tools for audio and texture compression to mitigate performance loss for low-end cpu and ram. There is a noticeable difference, so I seek to understand how it all works and, if my understanding is accurate, how GameMaker might implement texture atlassing directly.

Thank you in advance.

**Comment by DragoniteSpam** [comment] 2024-09-27 17:27
> Is it accurate to say that GameMaker loads textures individually, instead of atlassed

No, it is absolutely not true.

**Comment by JeodC** [comment] 2024-09-27 17:30
> > Is it accurate to say that GameMaker loads textures individually, instead of atlassed
> 
> 
> 
> No, it is absolutely not true.

Then what happens to boost performance in this way?

**Comment by JeodC** [comment] 2024-09-27 19:52
The script creator got back to me.

```
If the default pages are too big, mali can see a performance drop due to insanely large pages. You would have to check a frame capture to know if that's the case. As far as I'm aware, there are next to no heuristics done with regards to what textures go where, so the default atlases might cause the script's repacking to increase performance.

As for the NewTextureRepacker script, it was written for three reasons:
- Mali 400 has a very small precision on mediump preset, causing texture seams when atlases are >=2048 in any dimension
- Mali g31 can crash with too large textures (e.g. Gato Roboto)
- Some games can and will load too many textures by default

If there's a performance improvement it's most likely due to the script heuristics or because texture atlases are smaller after using it.
```

I was able to at least follow that, and it makes some sense. As it has a specific purpose, I'm not certain how useful it is beyond Mali blobs.

**Comment by attic-stuff** [comment] 2024-09-27 20:50
> I'm not certain how useful it is beyond Mali blobs.

pretty much none. there is a point at which gamemaker just doesn't need to support much older devices and much lower capabilities. the mali 400 is well over a decade old now, and 2048 has been the default gamemaker atlas size for a while. also gamemaker is fully capable of managing textures in both ram, and vram, and even has an official extension for compressing textures to lower their vram footprint. so the problem is developers not taking advantage of it, not gamemaker being incapable.

**Comment by JeodC** [comment] 2024-09-27 22:39
> > I'm not certain how useful it is beyond Mali blobs.
> 
> pretty much none. there is a point at which gamemaker would be held back to continue to support much older devices and much lower capabilities. the mali 400 is well over a decade old now, and 2048 has been the default gamemaker atlas size for a while. also gamemaker is fully capable of managing textures in both ram, and vram, and even has an official extension for compressing textures to lower their vram footprint. so the problem is developers not taking advantage of it, not gamemaker being incapable.

Yes, however most developers aren't targeting <4GB low-end cpu devices. I think I have a better understanding of how this all works out now; my goal was to avoid spreading misinformation under false assumptions. Thank you very much for your time.

**Comment by stuckie** [comment] 2024-09-30 08:48
Closing as above.

**Closed by stuckie** 2024-09-30 08:48 UTC
Labels: feature request
