### ISSUE TITLE
show_debug_message in Cleanup causing crash in Mac OS

### ISSUE THREAD

**Issue by tthrelfo** [YoYoGames/GameMaker-Bugs#5571] opened 2024-04-19 11:58 UTC
### Description
Having a show_debug_message() in the Cleanup event of an object in the active room causes a Mac OSX crash when closing the game with Command-Q.

### Steps To Reproduce
1. Create a new project
2. Create a new object
3. Add the Cleanup event to the object
4. Add this code to the Cleanup event:
show_cleanup_message("hi");
5. Drag the object into the Instances layer in your room
6. Run the game
7. Press Command-Q

[ce54cac9-37e2-4641-99ad-d8c6a6a43f71](https://api.gamemaker.io/api/github/downloads/ce54cac9-37e2-4641-99ad-d8c6a6a43f71)

**Comment by L-Clouds** [comment] 2024-04-19 17:28
Would you share the Mac crash message, please?  I'm hoping this is the cause of a bug reported in a GameMaker game I help keep track of bugs for (but don't have the code), and if the crash logs match, I could pass this info along.

**Comment by tthrelfo** [comment] 2024-04-20 00:29
> Would you share the Mac crash message, please? I'm hoping this is the cause of a bug reported in a GameMaker game I help keep track of bugs for (but don't have the code), and if the crash logs match, I could pass this info along.

Sure, I'll link it here: https://pastebin.com/Ei7Qi3W6

**Comment by L-Clouds** [comment] 2024-04-20 05:37
Ah, very different crash report.  Probably not, then.  (But, given it's YYC vs. VM and different version of GM, who knows.  If you're curious: https://pastebin.com/5mWtTUUs)

**Comment by rwkay** [comment] 2024-04-22 13:42
Fixed in 2024.4

**Closed by rwkay** 2024-04-22 13:42 UTC
Labels: crash

**Comment by Emc1923** [comment] 2024-04-26 15:42
Verified fixed in  IDE v2024.4.0.134  Runtime v2024.4.0.166.
