### ISSUE TITLE
get_*_filename pages don't mention returning null on cancel

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#8850] opened 2024-12-23 14:18 UTC
### Description

`get_save_filename()`, `get_open_filename()`, `get_save_filename_ext()` and `get_open_filename_ext()` docs all mention returning an empty string `""` on cancel, however they actually return a null string. Checking `_string == ""` will return `false` if `_string` is null. 

This issue was mentioned #7525. I doubt returning "null" is intentional because it breaks people's code, this bug reports states it's been fixed but the issue is also closed as "not planned". I'm mainly making this report to show that the docs are not consistent with the behaviour (but personally i think the behaviour should change, not the docs)

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/File_System/get_open_filename.htm https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/File_System/get_open_filename_ext.htm https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/File_System/get_save_filename.htm https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/File_System/get_save_filename_ext.htm

**Comment by GameDevTosh** [comment] 2024-12-23 14:42
Yea I'm really not sure why https://github.com/YoYoGames/GameMaker-Bugs/issues/7525 was closed since its always worked with "", and all of the manual pages still show it using "" for error checking:
![Image](https://github.com/user-attachments/assets/90a488be-88f2-460d-8f34-5326f93eb07d)

Even using nullish ?? to try to set the null returned to something else, like "" with:
```
var file = get_open_filename("text file|*.txt", "") ?? "";
```

doesn't work. Only the previously mentioned string_length in the other reports are a possible fix for now.

**Comment by alicemoretti** [comment] 2024-12-24 09:15
Duplicate of #8855.

**Closed by alicemoretti** 2024-12-24 09:15 UTC
Labels: docs-bug
