### ISSUE TITLE
Conditional Breakpoints

### ISSUE THREAD

**Issue by yamboschmambo** [YoYoGames/GameMaker-Bugs#8116] opened 2024-10-24 09:05 UTC
### Is your feature request related to a problem?

Developing games and dealing with a lot of reoccurring loops and all the complications that come with placing a breakpoint in these (breaking into a breakpoint 60 times a second, writing tedious if conditions inside the code just for debugging purposes), would be solved very easily with conditional breakpoints.

### Describe the solution you'd like

When they are hit, like regular breakpoints, a condition inside them is evaluated. If this condition is true, only then the game will stop and pop-up the debug window.

I imagine that the breakpoints could be similarly configured as in Visual Studio Code 2022, where a window opens whenever you right click a breakpoint and select 'add condition'

### Describe alternatives you've considered

Writing a helper function or piece of code to embed the breakpoint in, but this clutters the code, makes it less readable, takes a lot of time

**Comment by YYDan** [comment] 2024-10-24 10:12
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3349

**Closed by YYDan** 2024-10-24 10:12 UTC
Labels: feature request
