### ISSUE TITLE
In-Game: gamepad_button_check_pressed() and ...check() give different jump results in Windy Woods template

### ISSUE THREAD

**Issue by Michaelm82** [YoYoGames/GameMaker-Bugs#7401] opened 2024-08-23 06:10 UTC
### Description

if you us the if (gamepad_button_check_pressed(gamepad, gp_face1)) the jump Hight will not be the correct Hight. 
But if you use if (gamepad_button_check(gamepad, gp_face1)) the jump Hight will be correct.
You can test this using windy winds. 
This issue happed in the newer run times and is still an issue in the newest beta runtimes as well as the run times in the stable build. 

### Expected Change

The jump hight should be the same as when using touch controlles keyboard. when you use the gamepad. 

### Steps To Reproduce

1. Start GameMaker
2.  load windy winds
3. run the program
4. Press space bar the char will jump full Hight.
5. press jump on game pad and you will see the jump Hight is incorrect. 
7. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, Ubuntu, Android, GX.games, HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2024-08-23 08:47
The two functions do different things:
gamepad_button_check_pressed only returns true for one frame
gamepad_button_check returns true on each frame.

This is not a bug with GameMaker itself, but one in your project, so I will close this issue now. For coding support, please visit the [GameMaker Community](https://forum.gamemaker.io/index.php) forum and create a thread there, asking for advice.

**Comment by stuckie** [comment] 2024-08-23 08:47
The two functions do different things:
gamepad_button_check_pressed only returns true for one frame
gamepad_button_check returns true on each frame.

This is not a bug with GameMaker itself, but one in your project, so I will close this issue now. For coding support, please visit the [GameMaker Community](https://forum.gamemaker.io/index.php) forum and create a thread there, asking for advice.

**Comment by Michaelm82** [comment] 2024-08-23 13:57
This is not a bug in my code. This worked just fine untill the neewer master sdks. And this is the code from your program you have for platformer toutorial.

**Comment by jackerley** [comment] 2024-08-26 13:05
This is a bug in the platformer sample code, it will need updating @patrickrocheyoyo

**Comment by patrickrocheyoyo** [comment] 2024-11-07 10:56
Transferred to another repo. https://github.com/GMExternal/GameTemplates/issues/58

**Closed by patrickrocheyoyo** 2024-11-07 10:56 UTC
Labels: runner-bug
