### ISSUE TITLE
req for depth (z) buffer clear funcs equivelent to gl_ClearDepth()

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4300] opened 2023-06-06 14:33 UTC
Ticket #209664

Feature Type: feat_addition_ingame
Description: add the function draw_clear_depth(), and also possibly add "depth" as an optional arg to draw_clear() and draw_clear_alpha()
Alternatively named draw_clear_z() or draw_clear_zbuffer() to be inline with the gpu depth funcs

Benefit: currently there is no equivalent to the opengl funcs gl_clearDepth() and gl_clear(GL_DEPTH_BITS)
not having them makes things like reversed camera depth impossible (IE matrix_build_proj(..., 100, 0.01) instead of matrix_build_proj(..., 0.01, 100)), as since you cant clear the depth buffer, you can't use cmpfunc_greater in conjuction with gl_clearDepth(0.0)

it also makes easy application of GUI layers or "background layers" (IE cubemap environments) without using multiple surfaces in 3d scenes impossible (or at least, exceptionally annoying to do), as you cant do gl_clear(GL_DEPTH_BITS) after drawing your 3d scene to wipe away the depth info for things like new 2d or 3d HUD elements (think like an FPS's viewmodel).

While its a niche addition, its also an exceptionally powerful one to those who know how to use it.

**Comment by KeeVeeGames** [comment] 2024-05-23 11:52
Implemented in https://github.com/YoYoGames/GameMaker-Bugs/issues/3708#issuecomment-2049212309

**Comment by YYDan** [comment] 2024-05-24 14:26
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3708

**Closed by YYDan** 2024-05-24 14:26 UTC
Labels: feature request, import
