### ISSUE TITLE
Problem with sprite_add_ext

### ISSUE THREAD

**Issue by SantiFerre** [YoYoGames/GameMaker-Bugs#1656] opened 2023-09-10 12:09 UTC
### Description
I've a problem when I add a sprite with 'sprite_add_ext()' function, if the sprites sizes are 100x100, it returns a sprite 100x100 but in the column and row 100, there are transparecy.
Insead if I use 'sprite_add', the sprite gets the correct dimensions.

### Steps To Reproduce
I load the sprite from an url.

[a6984f6a-3d5b-4b04-91b8-47ec1d1ebeb1](https://api.gamemaker.io/api/github/downloads/a6984f6a-3d5b-4b04-91b8-47ec1d1ebeb1)

**Comment by YYDan** [comment] 2023-09-11 11:39
Duplicate of #1610

**Closed by YYDan** 2023-09-11 11:39 UTC
Labels: runner-bug
