### ISSUE TITLE
Workspace: Delete key no longer working to delete events

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7754] opened 2024-09-24 07:24 UTC
### Description
Edit: Apparently it is still working for others, so I have no idea why it stopped working for me. I tried restarting the IDE and tried multiple projects, and it's still broken.

Pressing delete on an event in the workspace object window no longer works, instead either doing nothing or deleting code from the selected event.

In this video, I'm spamming the delete key:

https://github.com/user-attachments/assets/d2ffabd0-c343-490d-a3e0-2dfeba55314c

### Steps To Reproduce
Open an object in the workspace, create some events, and try to use the delete key to delete them. Also some extra secret step that I don't know, since it seems to be only happening for me and not others.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[894a25fe-3c38-4956-8157-5c55557a228f](https://api.gamemaker.io/api/github/downloads/894a25fe-3c38-4956-8157-5c55557a228f)

**Comment by Grisgram** [comment] 2024-09-24 13:03
@KormexGit 
100% sure you didn't change any keybindings recently?

The reason for this question is, that BOTH of the last 2 updates of gamemaker made a full reset of all key bindings, i had to set up _all_ my bindings again, for every snippet and all, now i have an exported bindings file and it will not hit me again -- still curious, maybe it's just the keybinding?

have you checked that in the preferences?

**Comment by KormexGit** [comment] 2024-09-24 13:05
I already tried resetting my keybinds to defaults and it still kept happening

**Comment by KormexGit** [comment] 2024-09-24 14:13
Another update, gnysek figured out that this setting causes this behavior:
![image](https://github.com/user-attachments/assets/7482a5bb-1817-45ad-aeab-ead1ca5c4b3d)
I'm pretty sure I never changed this setting, especially since this issue started happening abruptly just recently, so I'm not sure if the update somehow changed it or what

**Comment by stuckie** [comment] 2024-09-24 15:15
I've just had a quick look at the bug package, as your changed preferences get added into it.
And yes, it has that that Object Editor setting was changed to single click at the time you sent the bug report.. the default is still set to Double Click.

**Comment by stuckie** [comment] 2024-10-29 10:52
Going to close this as above, as it seems to have been caused by setting to open events on single click, which would change the focus.

**Closed by stuckie** 2024-10-29 10:52 UTC
Labels: ide-bug
