### ISSUE TITLE
Ubuntu IDE - Project load fails in 2024 versions

### ISSUE THREAD

**Issue by Pikku-a** [YoYoGames/GameMaker-Bugs#5965] opened 2024-05-25 08:47 UTC
### Description
I haven't been able to use any 2024 versions of GameMaker, because when trying to open a project, this error appears: "Project load failed. Unable to load [project path]"

It seems to happen in all GameMaker-Beta-2024 versions. (Now I tried it using GameMaker-Beta-2024.600.0.560)

This version of GameMaker works: GameMaker-Beta-2023.1100.0.450

I use Linux Mint. However, I tried it with Ubuntu too, and the same problem happens.

### Steps To Reproduce
1. Get a project started in older GameMaker version (before 2024 versions?)
2. Try to open it in latest GameMaker Beta version

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Linux Linux Mint 21.3 kernel 6.5.0.35

[94903636-7ad1-4681-8fc5-492ecd654978](https://api.gamemaker.io/api/github/downloads/94903636-7ad1-4681-8fc5-492ecd654978)

**Comment by stuckie** [comment] 2024-05-31 08:23
Hello, this should be fixed with an updated runtime!

**Comment by stuckie** [comment] 2024-05-31 08:23
Duplicate of #6012

**Closed by stuckie** 2024-05-31 08:23 UTC
Labels: ide-bug
