### ISSUE TITLE
GXC Integration: "Game not found" when trying to play on the website after successfully uploading it to the Sandbox environment

### ISSUE THREAD

**Issue by eliehanna0** [YoYoGames/GameMaker-Bugs#5646] opened 2024-04-25 16:42 UTC
### Description

I have a private game that I created a couple of weeks ago, I was able to make changes to it and push new versions to Opera GX and it was all working fine.

Then a couple days back, I tried uploading new changes, I didn't see any errors on the output console, everything was successful, I got the GXC Upload succeeded message and all, but for some reason whenever I tried playing my private game , I would get a "Game not found" error message, and of course, I can't play the game.

Things I have tried based on similar reported issues:
- Change version number
- Change name of the game
- Upload it as a new game
- Waited a week

None of that worked and I am not able to find this specific issue online in the forums nor in the GameMaker Bugs reported issues.

I also tried creating a new game for testing purposes, published it as a new game on Opera GX, still get the same error when I try to play on the private link.

I learned that this is happening with any game I try to publish to Opera GX.

Note that I can see the list of any games that I upload in my Opera GX game list, but I can't play them on private mode.

Here is the second game's URL https://sandbox.gx.games/games/t13k80/platformer-demo-x/tracks/50496c25-2809-4773-8225-e07c2531f6b8/

I would appreciate any help, if this is not the correct place to report this, please point me in the right direction.

**Attached Files:**
 [contact_package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15113089/contact_package.zip)
 
[Platformer Demo.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15113105/Platformer.Demo.zip)

### Expected Change

Games uploaded to Opera GX can be viewed and played through the privale link

### Steps To Reproduce

1. Start GameMaker
2.  Create GX.games executable using GMS2 VM
3.  See GXC Upload succeeded message on the output console
4. Try to play game through the private link, I get the "Game not found" error message
 

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment] 2024-04-26 10:17
Unable to reproduce. Found no issues testing locally after uploading in current Betas, also checked on monthly  IDE v2024.2.0.132  Runtime v2024.2.0.163, and seems to be working as expected.

**Comment by yyalansavage** [comment] 2024-04-26 13:37
I notice you are using the "sandbox" environment, is there a particular reason for that? Does it work for you if upload using the default "production" environment?

**Comment by yyalansavage** [comment] 2024-04-26 14:11
Seems there was a problem with this for the sandbox environment only, which should now be fixed on the back end.

**Closed by yyalansavage** 2024-04-26 14:11 UTC
Labels: ide-bug

**Comment by YYDan** [comment] 2024-04-26 15:06
You should find you can upload okay now / your existing upload might work already. Either way, the servers have been fixed - this is not a GameMaker bug.

**Comment by eliehanna0** [comment] 2024-04-27 00:03
Awesome thank you so much!
