### ISSUE TITLE
Small tileset use incorrect collision

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#1553] opened 2023-08-18 13:16 UTC
### Description
When working with extremely small tilesets (such as the included one) the collision is off.

### Steps To Reproduce
Create a tilemap 2x8 (any number of tiles)
Create a 1x1 pixel.

Fill in tilemap in room and create an object that tests the collision using the 1x1. collision mask is off by a single pixel to the left

[36d2f7df-9e20-4567-8ffd-e1d9f1670dc5](https://api.gamemaker.io/api/github/downloads/36d2f7df-9e20-4567-8ffd-e1d9f1670dc5)

**Comment by YYDan** [comment] 2023-08-18 13:20
Looks at first glance to be duplicate of #1548

**Comment by michael-mcmullen** [comment] 2023-08-18 17:33
Could be, I swiched to a 32x32 tilesize and the initial point of contact is still a single pixel to the left and up.

https://github.com/YoYoGames/GameMaker-Bugs/assets/811123/fc398e5d-914c-426a-9d13-1395d76cd554

**Comment by jackerley** [comment] 2023-08-28 12:41
Turned out it wasn't a duplicate of #1548 fixed now

**Closed by jackerley** 2023-08-28 12:41 UTC
Labels: runner-bug, project
