### ISSUE TITLE
Add the esc key to close a search box

### ISSUE THREAD

**Issue by vxhaynes** [YoYoGames/GameMaker-Bugs#6644] opened 2024-07-12 22:55 UTC
### Is your feature request related to a problem?

Can you add the ability to close a search by hitting the esc key

### Describe the solution you'd like

If I use ctrl+f or ctrl+shift+f to search thru some code can hitting the escape key close that search so I can go back to coding

### Describe alternatives you've considered

I mean you can currently click the X to close it but if I'm on my laptop then I gotta use the trackpad to move the mouse allllll the way up to the search box to close it and my poor wrist is getting chronic pain and I don't have health insurance so I can't afford a doctor visit to fix it 😭

**Comment by YYDan** [comment] 2024-07-22 07:55
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3463

**Closed by YYDan** 2024-07-22 07:55 UTC
Labels: feature request
