### ISSUE TITLE
Add native support for Isometric Tiles in GameMaker

### ISSUE THREAD

**Issue by Kyu321** [YoYoGames/GameMaker-Bugs#8581] opened 2024-12-01 21:17 UTC
### Is your feature request related to a problem?

I'm always frustrated when I try to create isometric games in GameMaker, as the editor doesn't natively support isometric grids. Setting up the grid, snapping, collision logic, and layering requires custom solutions, which are time-consuming and challenging, especially for beginners. It also limits the use of the built-in tilemap editor.

### Describe the solution you'd like

I would like to see native support for isometric tiles, including:

An option in the tileset editor to define grids as isometric with adjustable tile dimensions (e.g., 64x32).
A toggle in the room editor to switch between orthogonal and isometric grids, allowing snapping for tiles and objects.
Integrated collision detection for isometric grids, enabling better interaction between tiles and objects.
This would make GameMaker much more user-friendly for creating isometric games like Hades, RollerCoaster Tycoon, or Age of Empires.

### Describe alternatives you've considered

Currently, creating isometric games in GameMaker requires custom implementations, such as:

Manually coding grid logic for snapping, rendering, and layer management.
Using external tools to design isometric maps, then importing them into GameMaker.
Writing scripts for collision detection, which can be prone to errors and harder to optimize.
These workarounds add a significant amount of complexity to development, especially for those who are new to GameMaker. Native support would streamline the process and allow developers to focus on gameplay rather than underlying systems.

**Comment by YYDan** [comment] 2024-12-02 09:29
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2893

**Closed by YYDan** 2024-12-02 09:29 UTC
Labels: feature request
