### ISSUE TITLE
Getting error building any project in v2024.4.0.137

### ISSUE THREAD

**Issue by XorDev** [YoYoGames/GameMaker-Bugs#5723] opened 2024-05-02 21:58 UTC
### Description
Core Resources : IDE Message - ProjectLoad_ErrorTitle : ProjectLoad_ErrorMessage ( C:/Users/Jon/Documents/GameMaker/GameMakerStudio2/Projects/Fun/Duel/options/ios/options_ios.yy(7,3): GMSC Error: option_ios_cocoapods_checkbox expected. )
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GMAssetCompiler.Loader.<>c__DisplayClass5_0.<LoadGMS2CreateAssets>b__2(ResourceBase _project)
   at YoYoStudio.Resources.ProjectInfo.<>c__DisplayClass23_0.<LoadProject>g__handleFailure|4(String message) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 294
   at YoYoStudio.Resources.ProjectInfo.LoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Boolean _triedProjectTool) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 322
   at GMAssetCompiler.Loader.LoadGMS2CreateAssets(String _filename)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
[createdump] Writing minidump to file C:\ProgramData\GameMakerStudio2\Dumps\gmdump.23400.dmp
[createdump] Dump successfully written
Igor complete.
elapsed time 00:00:06.5218468s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\Jon\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 05/02/2024 17:56:34
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[5a2a19f2-9bbe-4d67-87d4-ddfa8859e9ce](https://api.gamemaker.io/api/github/downloads/5a2a19f2-9bbe-4d67-87d4-ddfa8859e9ce)

**Comment by YYDan** [comment] 2024-05-03 08:31
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5719

**Closed by YYDan** 2024-05-03 08:31 UTC
Labels: build-bug, project
