### ISSUE TITLE
Code Editor 2: Refactor dialog box is non-responsive

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5717] opened 2024-05-02 19:29 UTC
### Description

When you ctrl + R to refactor something, the dialog box that pops up is bugged.

![refactor ce2](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/ce0b446f-7821-4d47-a220-5d7e6b58325a)

You can type into the text field, X-out, or hit Cancel (fortunately), but you can't drag the window around with the cursor, hit Enter in the text field, or click Apply.

### Expected Change

The dialog box to respond

### Steps To Reproduce

1. Start GameMaker
2. Enable CE2
3. Refactor something
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment] 2024-06-28 15:08
Unable to reproduce the behavior shown in the video but I did find an exception being thrown in some cases which might have contributed to the shown behavior. This is now fixed. In addition, a progress bar has been added for refactoring to indicate that work is being done before the window is dismissed which might also have contributed to perceptions of non-responsiveness.

**Closed** 2024-07-02 14:57 UTC
Labels: ide-bug

**Comment by sihammill** [comment] 2024-07-17 13:12
Fix verified in IDE v2024.800.0.592  Runtime v2024.800.0.616
