### ISSUE TITLE
Sounds are not processed when running or exporting on HTML5

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#5422] opened 2024-04-10 14:46 UTC
### Description
Sound files don't appear to be processed by the asset compiler at all - they're not in any of the temporary directories, nothing about them is in the console output in the IDE,  and sound files can't be accessed by a web browser when running a HTML5 game from the IDE

### Steps To Reproduce
1. Run the attached project with the HTML5 export module and in a browser, open the develoepr tools
2. Observe all the 404 errors on sound files
3. On clicking the play button, observe a crash as the game cannot handle missing sounds

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22635.0

[b8c4248d-3ec9-4c99-bd2b-d031b4e70996](https://api.gamemaker.io/api/github/downloads/b8c4248d-3ec9-4c99-bd2b-d031b4e70996)

**Comment by toby-yoyo** [comment] 2024-04-10 15:06
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5283

**Comment by stuckie** [comment] 2024-04-11 08:39
Closing as above

**Closed by stuckie** 2024-04-11 08:39 UTC
Labels: build-bug, project
