### ISSUE TITLE
Not Load  Spine exported file

### ISSUE THREAD

**Issue by albertodolci** [YoYoGames/GameMaker-Bugs#1532] opened 2023-08-15 17:10 UTC
### Description
If I try to load an Exported Json that came from a spine file that use multiple 
animation set for multiple skins, it fail to load in Game Maker

### Steps To Reproduce
I will add my file with the project (and also exported version) that not work on GMS

the attached file is a gms project and in the included files you will find spine project and also json export

[aa4ffa24-c9ab-41b2-9f8a-589f7ea27077](https://api.gamemaker.io/api/github/downloads/aa4ffa24-c9ab-41b2-9f8a-589f7ea27077)

**Comment by yoyo-danielc** [comment] 2024-06-04 15:39
Fix merged into the 2024.08 branch.

The root cause here is the asset compiler trying to generate a preview image - it looks for a skin with any valid vertices and then draws it, using their bounds for the preview image size and sprite offset, trouble is, the default skin in your project has no vertices, and another skin has all vertices at co-ordinate 0,0, so the asset compiler attempts to create a zero-size preview image and crashes.

The fix in August makes the asset compiler skip over skins which have all vertices at the same co-ordinate, in the mean time, ensuring the default skin in your sprite is usable for the preview image should work around it.

**Closed by yoyo-danielc** 2024-06-04 15:39 UTC
Labels: ide-bug

**Comment by alicemoretti** [comment] 2024-08-02 14:35
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625. 

Thank you.
