### ISSUE TITLE
Report a bug in the comment feature in the gml editor

### ISSUE THREAD

**Issue by jasonfoby** [YoYoGames/GameMaker-Bugs#7304] opened 2024-08-15 16:16 UTC
### Is your feature request related to a problem?

My native language is Korean. When I try to write a comment in Korean while writing code in the gml editor, there is a bug where the text is written in place when I write in Korean. When I write a comment in another language, it is written normally.

### Describe the solution you'd like

Rather than a solution, I would like you to review this part as there was no bug regarding comments in previous versions.

**Comment by YYDan** [comment] 2024-08-16 08:12
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6494

**Closed by YYDan** 2024-08-16 08:12 UTC
Labels: feature request
