### ISSUE TITLE
TextureGroup Bug Example Project

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#5378] opened 2024-04-08 09:27 UTC
### Description
Hey there,

I spent some hours to investigate the bug further, here is a sample project, which will show you the bug.

It contains 3 Configurations and 3 TextureGroups
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/19487451/12ddf953-1f19-457f-aa9f-74a7d4a54b32)   ![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/19487451/6f6b2681-e5f5-4391-93b0-99640ff9bcd9)

### Steps To Reproduce
* Open the project
* Look at the sprites and look at the the TextureGroups
* The circles are in texturegroup "circles", the boxes in "boxes"
* IMPORTANT: Select Configuration "Default"
* Select some sprites in the asset browser, choose "Assign Texture Group -> Default"  --> WORKS
* Assign them back to where they came from
* NOW CHANGE CONFIGURATION to any of the subconfigurations
* Repeat: Select some Sprites -> Assign TextureGroup "Default"
* "GameMaker has become unstable" (if you are lucky) or a instant crash with crash dump (if you are not so lucky)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/19487451/32911368-dc6d-46cf-a9ed-0a5c3ce63d7e)

Hope this helps!

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[0957f5e3-6f2a-47bb-af18-4c238f44d4a4](https://api.gamemaker.io/api/github/downloads/0957f5e3-6f2a-47bb-af18-4c238f44d4a4)

**Comment by Grisgram** [comment] 2024-04-09 13:30
Hello @stuckie 

I think, I found the core problem of the bug, but we need you to fix it :-)

If you look into the .yy file of such a damaged sprite, you see, that the key `ConfigValues` gets created, when you tinker with the TexturePage of a sprite (= assign another one), while not in configuration "Default".

The bug is, that it seems, GMS serializes the entire texturepage object to the `textureGroupId` value, and not only the textureGroupId.

What GMS currently writes into `ConfigValues` (the whole texturepage object):
```
  "ConfigValues":{
    "release":{
      "textureGroupId":"{\"ConfigValues\":{\"release\":{\"groupParent\":\"null\",\"compressFormat\":\"bz2\",\"loadType\":\"default\"}},\"isScaled\":true,\"compressFormat\":\"bz2\",\"customOptions\":\"\",\"loadType\":\"default\",\"directory\":\"\",\"autocrop\":true,\"border\":2,\"mipsToGenerate\":0,\"groupParent\":null,\"targets\":-1,\"resourceType\":\"GMTextureGroup\",\"resourceVersion\":\"2.0\",\"name\":\"ui\",\"%Name\":\"ui\"}",
    },
  },

```

...if you change this to a textureGroupId object:
```
"ConfigValues":{
    "release":{
      "textureGroupId":"{\"name\":\"ui\",\"path\":\"texturegroups/ui\"}",
    },
  },
```

all is good and GameMaker can handle the sprite as usual.
So we can assign sprites to different TexturePages based on the configuration.

So it looks, it's just a mini-bug, just the wrong object serialized.

Hope this helps you to tackle it down

kind regards
Gris

**Comment by stuckie** [comment] 2024-04-09 13:47
Ah, that means it is a duplicate of another bug we just fixed, so will get them tied together and verified.

Thanks!

**Comment by stuckie** [comment] 2024-04-10 11:04
Yep, this is a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5333 and will be fixed in the next beta!

**Closed by stuckie** 2024-04-10 11:04 UTC
Labels: project, crash
