### ISSUE TITLE
`instance_create` functions: `var_struct` with `x` and `y` isn't setting `xstart` and `ystart`

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4503] opened 2024-01-25 15:17 UTC
### Description

Creating an instance using `instance_create_depth()` or `instance_create_layer()` and passing in a struct with x and y values will cause that instance to be created at that struct's x and y. However, that instance's `xstart` and `ystart` will be set according to the x and y arguments passed in, even though it isn't created at that location.

For example:
```gml
instance_create_depth(0, 0, 0, oPlayer, {x:50, y:50})
```
will create `oPlayer` at `50,50`, but its `xstart` and `ystart` variables will both equal 0, not 50. Not sure if this is intended behaviour or a bug, but it seems counterintuitive and has caused issues in my projects.

### Expected Change

Set `xstart` and `ystart` according to `var_struct`'s x and y, if those variables exist.

### Steps To Reproduce

[xstart and ystart.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14053881/xstart.and.ystart.zip)

1. Start GameMaker
2. Create object `Object1`
3. In `Room1`'s creation code, type:
```gml
with instance_create_depth(0,0,0,Object1, {x:50, y:50})
{
	show_message($"xstart: {xstart}\n" + $"ystart: {ystart}")
}
```
5. Run the game and see the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by attic-stuff** [comment] 2024-01-25 15:40
think that's cause the struct is updating x and y, not setting initial x and y. if you want to change xstart and ystart as well, they are not read-only and you can pass new values in along with that struct. (personally i do not believe this behavior should change)

**Comment by backYard321** [comment] 2024-01-25 16:05
> think that's cause the struct is updating x and y, not setting initial x and y. if you want to change xstart and ystart as well, they are not read-only and you can pass new values in along with that struct. (personally i do not believe this behavior should change, given that if you place an object at 0,0 in the room editor, and then its create event change its position to 128, 128 then xstart and ystart will still show 0,0)

I definitely agree with the latter part about xtstart/ystart being set before the create event! But given that the `var_struct` sets them pre-create event, I'd expect xstart/ystart to be changed as well. I appreciate that they're both set-able variables though, and changing them through the struct is better than nothing, but it does feel like kind of a sketchy workaround.

**Comment by attic-stuff** [comment] 2024-01-25 16:19
it is not a work around because its intended behavior haha. with regard to the pre-create event: the position of the instance is resolved before pre create, when the instances are originally pooled i believe. a sort of pre-pre-create process that you do not have access to.

**Comment by RefresherTowel** [comment] 2024-01-25 17:03
Yeah, I agree with attic-stuff in regards to this. Setting one variable and having it invisibly set another is kinda clunky, especially since it would only be in this one exact scenario that setting x and y effects setting xstart and ystart (as opposed to setting vspeed and hspeed _always_ adjusting speed and direction). Just set them both if you want them both to have the same value, it's much more explicit and readable as code.

**Comment by backYard321** [comment] 2024-01-25 17:19
> Yeah, I agree with attic-stuff in regards to this. Setting one variable and having it invisibly set another is kinda clunky, especially since it would only be in this one exact scenario that setting x and y effects setting xstart and ystart (as opposed to setting vspeed and hspeed _always_ adjusting speed and direction). Just set them both if you want them both to have the same value, it's much more explicit and readable as code.

I mean I consider this pretty much the same as passing in x and y and having that alter xstar/ystart, just done through the struct argument instead of the x and y arguments - it's about as clunky as the existing behaviour.

**Comment by RefresherTowel** [comment] 2024-01-25 17:35
But they are separate variables? You are changing the x and y in the struct _after_ the instance has been assigned a position (which is the x and y in the instance_create_*() arguments). Naturally, the instance _did_ start at 0, 0, and xstart and ystart were assigned those values and after that you then changed its position using the injected struct. So I'm not sure why it's clunky to have to update the xstart and ystart manually, since it did not start at the new x and y you provide in the struct. Plus, as I said before, updating it in the struct is _explicit_ coding. It's better form to have it readable within the code that you are updating the starting position, rather than having it hidden in the background. Less chance for coders to be caught unaware.

**Comment by backYard321** [comment] 2024-01-25 18:03
I re-read the manual section, and you're definitely correct - the `var_struct` sets variables after "variable definitions" but before the create event, so I'm wrong to compare it to setting the x and y arguments in the create function. 

Personally, I would want xstart/ystart to be set after this, so that it also takes into account how x/y is set in variable definitions as well, but there's a chance that this will cause unexpected behaviour in people's projects so I'm not sure that it's ultimately worth it.

**Comment by attic-stuff** [comment] 2024-01-25 19:31
> I re-read the manual section, and you're definitely correct - the `var_struct` sets variables after "variable definitions" but before the create event, so I'm wrong to compare it to setting the x and y arguments in the create function.

again, remember, that if you put the instance in location A and use the create event to change it to location B, xstart and ystart will be location A and not location B. these two variables are set _before_ the create event. setting x and y through the creation struct is comparable to changing the x and y in a create event, but the issue you're having is xstart and ystart are resolved long before the create event anyways.

**Comment by backYard321** [comment] 2024-01-25 20:17
Yeah I agree, I think we're both saying the same thing now. While I personally would like any x/y manipulation that takes place before the create event to alter xstart/ystart (including manipulation taking place in create function arguments, room placement, variable definitions, and `var_struct`), I don't know whether other people would find the latter two more helpful or less helpful.

**Comment by rwkay** [comment] 2024-01-25 20:19
It is very unlikely that will be changing the behaviour at this stage...

**Comment by stuckie** [comment] 2024-01-26 09:42
Closing as above.

**Closed by stuckie** 2024-01-26 09:42 UTC
Labels: runner-bug
