### ISSUE TITLE
renaming/creating/deleting assets one after another can cause freezing

### ISSUE THREAD

**Issue by jack27121** [YoYoGames/GameMaker-Bugs#2274] opened 2023-11-23 10:03 UTC
### Description
if you create an asset and right after rename it before analyzing has finished it can cause gamemaker to freeze and need a restart
same if you delete multiple things and so on.

Also analyzing the project takes a pretty long time even when just renaming one single asset

[edeccb47-1ec9-4a3f-a543-161644136d3d](https://api.gamemaker.io/api/github/downloads/edeccb47-1ec9-4a3f-a543-161644136d3d)

**Comment by jack27121** [comment] 2023-11-23 10:03
In the current beta

**Comment by stuckie** [comment] 2023-11-24 09:36
Ideally we will need a project for this, as the size and complexity of the project will determine the amount of work it does while analysing the project.

**Comment by jack27121** [comment] 2023-11-24 09:39
> Ideally we will need a project for this, as the size and complexity of the project will determine the amount of work it does while analysing the project.

I've resubmitted the bug here with project https://github.com/YoYoGames/GameMaker-Bugs/issues/2283

**Comment by jack27121** [comment] 2023-11-24 09:40
@stuckie i've resubmitted the bug with the project included

**Comment by stuckie** [comment] 2023-11-24 10:08
Thanks, closing this as duplicate of #2283

**Closed by stuckie** 2023-11-24 10:08 UTC
Labels: ide-bug

**Comment by mgeddesGM** [comment] 2023-11-30 09:40
verified as duplicate of #2283
