### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3788] opened 2023-06-06 15:06 UTC
User request message on ticket [Ticket #190163]

 

Feature Type: feat_addition_ide
Description: Hi YOYO GAMES

I would like to suggest few things in connection with vector graphics support:

1. Support for SVG vector graphic format in GMS2. I do use vector (SWF) graphics in all my applications and it works great, but at the same it is a big hurdle to work in Inkscape(I do prefer Inkscape workflow) export, reopen in Illustrator and then exporting in the right format. It would be absolutely awesome with SVG support.

2. The precision slider on vector graphics is a bit lackluster, I would like some more feedback, something like how many triangles are left in the picture with a new precision setting.

3. Have the opportunity to set/read a specific value of the slider, right now I have no idea what I set it on, and if it is the same as some other graphics. Maybe even being able to set the slider value or the amount of triangles in the graphic, that could be very nice and give a lot more control.

I hope you will consider these suggestions.

If you like any further feedback or info, you are always welcome to contact me.

Have a nice day.

Sincerely
Gunnar Hohlweg
Benefit: I think these three improvements would lover the entry level and usability of vector graphics in GMS(Inkscape is free, new users could be pushed away by expensive external tools requirements like Illustrator), and at the same time speed up the workflow and give greater control for more advanced users like me.

**Comment by YYDan** [comment] 2024-10-25 10:28
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5895

**Closed by YYDan** 2024-10-25 10:28 UTC
Labels: feature request, import
