### ISSUE TITLE
Feather: Issues with non-specific type "Asset" returned from asset_get_ids()

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6591] opened 2024-07-09 16:06 UTC
### Description

Using `asset_get_ids()` to get all assets of a specific type will return those assets as an array of non-specific type `Asset`, instead of a specific asset type like `Asset.GMObject`, which triggers red feather message GM1041 when used as an argument for any function related to the type of asset (for example using `object_get_name()` with an object returned from `asset_get_ids(asset_object)`).

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/59960214/1044030a-200d-4d1d-8c68-af3ba8622c49)

While this feather message is technically correct, as the type doesn't exactly match what is expected, the code functions fine, and as far as i can tell there is no way to convert from a non-specific `Asset` to the specific asset type, so there should either be an exception to this feather message in this situation, a way to convert from `Asset` to a specific asset type, or `asset_get_ids()` should return the assets as their specific asset type to begin with.

Sample project: [asset_get_ids feather issue.zip](https://github.com/user-attachments/files/16146216/asset_get_ids.feather.issue.zip)

### Steps To Reproduce

1. Start GameMaker
2. Make a new project
3. Make a new object with event code or a script 
4. Write the lines: `objects = asset_get_ids(asset_object);` and `objects = asset_get_ids(asset_object);` into it
5. Observe the feather message

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly), 2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by KormexGit** [comment] 2024-07-10 08:50
Same as #4800

**Comment by stuckie** [comment] 2024-07-11 15:21
Duplicate of #4800

**Closed by stuckie** 2024-07-11 15:21 UTC
Labels: ide-bug
