### ISSUE TITLE
Code Editor 2 [Inheritance] : Inherited events are not show in the child's editor if the editor is open when the inheritance is set

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#5216] opened 2024-03-21 16:48 UTC
### Description

On  IDE v2024.400.0.522  Runtime v2024.400.0.543, when the user opens an object in the CD2 and then sets that object to be the child of another object, the inherited events from the parent are not displayed in the child's editor. 

The events appear after closing an re-opening the editor. 
Please see the video below: 

https://github.com/YoYoGames/YoYoStudio/assets/59605840/73a16b20-b6ea-4a2c-8574-890361f7f265

### Steps To Reproduce

1. Start GameMaker
2. Enable CD2 if needed
3. Open a project with objects with events
4. Create a new object
5. Open the new object in CD2
6. Set the new object as a child of an object with events
7. Observe that the inherited objects are not shown in the child's editor

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.522  Runtime v2024.400.0.543

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by YYDan** [comment] 2024-08-08 08:27
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5608

**Closed by YYDan** 2024-08-08 08:27 UTC
Labels: ide-bug
