### ISSUE TITLE
[Project Tools] Project conversion error

### ISSUE THREAD

**Issue by Ttanasart-pt** [YoYoGames/GameMaker-Bugs#5138] opened 2024-03-29 04:40 UTC
### Description
Trying to open some project from 2023.11 to 2024.2 (and beta 2024.4) gives out "Project load failed" error.

Clicking "ok" will show another warning "Load Error: GMSC LINK: Cannot find folder path".

Repeated attempt will cause the project to load with folder being place in the wrong location, multiple folders with the same name, and file missing.

### Steps To Reproduce
So far only replicable with large project. I've attached the affected project.

- Load the project "PixelComposer.yyz" in to GameMaker IDE 2024.2 and above.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.526 Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[702cafeb-eaa9-4d91-95ca-7e73588ff57b](https://api.gamemaker.io/api/github/downloads/702cafeb-eaa9-4d91-95ca-7e73588ff57b)

**Comment by stuckie** [comment] 2024-04-15 11:53
Duplicate of #4940 
This looks to have been the same cause as above and has been fixed in current April betas!

**Closed by stuckie** 2024-04-15 11:53 UTC
Labels: ide-bug

**Comment by alicemoretti** [comment] 2024-04-15 14:18
Verified fixed on IDE v2024.400.0.541  Runtime v2024.400.0.560. 

Thank you.
