### ISSUE TITLE
Runtime 2024.6 broke string_concat()

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#6518] opened 2024-07-04 07:03 UTC
### Description
In the latest release, string_concat() doesn't work when the first parameter is in a local variable. The second parameter is ignored and no string concatenation is performed.

### Steps To Reproduce
var _test = "prefix";
var _finalText = string_concat(_test, "_sufix");

The result won't be "prefix_sufix" as before but only "prefix"

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

### Which platform(s) are you seeing the problem on?
Windows

[0cf6cb16-f4a8-4e6a-8b3d-5c065dcf472b](https://api.gamemaker.io/api/github/downloads/0cf6cb16-f4a8-4e6a-8b3d-5c065dcf472b)

**Comment by YYDan** [comment] 2024-07-04 07:58
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/6480

**Closed by YYDan** 2024-07-04 07:58 UTC
Labels: runner-bug, project
