### ISSUE TITLE
Cannot place a sprite ontop of another sprite using the alt key

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#2457] opened 2023-12-12 08:18 UTC
### Description
When placing decorative sprites on an asset layer, you can use the alt key to place copies of a sprite by left-clicking the mouse.

But when the mouse position overlaps with the bounding box of another asset, instead of placing the new asset, the overlapping asset gets selected.

I think it would make more sense to give the placing of the new asset priority because holding down the alt key is a deliberate action - the user expects something to be placed down.

### Steps To Reproduce
1) Place a sprite on an asset layer

2) Hold the alt key and try to place another copy of it near the previous one (bounding boxes need to overlap)

3) Instead of a new sprite, the previous one gets selected.

[9709e42c-a3ab-41d4-b0c9-ad3609d9b46f](https://api.gamemaker.io/api/github/downloads/9709e42c-a3ab-41d4-b0c9-ad3609d9b46f)

**Comment by YYDan** [comment] 2023-12-12 09:15
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2414

**Closed by YYDan** 2023-12-12 09:15 UTC
Labels: ide-bug
