### ISSUE TITLE
Draw Editor event

### ISSUE THREAD

**Issue by adriandpad** [YoYoGames/GameMaker-Bugs#8153] opened 2024-10-27 06:59 UTC
### Is your feature request related to a problem?

A "Draw Editor" event would allow you to make visual helpers while in the room editor. Preferably when you select an object it would run. Even . It can be time consuming to check where exactly things like collision rectangles are or where a sprite will be drawn under conditions.

### Describe the solution you'd like

A practical example from my own project would be projecting shapes or sprites based on variable definitions. I won't know exactly where an object draws on its Z-axis until I run the game. It might be nice to see hitboxes and other sensors. Say I have a large collection rectangle for an object. I could at least preview it while level editing. Basic draw events like shapes and text would be handy for at a glance previews of an object's behaviour.

### Describe alternatives you've considered

Dummy assets and layers that get turned off. There's not really a good alternative.

### Additional context

We had a simple properties rectangle preview in our Owlboy editor that helped speed up workflows. I could click objects to see where their activation zone was, barriers, damage rectangles, movement ranges, things like that.

**Comment by KormexGit** [comment] 2024-10-27 07:47
Similar to #2839

**Comment by iampremo** [comment] 2024-10-28 09:52
Duplicate of #2839

**Closed by iampremo** 2024-10-28 09:52 UTC
Labels: feature request
