### ISSUE TITLE
IDE: Having a project load failure will disable many IDE buttons until the IDE is reloaded

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8334] opened 2024-11-07 20:42 UTC
### Description
If you have a project load failure and then either fix it or open a different project, many IDE buttons will be greyed out and unable to be pressed until the IDE is restarted. This includes the buttons for selecting your target platform, the run button, debugger, game options, etc. You can still use the hotkeys for the disabled buttons.

![Image](https://github.com/user-attachments/assets/b99f9068-7115-4365-ad5e-ea4679f1149d)

### Steps To Reproduce
1. Open a project that fails to load. You can easily force a project load failure by following the steps in #8333.
2. Either resolve the project load failure or open a different project.
3. See that many of the buttons at the top of the IDE are greyed out.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.674 Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[11eeaf3a-df5d-4e53-a374-ee734859aec4](https://api.gamemaker.io/api/github/downloads/11eeaf3a-df5d-4e53-a374-ee734859aec4)

**Comment by Emc1923** [comment] 2024-11-08 08:44
Dupe of https://github.com/YoYoGames/GameMaker-Bugs/issues/8340

**Comment by stuckie** [comment] 2024-11-08 09:49
Duplicate of #8340

**Closed by stuckie** 2024-11-08 09:49 UTC
Labels: ide-bug
