### ISSUE TITLE
In-Game: Camera and Layer issues in Runtime 2024.800.0.628

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#7183] opened 2024-08-09 09:19 UTC
### Description
Some of the rooms in my game have a bunch of camera and/or layer rendering issues. It's almost as if the game has a tiny viewport in the upper left corner. But then it also doesn't affect all the layers.

I attached a screenshot and a video.

### Steps To Reproduce
To repro the bug, use the big project I submitted before. @stuckie should know how to access it. They also linked an internal GDrive copy in this issue: #7043

Inside the obj_game Create event, change the Macros to:

DEBUG 1
live_enabled 0

DEBUG_ROOM:

rm_jungle_11 -> The bug appears in this room
rm_jungle_33 -> Bug doesn't happen in this room
rm_jungle_9 -> Invisible layers

If the project is not sufficient to reproduce the bug I'd be happy to resubmit an updated version next week.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files
* 2024-08-09 11_12_31-The Adventures of Kincaid.png
* 2024-08-09 10-59-11.mp4

[9c4cbf0a-6702-485e-b7bb-f216758edcf7](https://api.gamemaker.io/api/github/downloads/9c4cbf0a-6702-485e-b7bb-f216758edcf7)

**Comment by nullbunny** [comment] 2024-08-09 09:25
Some early investigation notes:
- The affected and unaffected rooms share the same room settings in terms of size and viewport settings.
- Toggling fullscreen and switching through the resolutions doesn't fix or affect the bug.

**Comment by YYDan** [comment] 2024-08-09 09:26
Hmmm, that Beta release has the change for https://github.com/YoYoGames/GameMaker-Bugs/issues/5934 in it. so I wonder if the problem you're seeing here is just that your project cache needs to be cleared, or something simple.

All is well for these rooms if you set your new IDE back to Beta 3's runtime (624)?

**Comment by YYDan** [comment] 2024-08-09 09:28
Also, is this actually when using the new GMRT runtime only?

**Comment by nullbunny** [comment] 2024-08-09 10:29
Cleaning the project didn't help.

I first noticed the bug when I set up GameMaker Beta very fresh for the first time for a colleague. Then I saw there was a new runtime released yesterday. When switching to it on my workstation, the bug appeared for me too.

When I switch back to the previous runtime (624) the bug disappears.

**Comment by KormexGit** [comment] 2024-08-10 07:02
This is happening for me too, doing any room transition makes my view only show the top left two thirds or so, cropping out the bottom right. New to latest beta

**Comment by JonnoRobson** [comment] 2024-08-12 09:09
I can confirm this is the same issue with scissor rects on effects as https://github.com/YoYoGames/GameMaker/issues/4272 and so will be fixed in the next BETA release.

**Comment by JonnoRobson** [comment] 2024-09-02 15:51
Update on this issue: Its likely this issue is not a duplicate of https://github.com/YoYoGames/GameMaker/issues/4272 as previously thought and is instead the same issue as https://github.com/YoYoGames/GameMaker-Bugs/issues/7252. I'll reopen this issue until a fix is found for both. In the meantime the same workaround for the connected issue should work in this project - in any affected rooms you should go into the settings for "Viewport 0" and change the viewport width and height so that they match the room dimensions. It is not necessary to enable viewports for the workaround to work.

**Comment by JonnoRobson** [comment] 2024-09-02 16:24
The effect rendering issue that was causing the problems in rooms with non-matching room and viewport dimensions should be fixed in the upcoming August GameMaker release. Disabled viewports are no longer applied when rendering effect layers.

**Closed by JonnoRobson** 2024-09-02 16:24 UTC
Labels: runner-bug
