### ISSUE TITLE
UI/UX: [Ubu IDE] Initial window size and DPI are not able to adapt to launching on small secondary monitor when a much larger primary is found

### ISSUE THREAD

**Issue by leroyron** [YoYoGames/GameMaker-Bugs#8361] opened 2024-11-10 15:03 UTC
### Description

The default general settings for the display 640 by 480 on my Ubuntu I think is too large on my first startup. I had to drag the IDE to large T.V. screen to find the settings. The settings off screen, No scrollbars and could not adjust. ![Image](https://github.com/user-attachments/assets/65dfe621-f0e7-426d-ab41-af8c9cefa157)
![Image](https://github.com/user-attachments/assets/a54514a2-70a2-4d65-be3c-019c5c2c61ab)
![Image](https://github.com/user-attachments/assets/4019e8dd-bc90-4c82-86b8-6c4f86d2ad1d)

### Expected Change

Initial scale or scroll bars.

### Steps To Reproduce

1. Start GameMaker after .deb install.
2. Seen scaling issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment] 2024-11-11 14:27
Hello,

Unfortunately, we are aware of this and haven't had a chance to track down exactly what is going on.
As a work around, you can place the attached dpi_override.json in ~/.local/share/GameMakerStudio2-Beta which should get you going.

[dpi_override.json](https://github.com/user-attachments/files/17703712/dpi_override.json)

**Comment by stuckie** [comment] 2024-11-11 14:28
Duplicate of #3196

**Closed by stuckie** 2024-11-11 14:28 UTC
Labels: ide-bug
