### ISSUE TITLE
Sequence audio plays from the left when created in-game

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#170] opened 2023-07-28 12:35 UTC
GM-2693

See the attached project. The Sequence in question is *seq_baddie_defeat*, and it plays when an enemy is defeated in-game. The audio that plays from it comes from the left speaker only.

Moving the audio track's position to the very left changes it. This behaviour makes me think that the default listener is at 0,0 in the room, but even then it seems to flip the stereo audio.

**Comment by toby-yoyo** [comment] 2024-11-06 15:24
This isn't a bug. There are two issues with the project:
- As suspected in the description, the audio listener is positioned at (0, 0, 0) and is never moved from there. This causes all positional sounds to be heard relative to that location.
- The listener orientation is also never configured. As documented in the manual (and shown in the image below), the default listener orientation has its up-y value set to 1, which places it upside-down relative to how sounds are generally perceived. This is the reason the sound comes from the left instead of the right as you might expect based on the first point.
![Image](https://github.com/user-attachments/assets/ca3d0367-8496-4559-a27a-131ab935a3f2)

When resolving both of these issues, the spatialisation problem in the description is also resolved. Attached is a quick hack of the original example project that shows this. To test this:
- Open and run this project: https://drive.google.com/file/d/15953oDK7jirtYd9X2yKzHkOoVZzly7-O/view?usp=sharing
- Start the game.
- Run up to the first skeleton enemy and attack it (space) from the left.
- You should hear the skeleton's death sfx from the right as expected.

Closing this as 'Not a bug'.

**Closed by toby-yoyo** 2024-11-06 15:24 UTC
Labels: runner-bug, import
