### ISSUE TITLE
[GMRT] structs literals can't use `true` or `false` as members

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7445] opened 2024-08-27 13:41 UTC
### Description

compiling:

```
a = { true: false }
```

this is not possible in GMRT, it's possible in VM and YYC

### Expected Change

should be allowed

### Steps To Reproduce

1. Start GameMaker
2. Try to compile the sample code
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by KormexGit** [comment] 2024-08-27 14:21
Duplicate of #7382

**Closed** 2024-11-06 16:18 UTC
Labels: build-bug, gmrt-bug
